# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: thunderid
description: A Helm chart for ThunderID - Open-source IAM stack
type: application
version: 1.0.0
appVersion: "1.0.0"
