// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourceserverprovidermock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// NewResourceServerProviderMock creates a new instance of ResourceServerProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceServerProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceServerProviderMock {
	mock := &ResourceServerProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceServerProviderMock is an autogenerated mock type for the ResourceServerProvider type
type ResourceServerProviderMock struct {
	mock.Mock
}

type ResourceServerProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceServerProviderMock) EXPECT() *ResourceServerProviderMock_Expecter {
	return &ResourceServerProviderMock_Expecter{mock: &_m.Mock}
}

// GetResourceServer provides a mock function for the type ResourceServerProviderMock
func (_mock *ResourceServerProviderMock) GetResourceServer(ctx context.Context, id string) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServer")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServerProviderMock_GetResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServer'
type ResourceServerProviderMock_GetResourceServer_Call struct {
	*mock.Call
}

// GetResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceServerProviderMock_Expecter) GetResourceServer(ctx interface{}, id interface{}) *ResourceServerProviderMock_GetResourceServer_Call {
	return &ResourceServerProviderMock_GetResourceServer_Call{Call: _e.mock.On("GetResourceServer", ctx, id)}
}

func (_c *ResourceServerProviderMock_GetResourceServer_Call) Run(run func(ctx context.Context, id string)) *ResourceServerProviderMock_GetResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServerProviderMock_GetResourceServer_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServerProviderMock_GetResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServerProviderMock_GetResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string) (*providers.ResourceServer, *common.ServiceError)) *ResourceServerProviderMock_GetResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerByIdentifier provides a mock function for the type ResourceServerProviderMock
func (_mock *ResourceServerProviderMock) GetResourceServerByIdentifier(ctx context.Context, identifier string) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerByIdentifier")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServerProviderMock_GetResourceServerByIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerByIdentifier'
type ResourceServerProviderMock_GetResourceServerByIdentifier_Call struct {
	*mock.Call
}

// GetResourceServerByIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *ResourceServerProviderMock_Expecter) GetResourceServerByIdentifier(ctx interface{}, identifier interface{}) *ResourceServerProviderMock_GetResourceServerByIdentifier_Call {
	return &ResourceServerProviderMock_GetResourceServerByIdentifier_Call{Call: _e.mock.On("GetResourceServerByIdentifier", ctx, identifier)}
}

func (_c *ResourceServerProviderMock_GetResourceServerByIdentifier_Call) Run(run func(ctx context.Context, identifier string)) *ResourceServerProviderMock_GetResourceServerByIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServerProviderMock_GetResourceServerByIdentifier_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServerProviderMock_GetResourceServerByIdentifier_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServerProviderMock_GetResourceServerByIdentifier_Call) RunAndReturn(run func(ctx context.Context, identifier string) (*providers.ResourceServer, *common.ServiceError)) *ResourceServerProviderMock_GetResourceServerByIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePermissions provides a mock function for the type ResourceServerProviderMock
func (_mock *ResourceServerProviderMock) ValidatePermissions(ctx context.Context, resourceServerID string, permissions []string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, permissions)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePermissions")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, permissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, resourceServerID, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, permissions)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServerProviderMock_ValidatePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePermissions'
type ResourceServerProviderMock_ValidatePermissions_Call struct {
	*mock.Call
}

// ValidatePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - permissions []string
func (_e *ResourceServerProviderMock_Expecter) ValidatePermissions(ctx interface{}, resourceServerID interface{}, permissions interface{}) *ResourceServerProviderMock_ValidatePermissions_Call {
	return &ResourceServerProviderMock_ValidatePermissions_Call{Call: _e.mock.On("ValidatePermissions", ctx, resourceServerID, permissions)}
}

func (_c *ResourceServerProviderMock_ValidatePermissions_Call) Run(run func(ctx context.Context, resourceServerID string, permissions []string)) *ResourceServerProviderMock_ValidatePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServerProviderMock_ValidatePermissions_Call) Return(strings []string, serviceError *common.ServiceError) *ResourceServerProviderMock_ValidatePermissions_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *ResourceServerProviderMock_ValidatePermissions_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, permissions []string) ([]string, *common.ServiceError)) *ResourceServerProviderMock_ValidatePermissions_Call {
	_c.Call.Return(run)
	return _c
}
