// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entity

import (
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// newDeclarativeSystemCredentialHasherMock creates a new instance of declarativeSystemCredentialHasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDeclarativeSystemCredentialHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *declarativeSystemCredentialHasherMock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &declarativeSystemCredentialHasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// declarativeSystemCredentialHasherMock is an autogenerated mock type for the declarativeSystemCredentialHasher type
type declarativeSystemCredentialHasherMock struct {
	mock.Mock
}

type declarativeSystemCredentialHasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *declarativeSystemCredentialHasherMock) EXPECT() *declarativeSystemCredentialHasherMock_Expecter {
	return &declarativeSystemCredentialHasherMock_Expecter{mock: &_m.Mock}
}

// hashPlaintextCredentials provides a mock function for the type declarativeSystemCredentialHasherMock
func (_mock *declarativeSystemCredentialHasherMock) hashPlaintextCredentials(creds json.RawMessage) (json.RawMessage, error) {
	ret := _mock.Called(creds)

	if len(ret) == 0 {
		panic("no return value specified for hashPlaintextCredentials")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) (json.RawMessage, error)); ok {
		return returnFunc(creds)
	}
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) json.RawMessage); ok {
		r0 = returnFunc(creds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = returnFunc(creds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'hashPlaintextCredentials'
type declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call struct {
	*mock.Call
}

// hashPlaintextCredentials is a helper method to define mock.On call
//   - creds json.RawMessage
func (_e *declarativeSystemCredentialHasherMock_Expecter) hashPlaintextCredentials(creds any) *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call {
	return &declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call{Call: _e.mock.On("hashPlaintextCredentials", creds)}
}

func (_c *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call) Run(run func(creds json.RawMessage)) *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 json.RawMessage
		if args[0] != nil {
			arg0 = args[0].(json.RawMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call) Return(rawMessage json.RawMessage, err error) *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call) RunAndReturn(run func(creds json.RawMessage) (json.RawMessage, error)) *declarativeSystemCredentialHasherMock_hashPlaintextCredentials_Call {
	_c.Call.Return(run)
	return _c
}
