// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkimock

import (
	"context"
	"crypto"
	"crypto/tls"
	"crypto/x509"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewPKIServiceInterfaceMock creates a new instance of PKIServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPKIServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PKIServiceInterfaceMock {
	mock := &PKIServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PKIServiceInterfaceMock is an autogenerated mock type for the PKIServiceInterface type
type PKIServiceInterfaceMock struct {
	mock.Mock
}

type PKIServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PKIServiceInterfaceMock) EXPECT() *PKIServiceInterfaceMock_Expecter {
	return &PKIServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetAllX509Certificates provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetAllX509Certificates(ctx context.Context) (map[string]*x509.Certificate, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllX509Certificates")
	}

	var r0 map[string]*x509.Certificate
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]*x509.Certificate, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]*x509.Certificate); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetAllX509Certificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllX509Certificates'
type PKIServiceInterfaceMock_GetAllX509Certificates_Call struct {
	*mock.Call
}

// GetAllX509Certificates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PKIServiceInterfaceMock_Expecter) GetAllX509Certificates(ctx interface{}) *PKIServiceInterfaceMock_GetAllX509Certificates_Call {
	return &PKIServiceInterfaceMock_GetAllX509Certificates_Call{Call: _e.mock.On("GetAllX509Certificates", ctx)}
}

func (_c *PKIServiceInterfaceMock_GetAllX509Certificates_Call) Run(run func(ctx context.Context)) *PKIServiceInterfaceMock_GetAllX509Certificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetAllX509Certificates_Call) Return(stringToCertificate map[string]*x509.Certificate, serviceError *serviceerror.ServiceError) *PKIServiceInterfaceMock_GetAllX509Certificates_Call {
	_c.Call.Return(stringToCertificate, serviceError)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetAllX509Certificates_Call) RunAndReturn(run func(ctx context.Context) (map[string]*x509.Certificate, *serviceerror.ServiceError)) *PKIServiceInterfaceMock_GetAllX509Certificates_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertThumbprint provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetCertThumbprint(id string) string {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCertThumbprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PKIServiceInterfaceMock_GetCertThumbprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertThumbprint'
type PKIServiceInterfaceMock_GetCertThumbprint_Call struct {
	*mock.Call
}

// GetCertThumbprint is a helper method to define mock.On call
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetCertThumbprint(id interface{}) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	return &PKIServiceInterfaceMock_GetCertThumbprint_Call{Call: _e.mock.On("GetCertThumbprint", id)}
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) Run(run func(id string)) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) Return(s string) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) RunAndReturn(run func(id string) string) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateChain provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetCertificateChain(id string) [][]byte {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateChain")
	}

	var r0 [][]byte
	if returnFunc, ok := ret.Get(0).(func(string) [][]byte); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	return r0
}

// PKIServiceInterfaceMock_GetCertificateChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateChain'
type PKIServiceInterfaceMock_GetCertificateChain_Call struct {
	*mock.Call
}

// GetCertificateChain is a helper method to define mock.On call
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetCertificateChain(id interface{}) *PKIServiceInterfaceMock_GetCertificateChain_Call {
	return &PKIServiceInterfaceMock_GetCertificateChain_Call{Call: _e.mock.On("GetCertificateChain", id)}
}

func (_c *PKIServiceInterfaceMock_GetCertificateChain_Call) Run(run func(id string)) *PKIServiceInterfaceMock_GetCertificateChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertificateChain_Call) Return(bytess [][]byte) *PKIServiceInterfaceMock_GetCertificateChain_Call {
	_c.Call.Return(bytess)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertificateChain_Call) RunAndReturn(run func(id string) [][]byte) *PKIServiceInterfaceMock_GetCertificateChain_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKey provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetPrivateKey(ctx context.Context, id string) (crypto.PrivateKey, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 crypto.PrivateKey
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (crypto.PrivateKey, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) crypto.PrivateKey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type PKIServiceInterfaceMock_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetPrivateKey(ctx interface{}, id interface{}) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	return &PKIServiceInterfaceMock_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey", ctx, id)}
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) Run(run func(ctx context.Context, id string)) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) Return(privateKey crypto.PrivateKey, serviceError *serviceerror.ServiceError) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Return(privateKey, serviceError)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) RunAndReturn(run func(ctx context.Context, id string) (crypto.PrivateKey, *serviceerror.ServiceError)) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupportedSigningAlgorithms provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetSupportedSigningAlgorithms() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedSigningAlgorithms")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedSigningAlgorithms'
type PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call struct {
	*mock.Call
}

// GetSupportedSigningAlgorithms is a helper method to define mock.On call
func (_e *PKIServiceInterfaceMock_Expecter) GetSupportedSigningAlgorithms() *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call {
	return &PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call{Call: _e.mock.On("GetSupportedSigningAlgorithms")}
}

func (_c *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call) Run(run func()) *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call) Return(strings []string) *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call) RunAndReturn(run func() []string) *PKIServiceInterfaceMock_GetSupportedSigningAlgorithms_Call {
	_c.Call.Return(run)
	return _c
}

// GetTLSConfig provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetTLSConfig() (*tls.Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTLSConfig")
	}

	var r0 *tls.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*tls.Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *tls.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetTLSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTLSConfig'
type PKIServiceInterfaceMock_GetTLSConfig_Call struct {
	*mock.Call
}

// GetTLSConfig is a helper method to define mock.On call
func (_e *PKIServiceInterfaceMock_Expecter) GetTLSConfig() *PKIServiceInterfaceMock_GetTLSConfig_Call {
	return &PKIServiceInterfaceMock_GetTLSConfig_Call{Call: _e.mock.On("GetTLSConfig")}
}

func (_c *PKIServiceInterfaceMock_GetTLSConfig_Call) Run(run func()) *PKIServiceInterfaceMock_GetTLSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetTLSConfig_Call) Return(config *tls.Config, err error) *PKIServiceInterfaceMock_GetTLSConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetTLSConfig_Call) RunAndReturn(run func() (*tls.Config, error)) *PKIServiceInterfaceMock_GetTLSConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetX509Certificate provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetX509Certificate(ctx context.Context, id string) (*x509.Certificate, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetX509Certificate")
	}

	var r0 *x509.Certificate
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*x509.Certificate, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *x509.Certificate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetX509Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetX509Certificate'
type PKIServiceInterfaceMock_GetX509Certificate_Call struct {
	*mock.Call
}

// GetX509Certificate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetX509Certificate(ctx interface{}, id interface{}) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	return &PKIServiceInterfaceMock_GetX509Certificate_Call{Call: _e.mock.On("GetX509Certificate", ctx, id)}
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) Run(run func(ctx context.Context, id string)) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) Return(certificate *x509.Certificate, serviceError *serviceerror.ServiceError) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Return(certificate, serviceError)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) RunAndReturn(run func(ctx context.Context, id string) (*x509.Certificate, *serviceerror.ServiceError)) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Return(run)
	return _c
}
