// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package serverconfig

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newServerConfigStoreInterfaceMock creates a new instance of serverConfigStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newServerConfigStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *serverConfigStoreInterfaceMock {
	mock := &serverConfigStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// serverConfigStoreInterfaceMock is an autogenerated mock type for the serverConfigStoreInterface type
type serverConfigStoreInterfaceMock struct {
	mock.Mock
}

type serverConfigStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *serverConfigStoreInterfaceMock) EXPECT() *serverConfigStoreInterfaceMock_Expecter {
	return &serverConfigStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetServerConfig provides a mock function for the type serverConfigStoreInterfaceMock
func (_mock *serverConfigStoreInterfaceMock) GetServerConfig(ctx context.Context, name ConfigName) (storeLayers, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServerConfig")
	}

	var r0 storeLayers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConfigName) (storeLayers, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConfigName) storeLayers); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(storeLayers)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ConfigName) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// serverConfigStoreInterfaceMock_GetServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerConfig'
type serverConfigStoreInterfaceMock_GetServerConfig_Call struct {
	*mock.Call
}

// GetServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - name ConfigName
func (_e *serverConfigStoreInterfaceMock_Expecter) GetServerConfig(ctx interface{}, name interface{}) *serverConfigStoreInterfaceMock_GetServerConfig_Call {
	return &serverConfigStoreInterfaceMock_GetServerConfig_Call{Call: _e.mock.On("GetServerConfig", ctx, name)}
}

func (_c *serverConfigStoreInterfaceMock_GetServerConfig_Call) Run(run func(ctx context.Context, name ConfigName)) *serverConfigStoreInterfaceMock_GetServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ConfigName
		if args[1] != nil {
			arg1 = args[1].(ConfigName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *serverConfigStoreInterfaceMock_GetServerConfig_Call) Return(storeLayersMoqParam storeLayers, err error) *serverConfigStoreInterfaceMock_GetServerConfig_Call {
	_c.Call.Return(storeLayersMoqParam, err)
	return _c
}

func (_c *serverConfigStoreInterfaceMock_GetServerConfig_Call) RunAndReturn(run func(ctx context.Context, name ConfigName) (storeLayers, error)) *serverConfigStoreInterfaceMock_GetServerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertServerConfig provides a mock function for the type serverConfigStoreInterfaceMock
func (_mock *serverConfigStoreInterfaceMock) UpsertServerConfig(ctx context.Context, cfg ServerConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertServerConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ServerConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// serverConfigStoreInterfaceMock_UpsertServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertServerConfig'
type serverConfigStoreInterfaceMock_UpsertServerConfig_Call struct {
	*mock.Call
}

// UpsertServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg ServerConfig
func (_e *serverConfigStoreInterfaceMock_Expecter) UpsertServerConfig(ctx interface{}, cfg interface{}) *serverConfigStoreInterfaceMock_UpsertServerConfig_Call {
	return &serverConfigStoreInterfaceMock_UpsertServerConfig_Call{Call: _e.mock.On("UpsertServerConfig", ctx, cfg)}
}

func (_c *serverConfigStoreInterfaceMock_UpsertServerConfig_Call) Run(run func(ctx context.Context, cfg ServerConfig)) *serverConfigStoreInterfaceMock_UpsertServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ServerConfig
		if args[1] != nil {
			arg1 = args[1].(ServerConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *serverConfigStoreInterfaceMock_UpsertServerConfig_Call) Return(err error) *serverConfigStoreInterfaceMock_UpsertServerConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *serverConfigStoreInterfaceMock_UpsertServerConfig_Call) RunAndReturn(run func(ctx context.Context, cfg ServerConfig) error) *serverConfigStoreInterfaceMock_UpsertServerConfig_Call {
	_c.Call.Return(run)
	return _c
}
