version: "3.9"

services:
  postgres:
    image: postgres
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../backend/dbscripts/runtime-transient/postgres.sql:/docker-entrypoint-initdb.d/runtime-transient-postgres.sql
      - ../../backend/dbscripts/configdb/postgres.sql:/docker-entrypoint-initdb.d/config-postgres.sql
      - ../../backend/dbscripts/entitydb/postgres.sql:/docker-entrypoint-initdb.d/entity-postgres.sql
      - ../../backend/dbscripts/runtime-persistent/postgres.sql:/docker-entrypoint-initdb.d/runtime-persistent-postgres.sql

volumes:
  postgres_data:
