/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type {LibraryAttribute} from '../types/user-types';

/**
 * The predefined library of attributes offered when building a user type schema.
 * This is a static, front-end-only convenience list; picking one seeds a schema
 * property with these values (a fresh row `id` is assigned on add). Entries are
 * listed in the order below. Edit this file to change the suggested attributes.
 */
const ATTRIBUTES: LibraryAttribute[] = [
  {
    name: 'username',
    displayName: 'Username',
    type: 'string',
    required: true,
    unique: true,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'email',
    displayName: 'Email',
    type: 'string',
    required: true,
    unique: true,
    credential: false,
    enum: [],
    regex: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$',
  },
  {
    name: 'given_name',
    displayName: 'First Name',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'family_name',
    displayName: 'Last Name',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'phone',
    displayName: 'Phone Number',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'password',
    displayName: 'Password',
    type: 'string',
    required: false,
    unique: false,
    credential: true,
    enum: [],
    regex: '',
  },
  {
    name: 'display_name',
    displayName: 'Display Name',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'name',
    displayName: 'Full Name',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'middle_name',
    displayName: 'Middle Name',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'nickname',
    displayName: 'Nickname',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'picture',
    displayName: 'Picture',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'birthdate',
    displayName: 'Birthdate',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'gender',
    displayName: 'Gender',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'locale',
    displayName: 'Locale',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'zoneinfo',
    displayName: 'Time Zone',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'preferred_language',
    displayName: 'Preferred Language',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'profile',
    displayName: 'Profile URL',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'website',
    displayName: 'Website',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'title',
    displayName: 'Title',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'email_verified',
    displayName: 'Email Verified',
    type: 'boolean',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'phone_verified',
    displayName: 'Phone Verified',
    type: 'boolean',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'active',
    displayName: 'Active',
    type: 'boolean',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'street_address',
    displayName: 'Street Address',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'locality',
    displayName: 'City',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'region',
    displayName: 'State/Region',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'postal_code',
    displayName: 'Postal Code',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'country',
    displayName: 'Country',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'employee_number',
    displayName: 'Employee Number',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'department',
    displayName: 'Department',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'division',
    displayName: 'Division',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'organization',
    displayName: 'Organization',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'cost_center',
    displayName: 'Cost Center',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
  {
    name: 'manager',
    displayName: 'Manager',
    type: 'string',
    required: false,
    unique: false,
    credential: false,
    enum: [],
    regex: '',
  },
];

export default ATTRIBUTES;
