// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgt

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/ou"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// newOuProviderMock creates a new instance of ouProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOuProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ouProviderMock {
	mock := &ouProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ouProviderMock is an autogenerated mock type for the ouProvider type
type ouProviderMock struct {
	mock.Mock
}

type ouProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ouProviderMock) EXPECT() *ouProviderMock_Expecter {
	return &ouProviderMock_Expecter{mock: &_m.Mock}
}

// GetOrganizationUnit provides a mock function for the type ouProviderMock
func (_mock *ouProviderMock) GetOrganizationUnit(ctx context.Context, id string) (ou.OrganizationUnit, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnit")
	}

	var r0 ou.OrganizationUnit
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ou.OrganizationUnit, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ou.OrganizationUnit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ou.OrganizationUnit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ouProviderMock_GetOrganizationUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnit'
type ouProviderMock_GetOrganizationUnit_Call struct {
	*mock.Call
}

// GetOrganizationUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ouProviderMock_Expecter) GetOrganizationUnit(ctx interface{}, id interface{}) *ouProviderMock_GetOrganizationUnit_Call {
	return &ouProviderMock_GetOrganizationUnit_Call{Call: _e.mock.On("GetOrganizationUnit", ctx, id)}
}

func (_c *ouProviderMock_GetOrganizationUnit_Call) Run(run func(ctx context.Context, id string)) *ouProviderMock_GetOrganizationUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ouProviderMock_GetOrganizationUnit_Call) Return(organizationUnit ou.OrganizationUnit, serviceError *common.ServiceError) *ouProviderMock_GetOrganizationUnit_Call {
	_c.Call.Return(organizationUnit, serviceError)
	return _c
}

func (_c *ouProviderMock_GetOrganizationUnit_Call) RunAndReturn(run func(ctx context.Context, id string) (ou.OrganizationUnit, *common.ServiceError)) *ouProviderMock_GetOrganizationUnit_Call {
	_c.Call.Return(run)
	return _c
}
