# ------------------------------------------------------------------------------
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
# ------------------------------------------------------------------------------

# Mockery configuration file for generating public mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/thunder-id/thunderid/internal/system/database/provider:
    config:
      all: true
      dir: tests/mocks/database/providermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: providermock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/system/database/model:
    config:
      all: true
      dir: tests/mocks/database/modelmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: modelmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/healthcheck/service:
    config:
      all: true
      dir: tests/mocks/healthcheck/servicemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: servicemock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/system/healthcheck/provider:
    config:
      all: true
      dir: tests/mocks/healthcheck/providermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: providermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/cache:
    config:
      all: true
      dir: tests/mocks/cachemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: cachemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/cert:
    config:
      all: true
      dir: tests/mocks/certmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: certmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/jose/jwt:
    config:
      all: true
      dir: tests/mocks/jose/jwtmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: jwtmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/jose/jwe:
    config:
      all: true
      dir: tests/mocks/jose/jwemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: jwemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/scope:
    config:
      all: true
      dir: tests/mocks/oauth/scopemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: scopemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/authz:
    interfaces:
      AuthorizeHandlerInterface:
        config:
          dir: tests/mocks/oauth/oauth2/authzmock
          structname: '{{.InterfaceName}}Mock'
          pkgname: authzmock
          filename: "{{.InterfaceName}}_mock.go"
      AuthorizeServiceInterface:
        config:
          dir: tests/mocks/oauth/oauth2/authzmock
          structname: '{{.InterfaceName}}Mock'
          pkgname: authzmock
          filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/granthandlers:
    config:
      all: true
      dir: tests/mocks/oauth/oauth2/granthandlersmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: granthandlersmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/token:
    config:
      all: true
      dir: tests/mocks/oauth/oauth2/tokenmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: tokenmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/tokenservice:
    config:
      all: true
      dir: tests/mocks/oauth/oauth2/tokenservicemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: tokenservicemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/introspect:
    config:
      all: true
      dir: tests/mocks/oauth/oauth2/introspectmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: introspectmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/oauth/oauth2/discovery:
    config:
      all: true
      dir: tests/mocks/oauth/oauth2/discoverymock
      structname: '{{.InterfaceName}}Mock'
      pkgname: discoverymock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/entity:
    config:
      dir: tests/mocks/entitymock
      structname: '{{.InterfaceName}}Mock'
      pkgname: entitymock
      filename: "{{.InterfaceName}}_mock.go"
    interfaces:
      EntityServiceInterface:

  github.com/thunder-id/thunderid/internal/user:
    config:
      all: true
      dir: tests/mocks/usermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: usermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn:
    config:
      all: true
      dir: tests/mocks/authn/authnmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: authnmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/assert:
    config:
      all: true
      dir: tests/mocks/authn/assertmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: assertmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/otp:
    config:
      all: true
      dir: tests/mocks/authn/otpmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: otpmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/oauth:
    config:
      all: true
      dir: tests/mocks/authn/oauthmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: oauthmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/oidc:
    config:
      all: true
      dir: tests/mocks/authn/oidcmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: oidcmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/google:
    config:
      all: true
      dir: tests/mocks/authn/googlemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: googlemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/github:
    config:
      all: true
      dir: tests/mocks/authn/githubmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: githubmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/magiclink:
    config:
      all: true
      dir: tests/mocks/authn/magiclinkmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: magiclinkmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authn/passkey:
    interfaces:
      PasskeyServiceInterface:
        config:
          dir: tests/mocks/authn/passkeymock
          structname: 'WebAuthnAuthnServiceInterfaceMock'
          pkgname: passkeymock
          filename: "WebAuthnAuthnServiceInterface_mock.go"

  github.com/thunder-id/thunderid/internal/authn/consent:
    interfaces:
      ConsentEnforcerServiceInterface:
        config:
          dir: tests/mocks/authn/consentenforcermock
          structname: '{{.InterfaceName}}Mock'
          pkgname: consentenforcermock
          filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/idp:
    config:
      all: true
      dir: tests/mocks/idp/idpmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: idpmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/notification:
    config:
      all: true
      dir: tests/mocks/notification/notificationmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: notificationmock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/notification/message:
    config:
      all: true
      dir: tests/mocks/notification/messagemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: messagemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/http:
    config:
      all: true
      dir: tests/mocks/httpmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: httpmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/application:
    config:
      dir: tests/mocks/applicationmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: applicationmock
      filename: "{{.InterfaceName}}_mock.go"
    interfaces:
      ApplicationServiceInterface:

  github.com/thunder-id/thunderid/internal/inboundclient:
    config:
      dir: tests/mocks/inboundclientmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: inboundclientmock
      filename: "{{.InterfaceName}}_mock.go"
    interfaces:
      InboundClientServiceInterface:
  
  github.com/thunder-id/thunderid/internal/ou:
    config:
      all: true
      dir: tests/mocks/oumock
      structname: '{{.InterfaceName}}Mock'
      pkgname: oumock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/flow/core:
    config:
      all: true
      dir: tests/mocks/flow/coremock
      structname: '{{.InterfaceName}}Mock'
      pkgname: coremock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/flow/flowexec:
    config:
      all: true
      dir: tests/mocks/flow/flowexecmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: flowexecmock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/flow/mgt:
    config:
      all: true
      dir: tests/mocks/flow/flowmgtmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: flowmgtmock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/flow/executor:
    config:
      all: true
      dir: tests/mocks/flow/executormock
      structname: '{{.InterfaceName}}Mock'
      pkgname: executormock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/entitytype:
    config:
      all: true
      dir: tests/mocks/entitytypemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: entitytypemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/group:
    config:
      all: true
      dir: tests/mocks/groupmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: groupmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authz:
    config:
      all: true
      dir: tests/mocks/authzmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: authzmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authz/engine:
    config:
      all: true
      dir: tests/mocks/authz/engine
      structname: '{{.InterfaceName}}Mock'
      pkgname: enginemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/role:
    config:
      all: true
      dir: tests/mocks/rolemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: rolemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/observability:
    config:
      all: true
      dir: tests/mocks/observability/observabilitymock
      structname: '{{.InterfaceName}}Mock'
      pkgname: observabilitymock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/observability/adapter:
    config:
      all: true
      dir: tests/mocks/observability/adaptermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: adaptermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/design/theme/mgt:
    config:
      all: true
      dir: tests/mocks/design/thememock
      structname: '{{.InterfaceName}}Mock'
      pkgname: thememock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/design/layout/mgt:
    config:
      all: true
      dir: tests/mocks/design/layoutmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: layoutmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/design/resolve:
    config:
      all: true
      dir: tests/mocks/design/resolvemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: resolvemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/i18n/mgt:
    config:
      all: true
      dir: tests/mocks/i18n/mgtmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: mgtmock
      filename: "{{.InterfaceName}}_mock.go"
  
  github.com/thunder-id/thunderid/internal/system/cryptolab/hash:
    config:
      all: true
      dir: tests/mocks/crypto/hashmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: hashmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/kmprovider/defaultkm/pkiservice:
    config:
      all: true
      dir: tests/mocks/crypto/pki/pkimock
      structname: '{{.InterfaceName}}Mock'
      pkgname: pkimock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/kmprovider:
    config:
      all: true
      dir: tests/mocks/crypto/cryptomock
      structname: '{{.InterfaceName}}Mock'
      pkgname: cryptomock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/resource:
    config:
      all: true
      dir: tests/mocks/resourcemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: resourcemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/entityprovider:
    config:
      all: true
      dir: tests/mocks/entityprovidermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: entityprovidermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authnprovider/provider:
    config:
      all: true
      dir: tests/mocks/authnprovider/providermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: providermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/authnprovider/manager:
    config:
      all: true
      dir: tests/mocks/authnprovider/managermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: managermock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/sysauthz:
    interfaces:
      SystemAuthorizationServiceInterface:
        config:
          dir: tests/mocks/sysauthzmock
          structname: '{{.InterfaceName}}Mock'
          pkgname: sysauthzmock
          filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/consent:
    interfaces:
      ConsentServiceInterface:
        config:
          dir: tests/mocks/consentmock
          structname: '{{.InterfaceName}}Mock'
          pkgname: consentmock
          filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/attributecache:
    config:
      all: true
      dir: tests/mocks/attributecachemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: attributecachemock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/email:
    config:
      all: true
      dir: tests/mocks/emailmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: emailmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/thunder-id/thunderid/internal/system/template:
    config:
      all: true
      dir: tests/mocks/templatemock
      structname: '{{.InterfaceName}}Mock'
      pkgname: templatemock
      filename: "{{.InterfaceName}}_mock.go"
