// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package passkey

import (
	mock "github.com/stretchr/testify/mock"
)

// newWebAuthnServiceMock creates a new instance of webAuthnServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newWebAuthnServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *webAuthnServiceMock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &webAuthnServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// webAuthnServiceMock is an autogenerated mock type for the webAuthnService type
type webAuthnServiceMock struct {
	mock.Mock
}

type webAuthnServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *webAuthnServiceMock) EXPECT() *webAuthnServiceMock_Expecter {
	return &webAuthnServiceMock_Expecter{mock: &_m.Mock}
}

// BeginDiscoverableLogin provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) BeginDiscoverableLogin() (*credentialAssertion, *sessionData, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginDiscoverableLogin")
	}

	var r0 *credentialAssertion
	var r1 *sessionData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (*credentialAssertion, *sessionData, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *credentialAssertion); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialAssertion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *sessionData); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sessionData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// webAuthnServiceMock_BeginDiscoverableLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginDiscoverableLogin'
type webAuthnServiceMock_BeginDiscoverableLogin_Call struct {
	*mock.Call
}

// BeginDiscoverableLogin is a helper method to define mock.On call
func (_e *webAuthnServiceMock_Expecter) BeginDiscoverableLogin() *webAuthnServiceMock_BeginDiscoverableLogin_Call {
	return &webAuthnServiceMock_BeginDiscoverableLogin_Call{Call: _e.mock.On("BeginDiscoverableLogin")}
}

func (_c *webAuthnServiceMock_BeginDiscoverableLogin_Call) Run(run func()) *webAuthnServiceMock_BeginDiscoverableLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *webAuthnServiceMock_BeginDiscoverableLogin_Call) Return(credentialAssertionMoqParam *credentialAssertion, sessionDataMoqParam *sessionData, err error) *webAuthnServiceMock_BeginDiscoverableLogin_Call {
	_c.Call.Return(credentialAssertionMoqParam, sessionDataMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_BeginDiscoverableLogin_Call) RunAndReturn(run func() (*credentialAssertion, *sessionData, error)) *webAuthnServiceMock_BeginDiscoverableLogin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginLogin provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) BeginLogin(user webauthnUserInterface) (*credentialAssertion, *sessionData, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for BeginLogin")
	}

	var r0 *credentialAssertion
	var r1 *sessionData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface) (*credentialAssertion, *sessionData, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface) *credentialAssertion); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialAssertion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(webauthnUserInterface) *sessionData); ok {
		r1 = returnFunc(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sessionData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(webauthnUserInterface) error); ok {
		r2 = returnFunc(user)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// webAuthnServiceMock_BeginLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginLogin'
type webAuthnServiceMock_BeginLogin_Call struct {
	*mock.Call
}

// BeginLogin is a helper method to define mock.On call
//   - user webauthnUserInterface
func (_e *webAuthnServiceMock_Expecter) BeginLogin(user any) *webAuthnServiceMock_BeginLogin_Call {
	return &webAuthnServiceMock_BeginLogin_Call{Call: _e.mock.On("BeginLogin", user)}
}

func (_c *webAuthnServiceMock_BeginLogin_Call) Run(run func(user webauthnUserInterface)) *webAuthnServiceMock_BeginLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 webauthnUserInterface
		if args[0] != nil {
			arg0 = args[0].(webauthnUserInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *webAuthnServiceMock_BeginLogin_Call) Return(credentialAssertionMoqParam *credentialAssertion, sessionDataMoqParam *sessionData, err error) *webAuthnServiceMock_BeginLogin_Call {
	_c.Call.Return(credentialAssertionMoqParam, sessionDataMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_BeginLogin_Call) RunAndReturn(run func(user webauthnUserInterface) (*credentialAssertion, *sessionData, error)) *webAuthnServiceMock_BeginLogin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginRegistration provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) BeginRegistration(user webauthnUserInterface, options []registrationOption) (*credentialCreation, *sessionData, error) {
	ret := _mock.Called(user, options)

	if len(ret) == 0 {
		panic("no return value specified for BeginRegistration")
	}

	var r0 *credentialCreation
	var r1 *sessionData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, []registrationOption) (*credentialCreation, *sessionData, error)); ok {
		return returnFunc(user, options)
	}
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, []registrationOption) *credentialCreation); ok {
		r0 = returnFunc(user, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialCreation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(webauthnUserInterface, []registrationOption) *sessionData); ok {
		r1 = returnFunc(user, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sessionData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(webauthnUserInterface, []registrationOption) error); ok {
		r2 = returnFunc(user, options)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// webAuthnServiceMock_BeginRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginRegistration'
type webAuthnServiceMock_BeginRegistration_Call struct {
	*mock.Call
}

// BeginRegistration is a helper method to define mock.On call
//   - user webauthnUserInterface
//   - options []registrationOption
func (_e *webAuthnServiceMock_Expecter) BeginRegistration(user any, options any) *webAuthnServiceMock_BeginRegistration_Call {
	return &webAuthnServiceMock_BeginRegistration_Call{Call: _e.mock.On("BeginRegistration", user, options)}
}

func (_c *webAuthnServiceMock_BeginRegistration_Call) Run(run func(user webauthnUserInterface, options []registrationOption)) *webAuthnServiceMock_BeginRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 webauthnUserInterface
		if args[0] != nil {
			arg0 = args[0].(webauthnUserInterface)
		}
		var arg1 []registrationOption
		if args[1] != nil {
			arg1 = args[1].([]registrationOption)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *webAuthnServiceMock_BeginRegistration_Call) Return(credentialCreationMoqParam *credentialCreation, sessionDataMoqParam *sessionData, err error) *webAuthnServiceMock_BeginRegistration_Call {
	_c.Call.Return(credentialCreationMoqParam, sessionDataMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_BeginRegistration_Call) RunAndReturn(run func(user webauthnUserInterface, options []registrationOption) (*credentialCreation, *sessionData, error)) *webAuthnServiceMock_BeginRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCredential provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) CreateCredential(user webauthnUserInterface, session sessionData, response *parsedCredentialCreationData) (*webauthnCredential, error) {
	ret := _mock.Called(user, session, response)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 *webauthnCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, sessionData, *parsedCredentialCreationData) (*webauthnCredential, error)); ok {
		return returnFunc(user, session, response)
	}
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, sessionData, *parsedCredentialCreationData) *webauthnCredential); ok {
		r0 = returnFunc(user, session, response)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthnCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(webauthnUserInterface, sessionData, *parsedCredentialCreationData) error); ok {
		r1 = returnFunc(user, session, response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// webAuthnServiceMock_CreateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredential'
type webAuthnServiceMock_CreateCredential_Call struct {
	*mock.Call
}

// CreateCredential is a helper method to define mock.On call
//   - user webauthnUserInterface
//   - session sessionData
//   - response *parsedCredentialCreationData
func (_e *webAuthnServiceMock_Expecter) CreateCredential(user any, session any, response any) *webAuthnServiceMock_CreateCredential_Call {
	return &webAuthnServiceMock_CreateCredential_Call{Call: _e.mock.On("CreateCredential", user, session, response)}
}

func (_c *webAuthnServiceMock_CreateCredential_Call) Run(run func(user webauthnUserInterface, session sessionData, response *parsedCredentialCreationData)) *webAuthnServiceMock_CreateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 webauthnUserInterface
		if args[0] != nil {
			arg0 = args[0].(webauthnUserInterface)
		}
		var arg1 sessionData
		if args[1] != nil {
			arg1 = args[1].(sessionData)
		}
		var arg2 *parsedCredentialCreationData
		if args[2] != nil {
			arg2 = args[2].(*parsedCredentialCreationData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *webAuthnServiceMock_CreateCredential_Call) Return(webauthnCredentialMoqParam *webauthnCredential, err error) *webAuthnServiceMock_CreateCredential_Call {
	_c.Call.Return(webauthnCredentialMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_CreateCredential_Call) RunAndReturn(run func(user webauthnUserInterface, session sessionData, response *parsedCredentialCreationData) (*webauthnCredential, error)) *webAuthnServiceMock_CreateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLogin provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) ValidateLogin(user webauthnUserInterface, session sessionData, response *parsedCredentialAssertionData) (*webauthnCredential, error) {
	ret := _mock.Called(user, session, response)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogin")
	}

	var r0 *webauthnCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, sessionData, *parsedCredentialAssertionData) (*webauthnCredential, error)); ok {
		return returnFunc(user, session, response)
	}
	if returnFunc, ok := ret.Get(0).(func(webauthnUserInterface, sessionData, *parsedCredentialAssertionData) *webauthnCredential); ok {
		r0 = returnFunc(user, session, response)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthnCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(webauthnUserInterface, sessionData, *parsedCredentialAssertionData) error); ok {
		r1 = returnFunc(user, session, response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// webAuthnServiceMock_ValidateLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLogin'
type webAuthnServiceMock_ValidateLogin_Call struct {
	*mock.Call
}

// ValidateLogin is a helper method to define mock.On call
//   - user webauthnUserInterface
//   - session sessionData
//   - response *parsedCredentialAssertionData
func (_e *webAuthnServiceMock_Expecter) ValidateLogin(user any, session any, response any) *webAuthnServiceMock_ValidateLogin_Call {
	return &webAuthnServiceMock_ValidateLogin_Call{Call: _e.mock.On("ValidateLogin", user, session, response)}
}

func (_c *webAuthnServiceMock_ValidateLogin_Call) Run(run func(user webauthnUserInterface, session sessionData, response *parsedCredentialAssertionData)) *webAuthnServiceMock_ValidateLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 webauthnUserInterface
		if args[0] != nil {
			arg0 = args[0].(webauthnUserInterface)
		}
		var arg1 sessionData
		if args[1] != nil {
			arg1 = args[1].(sessionData)
		}
		var arg2 *parsedCredentialAssertionData
		if args[2] != nil {
			arg2 = args[2].(*parsedCredentialAssertionData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *webAuthnServiceMock_ValidateLogin_Call) Return(webauthnCredentialMoqParam *webauthnCredential, err error) *webAuthnServiceMock_ValidateLogin_Call {
	_c.Call.Return(webauthnCredentialMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_ValidateLogin_Call) RunAndReturn(run func(user webauthnUserInterface, session sessionData, response *parsedCredentialAssertionData) (*webauthnCredential, error)) *webAuthnServiceMock_ValidateLogin_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePasskeyLogin provides a mock function for the type webAuthnServiceMock
func (_mock *webAuthnServiceMock) ValidatePasskeyLogin(userHandler func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), session sessionData, response *parsedCredentialAssertionData) (webauthnUserInterface, *webauthnCredential, error) {
	ret := _mock.Called(userHandler, session, response)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePasskeyLogin")
	}

	var r0 webauthnUserInterface
	var r1 *webauthnCredential
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), sessionData, *parsedCredentialAssertionData) (webauthnUserInterface, *webauthnCredential, error)); ok {
		return returnFunc(userHandler, session, response)
	}
	if returnFunc, ok := ret.Get(0).(func(func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), sessionData, *parsedCredentialAssertionData) webauthnUserInterface); ok {
		r0 = returnFunc(userHandler, session, response)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(webauthnUserInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), sessionData, *parsedCredentialAssertionData) *webauthnCredential); ok {
		r1 = returnFunc(userHandler, session, response)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*webauthnCredential)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), sessionData, *parsedCredentialAssertionData) error); ok {
		r2 = returnFunc(userHandler, session, response)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// webAuthnServiceMock_ValidatePasskeyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePasskeyLogin'
type webAuthnServiceMock_ValidatePasskeyLogin_Call struct {
	*mock.Call
}

// ValidatePasskeyLogin is a helper method to define mock.On call
//   - userHandler func(rawID []byte, userHandle []byte) (webauthnUserInterface, error)
//   - session sessionData
//   - response *parsedCredentialAssertionData
func (_e *webAuthnServiceMock_Expecter) ValidatePasskeyLogin(userHandler any, session any, response any) *webAuthnServiceMock_ValidatePasskeyLogin_Call {
	return &webAuthnServiceMock_ValidatePasskeyLogin_Call{Call: _e.mock.On("ValidatePasskeyLogin", userHandler, session, response)}
}

func (_c *webAuthnServiceMock_ValidatePasskeyLogin_Call) Run(run func(userHandler func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), session sessionData, response *parsedCredentialAssertionData)) *webAuthnServiceMock_ValidatePasskeyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(rawID []byte, userHandle []byte) (webauthnUserInterface, error)
		if args[0] != nil {
			arg0 = args[0].(func(rawID []byte, userHandle []byte) (webauthnUserInterface, error))
		}
		var arg1 sessionData
		if args[1] != nil {
			arg1 = args[1].(sessionData)
		}
		var arg2 *parsedCredentialAssertionData
		if args[2] != nil {
			arg2 = args[2].(*parsedCredentialAssertionData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *webAuthnServiceMock_ValidatePasskeyLogin_Call) Return(webauthnUserInterfaceMoqParam webauthnUserInterface, webauthnCredentialMoqParam *webauthnCredential, err error) *webAuthnServiceMock_ValidatePasskeyLogin_Call {
	_c.Call.Return(webauthnUserInterfaceMoqParam, webauthnCredentialMoqParam, err)
	return _c
}

func (_c *webAuthnServiceMock_ValidatePasskeyLogin_Call) RunAndReturn(run func(userHandler func(rawID []byte, userHandle []byte) (webauthnUserInterface, error), session sessionData, response *parsedCredentialAssertionData) (webauthnUserInterface, *webauthnCredential, error)) *webAuthnServiceMock_ValidatePasskeyLogin_Call {
	_c.Call.Return(run)
	return _c
}
