// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgt_legacymock

import (
	"github.com/thunder-id/thunderid/internal/flow/core"
	mock "github.com/stretchr/testify/mock"
)

// NewLegacyFlowMgtServiceInterfaceMock creates a new instance of LegacyFlowMgtServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLegacyFlowMgtServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LegacyFlowMgtServiceInterfaceMock {
	mock := &LegacyFlowMgtServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LegacyFlowMgtServiceInterfaceMock is an autogenerated mock type for the LegacyFlowMgtServiceInterface type
type LegacyFlowMgtServiceInterfaceMock struct {
	mock.Mock
}

type LegacyFlowMgtServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LegacyFlowMgtServiceInterfaceMock) EXPECT() *LegacyFlowMgtServiceInterfaceMock_Expecter {
	return &LegacyFlowMgtServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetGraph provides a mock function for the type LegacyFlowMgtServiceInterfaceMock
func (_mock *LegacyFlowMgtServiceInterfaceMock) GetGraph(graphID string) (core.GraphInterface, bool) {
	ret := _mock.Called(graphID)

	if len(ret) == 0 {
		panic("no return value specified for GetGraph")
	}

	var r0 core.GraphInterface
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (core.GraphInterface, bool)); ok {
		return returnFunc(graphID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) core.GraphInterface); ok {
		r0 = returnFunc(graphID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GraphInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(graphID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// LegacyFlowMgtServiceInterfaceMock_GetGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraph'
type LegacyFlowMgtServiceInterfaceMock_GetGraph_Call struct {
	*mock.Call
}

// GetGraph is a helper method to define mock.On call
//   - graphID string
func (_e *LegacyFlowMgtServiceInterfaceMock_Expecter) GetGraph(graphID interface{}) *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call {
	return &LegacyFlowMgtServiceInterfaceMock_GetGraph_Call{Call: _e.mock.On("GetGraph", graphID)}
}

func (_c *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call) Run(run func(graphID string)) *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call) Return(graphInterface core.GraphInterface, b bool) *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Return(graphInterface, b)
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call) RunAndReturn(run func(graphID string) (core.GraphInterface, bool)) *LegacyFlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidGraphID provides a mock function for the type LegacyFlowMgtServiceInterfaceMock
func (_mock *LegacyFlowMgtServiceInterfaceMock) IsValidGraphID(graphID string) bool {
	ret := _mock.Called(graphID)

	if len(ret) == 0 {
		panic("no return value specified for IsValidGraphID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(graphID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidGraphID'
type LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call struct {
	*mock.Call
}

// IsValidGraphID is a helper method to define mock.On call
//   - graphID string
func (_e *LegacyFlowMgtServiceInterfaceMock_Expecter) IsValidGraphID(graphID interface{}) *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call {
	return &LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call{Call: _e.mock.On("IsValidGraphID", graphID)}
}

func (_c *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call) Run(run func(graphID string)) *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call) Return(b bool) *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call) RunAndReturn(run func(graphID string) bool) *LegacyFlowMgtServiceInterfaceMock_IsValidGraphID_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterGraph provides a mock function for the type LegacyFlowMgtServiceInterfaceMock
func (_mock *LegacyFlowMgtServiceInterfaceMock) RegisterGraph(graphID string, g core.GraphInterface) {
	_mock.Called(graphID, g)
	return
}

// LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGraph'
type LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call struct {
	*mock.Call
}

// RegisterGraph is a helper method to define mock.On call
//   - graphID string
//   - g core.GraphInterface
func (_e *LegacyFlowMgtServiceInterfaceMock_Expecter) RegisterGraph(graphID interface{}, g interface{}) *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call {
	return &LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call{Call: _e.mock.On("RegisterGraph", graphID, g)}
}

func (_c *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call) Run(run func(graphID string, g core.GraphInterface)) *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 core.GraphInterface
		if args[1] != nil {
			arg1 = args[1].(core.GraphInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call) Return() *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call {
	_c.Call.Return()
	return _c
}

func (_c *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call) RunAndReturn(run func(graphID string, g core.GraphInterface)) *LegacyFlowMgtServiceInterfaceMock_RegisterGraph_Call {
	_c.Run(run)
	return _c
}
