// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package executor

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/revocation"
	"github.com/thunder-id/thunderid/internal/role"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// newRoleAssignmentAdminProviderMock creates a new instance of roleAssignmentAdminProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRoleAssignmentAdminProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *roleAssignmentAdminProviderMock {
	mock := &roleAssignmentAdminProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// roleAssignmentAdminProviderMock is an autogenerated mock type for the roleAssignmentAdminProvider type
type roleAssignmentAdminProviderMock struct {
	mock.Mock
}

type roleAssignmentAdminProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *roleAssignmentAdminProviderMock) EXPECT() *roleAssignmentAdminProviderMock_Expecter {
	return &roleAssignmentAdminProviderMock_Expecter{mock: &_m.Mock}
}

// RemoveAssignments provides a mock function for the type roleAssignmentAdminProviderMock
func (_mock *roleAssignmentAdminProviderMock) RemoveAssignments(ctx context.Context, id string, assignments []role.RoleAssignment) *common.ServiceError {
	ret := _mock.Called(ctx, id, assignments)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []role.RoleAssignment) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// roleAssignmentAdminProviderMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type roleAssignmentAdminProviderMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assignments []role.RoleAssignment
func (_e *roleAssignmentAdminProviderMock_Expecter) RemoveAssignments(ctx interface{}, id interface{}, assignments interface{}) *roleAssignmentAdminProviderMock_RemoveAssignments_Call {
	return &roleAssignmentAdminProviderMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", ctx, id, assignments)}
}

func (_c *roleAssignmentAdminProviderMock_RemoveAssignments_Call) Run(run func(ctx context.Context, id string, assignments []role.RoleAssignment)) *roleAssignmentAdminProviderMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []role.RoleAssignment
		if args[2] != nil {
			arg2 = args[2].([]role.RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *roleAssignmentAdminProviderMock_RemoveAssignments_Call) Return(serviceError *common.ServiceError) *roleAssignmentAdminProviderMock_RemoveAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *roleAssignmentAdminProviderMock_RemoveAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, assignments []role.RoleAssignment) *common.ServiceError) *roleAssignmentAdminProviderMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRemoveAssignment provides a mock function for the type roleAssignmentAdminProviderMock
func (_mock *roleAssignmentAdminProviderMock) ValidateRemoveAssignment(ctx context.Context, id string, assigneeID string) (*revocation.AccessRevocationTarget, *common.ServiceError) {
	ret := _mock.Called(ctx, id, assigneeID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRemoveAssignment")
	}

	var r0 *revocation.AccessRevocationTarget
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*revocation.AccessRevocationTarget, *common.ServiceError)); ok {
		return returnFunc(ctx, id, assigneeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *revocation.AccessRevocationTarget); ok {
		r0 = returnFunc(ctx, id, assigneeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*revocation.AccessRevocationTarget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, assigneeID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRemoveAssignment'
type roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call struct {
	*mock.Call
}

// ValidateRemoveAssignment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assigneeID string
func (_e *roleAssignmentAdminProviderMock_Expecter) ValidateRemoveAssignment(ctx interface{}, id interface{}, assigneeID interface{}) *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call {
	return &roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call{Call: _e.mock.On("ValidateRemoveAssignment", ctx, id, assigneeID)}
}

func (_c *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call) Run(run func(ctx context.Context, id string, assigneeID string)) *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call) Return(accessRevocationTarget *revocation.AccessRevocationTarget, serviceError *common.ServiceError) *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call {
	_c.Call.Return(accessRevocationTarget, serviceError)
	return _c
}

func (_c *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call) RunAndReturn(run func(ctx context.Context, id string, assigneeID string) (*revocation.AccessRevocationTarget, *common.ServiceError)) *roleAssignmentAdminProviderMock_ValidateRemoveAssignment_Call {
	_c.Call.Return(run)
	return _c
}
