// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notificationtemplate

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newNotificationTemplateStoreInterfaceMock creates a new instance of notificationTemplateStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNotificationTemplateStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *notificationTemplateStoreInterfaceMock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &notificationTemplateStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// notificationTemplateStoreInterfaceMock is an autogenerated mock type for the notificationTemplateStoreInterface type
type notificationTemplateStoreInterfaceMock struct {
	mock.Mock
}

type notificationTemplateStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *notificationTemplateStoreInterfaceMock) EXPECT() *notificationTemplateStoreInterfaceMock_Expecter {
	return &notificationTemplateStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CountTemplates provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) CountTemplates(ctx context.Context, channel ChannelType) (int, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CountTemplates")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType) (int, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType) int); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChannelType) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notificationTemplateStoreInterfaceMock_CountTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTemplates'
type notificationTemplateStoreInterfaceMock_CountTemplates_Call struct {
	*mock.Call
}

// CountTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
func (_e *notificationTemplateStoreInterfaceMock_Expecter) CountTemplates(ctx any, channel any) *notificationTemplateStoreInterfaceMock_CountTemplates_Call {
	return &notificationTemplateStoreInterfaceMock_CountTemplates_Call{Call: _e.mock.On("CountTemplates", ctx, channel)}
}

func (_c *notificationTemplateStoreInterfaceMock_CountTemplates_Call) Run(run func(ctx context.Context, channel ChannelType)) *notificationTemplateStoreInterfaceMock_CountTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_CountTemplates_Call) Return(n int, err error) *notificationTemplateStoreInterfaceMock_CountTemplates_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_CountTemplates_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType) (int, error)) *notificationTemplateStoreInterfaceMock_CountTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) CreateTemplate(ctx context.Context, template templateDAO) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, templateDAO) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// notificationTemplateStoreInterfaceMock_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type notificationTemplateStoreInterfaceMock_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template templateDAO
func (_e *notificationTemplateStoreInterfaceMock_Expecter) CreateTemplate(ctx any, template any) *notificationTemplateStoreInterfaceMock_CreateTemplate_Call {
	return &notificationTemplateStoreInterfaceMock_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, template)}
}

func (_c *notificationTemplateStoreInterfaceMock_CreateTemplate_Call) Run(run func(ctx context.Context, template templateDAO)) *notificationTemplateStoreInterfaceMock_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 templateDAO
		if args[1] != nil {
			arg1 = args[1].(templateDAO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_CreateTemplate_Call) Return(err error) *notificationTemplateStoreInterfaceMock_CreateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_CreateTemplate_Call) RunAndReturn(run func(ctx context.Context, template templateDAO) error) *notificationTemplateStoreInterfaceMock_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) DeleteTemplate(ctx context.Context, channel ChannelType, id string) error {
	ret := _mock.Called(ctx, channel, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) error); ok {
		r0 = returnFunc(ctx, channel, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// notificationTemplateStoreInterfaceMock_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type notificationTemplateStoreInterfaceMock_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
//   - id string
func (_e *notificationTemplateStoreInterfaceMock_Expecter) DeleteTemplate(ctx any, channel any, id any) *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call {
	return &notificationTemplateStoreInterfaceMock_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, channel, id)}
}

func (_c *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call) Run(run func(ctx context.Context, channel ChannelType, id string)) *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call) Return(err error) *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType, id string) error) *notificationTemplateStoreInterfaceMock_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) GetTemplate(ctx context.Context, channel ChannelType, id string) (templateDAO, error) {
	ret := _mock.Called(ctx, channel, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 templateDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) (templateDAO, error)); ok {
		return returnFunc(ctx, channel, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) templateDAO); ok {
		r0 = returnFunc(ctx, channel, id)
	} else {
		r0 = ret.Get(0).(templateDAO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChannelType, string) error); ok {
		r1 = returnFunc(ctx, channel, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notificationTemplateStoreInterfaceMock_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type notificationTemplateStoreInterfaceMock_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
//   - id string
func (_e *notificationTemplateStoreInterfaceMock_Expecter) GetTemplate(ctx any, channel any, id any) *notificationTemplateStoreInterfaceMock_GetTemplate_Call {
	return &notificationTemplateStoreInterfaceMock_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, channel, id)}
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplate_Call) Run(run func(ctx context.Context, channel ChannelType, id string)) *notificationTemplateStoreInterfaceMock_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplate_Call) Return(templateDAOMoqParam templateDAO, err error) *notificationTemplateStoreInterfaceMock_GetTemplate_Call {
	_c.Call.Return(templateDAOMoqParam, err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplate_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType, id string) (templateDAO, error)) *notificationTemplateStoreInterfaceMock_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateByHandle provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) GetTemplateByHandle(ctx context.Context, channel ChannelType, handle string) (templateDAO, error) {
	ret := _mock.Called(ctx, channel, handle)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByHandle")
	}

	var r0 templateDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) (templateDAO, error)); ok {
		return returnFunc(ctx, channel, handle)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) templateDAO); ok {
		r0 = returnFunc(ctx, channel, handle)
	} else {
		r0 = ret.Get(0).(templateDAO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChannelType, string) error); ok {
		r1 = returnFunc(ctx, channel, handle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByHandle'
type notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call struct {
	*mock.Call
}

// GetTemplateByHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
//   - handle string
func (_e *notificationTemplateStoreInterfaceMock_Expecter) GetTemplateByHandle(ctx any, channel any, handle any) *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call {
	return &notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call{Call: _e.mock.On("GetTemplateByHandle", ctx, channel, handle)}
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call) Run(run func(ctx context.Context, channel ChannelType, handle string)) *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call) Return(templateDAOMoqParam templateDAO, err error) *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call {
	_c.Call.Return(templateDAOMoqParam, err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType, handle string) (templateDAO, error)) *notificationTemplateStoreInterfaceMock_GetTemplateByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// IsHandleExists provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) IsHandleExists(ctx context.Context, channel ChannelType, handle string) (bool, error) {
	ret := _mock.Called(ctx, channel, handle)

	if len(ret) == 0 {
		panic("no return value specified for IsHandleExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) (bool, error)); ok {
		return returnFunc(ctx, channel, handle)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, string) bool); ok {
		r0 = returnFunc(ctx, channel, handle)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChannelType, string) error); ok {
		r1 = returnFunc(ctx, channel, handle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notificationTemplateStoreInterfaceMock_IsHandleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHandleExists'
type notificationTemplateStoreInterfaceMock_IsHandleExists_Call struct {
	*mock.Call
}

// IsHandleExists is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
//   - handle string
func (_e *notificationTemplateStoreInterfaceMock_Expecter) IsHandleExists(ctx any, channel any, handle any) *notificationTemplateStoreInterfaceMock_IsHandleExists_Call {
	return &notificationTemplateStoreInterfaceMock_IsHandleExists_Call{Call: _e.mock.On("IsHandleExists", ctx, channel, handle)}
}

func (_c *notificationTemplateStoreInterfaceMock_IsHandleExists_Call) Run(run func(ctx context.Context, channel ChannelType, handle string)) *notificationTemplateStoreInterfaceMock_IsHandleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_IsHandleExists_Call) Return(b bool, err error) *notificationTemplateStoreInterfaceMock_IsHandleExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_IsHandleExists_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType, handle string) (bool, error)) *notificationTemplateStoreInterfaceMock_IsHandleExists_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) ListTemplates(ctx context.Context, channel ChannelType, limit int, offset int) ([]templateDAO, error) {
	ret := _mock.Called(ctx, channel, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []templateDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, int, int) ([]templateDAO, error)); ok {
		return returnFunc(ctx, channel, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChannelType, int, int) []templateDAO); ok {
		r0 = returnFunc(ctx, channel, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]templateDAO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChannelType, int, int) error); ok {
		r1 = returnFunc(ctx, channel, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notificationTemplateStoreInterfaceMock_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type notificationTemplateStoreInterfaceMock_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - channel ChannelType
//   - limit int
//   - offset int
func (_e *notificationTemplateStoreInterfaceMock_Expecter) ListTemplates(ctx any, channel any, limit any, offset any) *notificationTemplateStoreInterfaceMock_ListTemplates_Call {
	return &notificationTemplateStoreInterfaceMock_ListTemplates_Call{Call: _e.mock.On("ListTemplates", ctx, channel, limit, offset)}
}

func (_c *notificationTemplateStoreInterfaceMock_ListTemplates_Call) Run(run func(ctx context.Context, channel ChannelType, limit int, offset int)) *notificationTemplateStoreInterfaceMock_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChannelType
		if args[1] != nil {
			arg1 = args[1].(ChannelType)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_ListTemplates_Call) Return(templateDAOMoqParams []templateDAO, err error) *notificationTemplateStoreInterfaceMock_ListTemplates_Call {
	_c.Call.Return(templateDAOMoqParams, err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_ListTemplates_Call) RunAndReturn(run func(ctx context.Context, channel ChannelType, limit int, offset int) ([]templateDAO, error)) *notificationTemplateStoreInterfaceMock_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function for the type notificationTemplateStoreInterfaceMock
func (_mock *notificationTemplateStoreInterfaceMock) UpdateTemplate(ctx context.Context, template templateDAO) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, templateDAO) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// notificationTemplateStoreInterfaceMock_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type notificationTemplateStoreInterfaceMock_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template templateDAO
func (_e *notificationTemplateStoreInterfaceMock_Expecter) UpdateTemplate(ctx any, template any) *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call {
	return &notificationTemplateStoreInterfaceMock_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, template)}
}

func (_c *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call) Run(run func(ctx context.Context, template templateDAO)) *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 templateDAO
		if args[1] != nil {
			arg1 = args[1].(templateDAO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call) Return(err error) *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call) RunAndReturn(run func(ctx context.Context, template templateDAO) error) *notificationTemplateStoreInterfaceMock_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}
