// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionmock

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/flow/session"
)

// NewHandleTransportMock creates a new instance of HandleTransportMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandleTransportMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandleTransportMock {
	mock := &HandleTransportMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HandleTransportMock is an autogenerated mock type for the HandleTransport type
type HandleTransportMock struct {
	mock.Mock
}

type HandleTransportMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HandleTransportMock) EXPECT() *HandleTransportMock_Expecter {
	return &HandleTransportMock_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type HandleTransportMock
func (_mock *HandleTransportMock) Clear(x *session.Exchange, flowID string) {
	_mock.Called(x, flowID)
	return
}

// HandleTransportMock_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type HandleTransportMock_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - x *session.Exchange
//   - flowID string
func (_e *HandleTransportMock_Expecter) Clear(x interface{}, flowID interface{}) *HandleTransportMock_Clear_Call {
	return &HandleTransportMock_Clear_Call{Call: _e.mock.On("Clear", x, flowID)}
}

func (_c *HandleTransportMock_Clear_Call) Run(run func(x *session.Exchange, flowID string)) *HandleTransportMock_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *session.Exchange
		if args[0] != nil {
			arg0 = args[0].(*session.Exchange)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HandleTransportMock_Clear_Call) Return() *HandleTransportMock_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *HandleTransportMock_Clear_Call) RunAndReturn(run func(x *session.Exchange, flowID string)) *HandleTransportMock_Clear_Call {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type HandleTransportMock
func (_mock *HandleTransportMock) Read(x *session.Exchange) session.InboundHandle {
	ret := _mock.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 session.InboundHandle
	if returnFunc, ok := ret.Get(0).(func(*session.Exchange) session.InboundHandle); ok {
		r0 = returnFunc(x)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(session.InboundHandle)
		}
	}
	return r0
}

// HandleTransportMock_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type HandleTransportMock_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - x *session.Exchange
func (_e *HandleTransportMock_Expecter) Read(x interface{}) *HandleTransportMock_Read_Call {
	return &HandleTransportMock_Read_Call{Call: _e.mock.On("Read", x)}
}

func (_c *HandleTransportMock_Read_Call) Run(run func(x *session.Exchange)) *HandleTransportMock_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *session.Exchange
		if args[0] != nil {
			arg0 = args[0].(*session.Exchange)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HandleTransportMock_Read_Call) Return(inboundHandle session.InboundHandle) *HandleTransportMock_Read_Call {
	_c.Call.Return(inboundHandle)
	return _c
}

func (_c *HandleTransportMock_Read_Call) RunAndReturn(run func(x *session.Exchange) session.InboundHandle) *HandleTransportMock_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type HandleTransportMock
func (_mock *HandleTransportMock) Write(x *session.Exchange, flowID string, handle string, ttl time.Duration) {
	_mock.Called(x, flowID, handle, ttl)
	return
}

// HandleTransportMock_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type HandleTransportMock_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - x *session.Exchange
//   - flowID string
//   - handle string
//   - ttl time.Duration
func (_e *HandleTransportMock_Expecter) Write(x interface{}, flowID interface{}, handle interface{}, ttl interface{}) *HandleTransportMock_Write_Call {
	return &HandleTransportMock_Write_Call{Call: _e.mock.On("Write", x, flowID, handle, ttl)}
}

func (_c *HandleTransportMock_Write_Call) Run(run func(x *session.Exchange, flowID string, handle string, ttl time.Duration)) *HandleTransportMock_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *session.Exchange
		if args[0] != nil {
			arg0 = args[0].(*session.Exchange)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *HandleTransportMock_Write_Call) Return() *HandleTransportMock_Write_Call {
	_c.Call.Return()
	return _c
}

func (_c *HandleTransportMock_Write_Call) RunAndReturn(run func(x *session.Exchange, flowID string, handle string, ttl time.Duration)) *HandleTransportMock_Write_Call {
	_c.Run(run)
	return _c
}
