// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rolemock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/role"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewRoleAssignmentServiceInterfaceMock creates a new instance of RoleAssignmentServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleAssignmentServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleAssignmentServiceInterfaceMock {
	mock := &RoleAssignmentServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleAssignmentServiceInterfaceMock is an autogenerated mock type for the RoleAssignmentServiceInterface type
type RoleAssignmentServiceInterfaceMock struct {
	mock.Mock
}

type RoleAssignmentServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleAssignmentServiceInterfaceMock) EXPECT() *RoleAssignmentServiceInterfaceMock_Expecter {
	return &RoleAssignmentServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) AddAssignments(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, id, assignments)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []role.RoleAssignment) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, id, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleAssignmentServiceInterfaceMock_AddAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssignments'
type RoleAssignmentServiceInterfaceMock_AddAssignments_Call struct {
	*mock.Call
}

// AddAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assignments []role.RoleAssignment
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) AddAssignments(ctx interface{}, id interface{}, assignments interface{}) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_AddAssignments_Call{Call: _e.mock.On("AddAssignments", ctx, id, assignments)}
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) Run(run func(ctx context.Context, id string, assignments []role.RoleAssignment)) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []role.RoleAssignment
		if args[2] != nil {
			arg2 = args[2].([]role.RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetRoleAssignments(ctx context.Context, id string, limit int, offset int, includeDisplay bool) (*role.AssignmentList, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id, limit, offset, includeDisplay)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignments")
	}

	var r0 *role.AssignmentList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool) (*role.AssignmentList, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id, limit, offset, includeDisplay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool) *role.AssignmentList); ok {
		r0 = returnFunc(ctx, id, limit, offset, includeDisplay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id, limit, offset, includeDisplay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignments'
type RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call struct {
	*mock.Call
}

// GetRoleAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - limit int
//   - offset int
//   - includeDisplay bool
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetRoleAssignments(ctx interface{}, id interface{}, limit interface{}, offset interface{}, includeDisplay interface{}) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call{Call: _e.mock.On("GetRoleAssignments", ctx, id, limit, offset, includeDisplay)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) Run(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) Return(assignmentList *role.AssignmentList, serviceError *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool) (*role.AssignmentList, *serviceerror.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignmentsByType provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetRoleAssignmentsByType(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string) (*role.AssignmentList, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id, limit, offset, includeDisplay, assigneeType)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignmentsByType")
	}

	var r0 *role.AssignmentList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool, string) (*role.AssignmentList, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, bool, string) *role.AssignmentList); ok {
		r0 = returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int, bool, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignmentsByType'
type RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call struct {
	*mock.Call
}

// GetRoleAssignmentsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - limit int
//   - offset int
//   - includeDisplay bool
//   - assigneeType string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetRoleAssignmentsByType(ctx interface{}, id interface{}, limit interface{}, offset interface{}, includeDisplay interface{}, assigneeType interface{}) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	return &RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call{Call: _e.mock.On("GetRoleAssignmentsByType", ctx, id, limit, offset, includeDisplay, assigneeType)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) Run(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) Return(assignmentList *role.AssignmentList, serviceError *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) RunAndReturn(run func(ctx context.Context, id string, limit int, offset int, includeDisplay bool, assigneeType string) (*role.AssignmentList, *serviceerror.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) RemoveAssignments(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, id, assignments)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []role.RoleAssignment) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, id, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - assignments []role.RoleAssignment
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) RemoveAssignments(ctx interface{}, id interface{}, assignments interface{}) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", ctx, id, assignments)}
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) Run(run func(ctx context.Context, id string, assignments []role.RoleAssignment)) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []role.RoleAssignment
		if args[2] != nil {
			arg2 = args[2].([]role.RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, assignments []role.RoleAssignment) *serviceerror.ServiceError) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}
