// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package corsmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewMergedConfigReaderMock creates a new instance of MergedConfigReaderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMergedConfigReaderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MergedConfigReaderMock {
	mock := &MergedConfigReaderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MergedConfigReaderMock is an autogenerated mock type for the MergedConfigReader type
type MergedConfigReaderMock struct {
	mock.Mock
}

type MergedConfigReaderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MergedConfigReaderMock) EXPECT() *MergedConfigReaderMock_Expecter {
	return &MergedConfigReaderMock_Expecter{mock: &_m.Mock}
}

// GetMergedConfig provides a mock function for the type MergedConfigReaderMock
func (_mock *MergedConfigReaderMock) GetMergedConfig(ctx context.Context, name string) (any, *common.ServiceError) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMergedConfig")
	}

	var r0 any
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, *common.ServiceError)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// MergedConfigReaderMock_GetMergedConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergedConfig'
type MergedConfigReaderMock_GetMergedConfig_Call struct {
	*mock.Call
}

// GetMergedConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MergedConfigReaderMock_Expecter) GetMergedConfig(ctx interface{}, name interface{}) *MergedConfigReaderMock_GetMergedConfig_Call {
	return &MergedConfigReaderMock_GetMergedConfig_Call{Call: _e.mock.On("GetMergedConfig", ctx, name)}
}

func (_c *MergedConfigReaderMock_GetMergedConfig_Call) Run(run func(ctx context.Context, name string)) *MergedConfigReaderMock_GetMergedConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MergedConfigReaderMock_GetMergedConfig_Call) Return(v any, serviceError *common.ServiceError) *MergedConfigReaderMock_GetMergedConfig_Call {
	_c.Call.Return(v, serviceError)
	return _c
}

func (_c *MergedConfigReaderMock_GetMergedConfig_Call) RunAndReturn(run func(ctx context.Context, name string) (any, *common.ServiceError)) *MergedConfigReaderMock_GetMergedConfig_Call {
	_c.Call.Return(run)
	return _c
}
