// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package managermock

import (
	"context"

	"github.com/asgardeo/thunder/internal/authnprovider/common"
	"github.com/asgardeo/thunder/internal/authnprovider/manager"
	"github.com/asgardeo/thunder/internal/entityprovider"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthnProviderManagerInterfaceMock creates a new instance of AuthnProviderManagerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthnProviderManagerInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthnProviderManagerInterfaceMock {
	mock := &AuthnProviderManagerInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthnProviderManagerInterfaceMock is an autogenerated mock type for the AuthnProviderManagerInterface type
type AuthnProviderManagerInterfaceMock struct {
	mock.Mock
}

type AuthnProviderManagerInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthnProviderManagerInterfaceMock) EXPECT() *AuthnProviderManagerInterfaceMock_Expecter {
	return &AuthnProviderManagerInterfaceMock_Expecter{mock: &_m.Mock}
}

// AuthenticateForRegistration provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) AuthenticateForRegistration(ctx context.Context, credentialType string, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, credentialType, authUser)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateForRegistration")
	}

	var r0 manager.AuthUser
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, credentialType, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, credentialType, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, manager.AuthUser) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, credentialType, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateForRegistration'
type AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call struct {
	*mock.Call
}

// AuthenticateForRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialType string
//   - authUser manager.AuthUser
func (_e *AuthnProviderManagerInterfaceMock_Expecter) AuthenticateForRegistration(ctx interface{}, credentialType interface{}, authUser interface{}) *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call {
	return &AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call{Call: _e.mock.On("AuthenticateForRegistration", ctx, credentialType, authUser)}
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call) Run(run func(ctx context.Context, credentialType string, authUser manager.AuthUser)) *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 manager.AuthUser
		if args[2] != nil {
			arg2 = args[2].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call) Return(authUser1 manager.AuthUser, serviceError *serviceerror.ServiceError) *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call {
	_c.Call.Return(authUser1, serviceError)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call) RunAndReturn(run func(ctx context.Context, credentialType string, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)) *AuthnProviderManagerInterfaceMock_AuthenticateForRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateResolvedUser provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) AuthenticateResolvedUser(ctx context.Context, resolvedUser *entityprovider.Entity, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, resolvedUser, authUser)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateResolvedUser")
	}

	var r0 manager.AuthUser
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entityprovider.Entity, manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, resolvedUser, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entityprovider.Entity, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, resolvedUser, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entityprovider.Entity, manager.AuthUser) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, resolvedUser, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateResolvedUser'
type AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call struct {
	*mock.Call
}

// AuthenticateResolvedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - resolvedUser *entityprovider.Entity
//   - authUser manager.AuthUser
func (_e *AuthnProviderManagerInterfaceMock_Expecter) AuthenticateResolvedUser(ctx interface{}, resolvedUser interface{}, authUser interface{}) *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call {
	return &AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call{Call: _e.mock.On("AuthenticateResolvedUser", ctx, resolvedUser, authUser)}
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call) Run(run func(ctx context.Context, resolvedUser *entityprovider.Entity, authUser manager.AuthUser)) *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entityprovider.Entity
		if args[1] != nil {
			arg1 = args[1].(*entityprovider.Entity)
		}
		var arg2 manager.AuthUser
		if args[2] != nil {
			arg2 = args[2].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call) Return(authUser1 manager.AuthUser, serviceError *serviceerror.ServiceError) *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call {
	_c.Call.Return(authUser1, serviceError)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call) RunAndReturn(run func(ctx context.Context, resolvedUser *entityprovider.Entity, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)) *AuthnProviderManagerInterfaceMock_AuthenticateResolvedUser_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateUser provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) AuthenticateUser(ctx context.Context, authnType string, authnData any, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, authnType, authnData, requestedAttributes, metadata, authUser)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 manager.AuthUser
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, authnType, authnData, requestedAttributes, metadata, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, authnType, authnData, requestedAttributes, metadata, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any, *common.RequestedAttributes, *common.AuthnMetadata, manager.AuthUser) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, authnType, authnData, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// AuthnProviderManagerInterfaceMock_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type AuthnProviderManagerInterfaceMock_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authnType string
//   - authnData any
//   - requestedAttributes *common.RequestedAttributes
//   - metadata *common.AuthnMetadata
//   - authUser manager.AuthUser
func (_e *AuthnProviderManagerInterfaceMock_Expecter) AuthenticateUser(ctx interface{}, authnType interface{}, authnData interface{}, requestedAttributes interface{}, metadata interface{}, authUser interface{}) *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call {
	return &AuthnProviderManagerInterfaceMock_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, authnType, authnData, requestedAttributes, metadata, authUser)}
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call) Run(run func(ctx context.Context, authnType string, authnData any, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser)) *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 *common.RequestedAttributes
		if args[3] != nil {
			arg3 = args[3].(*common.RequestedAttributes)
		}
		var arg4 *common.AuthnMetadata
		if args[4] != nil {
			arg4 = args[4].(*common.AuthnMetadata)
		}
		var arg5 manager.AuthUser
		if args[5] != nil {
			arg5 = args[5].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call) Return(authUser1 manager.AuthUser, serviceError *serviceerror.ServiceError) *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call {
	_c.Call.Return(authUser1, serviceError)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, authnType string, authnData any, requestedAttributes *common.RequestedAttributes, metadata *common.AuthnMetadata, authUser manager.AuthUser) (manager.AuthUser, *serviceerror.ServiceError)) *AuthnProviderManagerInterfaceMock_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticatorFactors provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) GetAuthenticatorFactors(authenticatorName string) []common.AuthenticationFactor {
	ret := _mock.Called(authenticatorName)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticatorFactors")
	}

	var r0 []common.AuthenticationFactor
	if returnFunc, ok := ret.Get(0).(func(string) []common.AuthenticationFactor); ok {
		r0 = returnFunc(authenticatorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.AuthenticationFactor)
		}
	}
	return r0
}

// AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticatorFactors'
type AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call struct {
	*mock.Call
}

// GetAuthenticatorFactors is a helper method to define mock.On call
//   - authenticatorName string
func (_e *AuthnProviderManagerInterfaceMock_Expecter) GetAuthenticatorFactors(authenticatorName interface{}) *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call {
	return &AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call{Call: _e.mock.On("GetAuthenticatorFactors", authenticatorName)}
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call) Run(run func(authenticatorName string)) *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call) Return(authenticationFactors []common.AuthenticationFactor) *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call {
	_c.Call.Return(authenticationFactors)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call) RunAndReturn(run func(authenticatorName string) []common.AuthenticationFactor) *AuthnProviderManagerInterfaceMock_GetAuthenticatorFactors_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticatorMetadata provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) GetAuthenticatorMetadata(authenticatorName string) *common.AuthenticatorMeta {
	ret := _mock.Called(authenticatorName)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticatorMetadata")
	}

	var r0 *common.AuthenticatorMeta
	if returnFunc, ok := ret.Get(0).(func(string) *common.AuthenticatorMeta); ok {
		r0 = returnFunc(authenticatorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthenticatorMeta)
		}
	}
	return r0
}

// AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticatorMetadata'
type AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call struct {
	*mock.Call
}

// GetAuthenticatorMetadata is a helper method to define mock.On call
//   - authenticatorName string
func (_e *AuthnProviderManagerInterfaceMock_Expecter) GetAuthenticatorMetadata(authenticatorName interface{}) *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call {
	return &AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call{Call: _e.mock.On("GetAuthenticatorMetadata", authenticatorName)}
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call) Run(run func(authenticatorName string)) *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call) Return(authenticatorMeta *common.AuthenticatorMeta) *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call {
	_c.Call.Return(authenticatorMeta)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call) RunAndReturn(run func(authenticatorName string) *common.AuthenticatorMeta) *AuthnProviderManagerInterfaceMock_GetAuthenticatorMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAttributes provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) GetUserAttributes(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, requestedAttributes, metadata, authUser)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAttributes")
	}

	var r0 manager.AuthUser
	var r1 *common.AttributesResponse
	var r2 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, requestedAttributes, metadata, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) manager.AuthUser); ok {
		r0 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		r0 = ret.Get(0).(manager.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) *common.AttributesResponse); ok {
		r1 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.AttributesResponse)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *common.RequestedAttributes, *common.GetAttributesMetadata, manager.AuthUser) *serviceerror.ServiceError); ok {
		r2 = returnFunc(ctx, requestedAttributes, metadata, authUser)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*serviceerror.ServiceError)
		}
	}
	return r0, r1, r2
}

// AuthnProviderManagerInterfaceMock_GetUserAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAttributes'
type AuthnProviderManagerInterfaceMock_GetUserAttributes_Call struct {
	*mock.Call
}

// GetUserAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - requestedAttributes *common.RequestedAttributes
//   - metadata *common.GetAttributesMetadata
//   - authUser manager.AuthUser
func (_e *AuthnProviderManagerInterfaceMock_Expecter) GetUserAttributes(ctx interface{}, requestedAttributes interface{}, metadata interface{}, authUser interface{}) *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call {
	return &AuthnProviderManagerInterfaceMock_GetUserAttributes_Call{Call: _e.mock.On("GetUserAttributes", ctx, requestedAttributes, metadata, authUser)}
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call) Run(run func(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser)) *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *common.RequestedAttributes
		if args[1] != nil {
			arg1 = args[1].(*common.RequestedAttributes)
		}
		var arg2 *common.GetAttributesMetadata
		if args[2] != nil {
			arg2 = args[2].(*common.GetAttributesMetadata)
		}
		var arg3 manager.AuthUser
		if args[3] != nil {
			arg3 = args[3].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call) Return(authUser1 manager.AuthUser, attributesResponse *common.AttributesResponse, serviceError *serviceerror.ServiceError) *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call {
	_c.Call.Return(authUser1, attributesResponse, serviceError)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call) RunAndReturn(run func(ctx context.Context, requestedAttributes *common.RequestedAttributes, metadata *common.GetAttributesMetadata, authUser manager.AuthUser) (manager.AuthUser, *common.AttributesResponse, *serviceerror.ServiceError)) *AuthnProviderManagerInterfaceMock_GetUserAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAvailableAttributes provides a mock function for the type AuthnProviderManagerInterfaceMock
func (_mock *AuthnProviderManagerInterfaceMock) GetUserAvailableAttributes(ctx context.Context, authUser manager.AuthUser) (*common.AttributesResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, authUser)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAvailableAttributes")
	}

	var r0 *common.AttributesResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.AuthUser) (*common.AttributesResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, authUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.AuthUser) *common.AttributesResponse); ok {
		r0 = returnFunc(ctx, authUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AttributesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manager.AuthUser) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, authUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAvailableAttributes'
type AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call struct {
	*mock.Call
}

// GetUserAvailableAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - authUser manager.AuthUser
func (_e *AuthnProviderManagerInterfaceMock_Expecter) GetUserAvailableAttributes(ctx interface{}, authUser interface{}) *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call {
	return &AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call{Call: _e.mock.On("GetUserAvailableAttributes", ctx, authUser)}
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call) Run(run func(ctx context.Context, authUser manager.AuthUser)) *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manager.AuthUser
		if args[1] != nil {
			arg1 = args[1].(manager.AuthUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call) Return(attributesResponse *common.AttributesResponse, serviceError *serviceerror.ServiceError) *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call {
	_c.Call.Return(attributesResponse, serviceError)
	return _c
}

func (_c *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call) RunAndReturn(run func(ctx context.Context, authUser manager.AuthUser) (*common.AttributesResponse, *serviceerror.ServiceError)) *AuthnProviderManagerInterfaceMock_GetUserAvailableAttributes_Call {
	_c.Call.Return(run)
	return _c
}
