# Copyright 2026 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

services:
  redis:
    image: redis:7.4-alpine
    restart: always
    environment:
      REDIS_USERNAME: dbuser
      REDIS_PASSWORD: dbpassword
    command: >
      redis-server
      --user default off
      --user dbuser on ">dbpassword" ~* &* +@all
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
