// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewOUEnumeratorMock creates a new instance of OUEnumeratorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOUEnumeratorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OUEnumeratorMock {
	mock := &OUEnumeratorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OUEnumeratorMock is an autogenerated mock type for the OUEnumerator type
type OUEnumeratorMock struct {
	mock.Mock
}

type OUEnumeratorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OUEnumeratorMock) EXPECT() *OUEnumeratorMock_Expecter {
	return &OUEnumeratorMock_Expecter{mock: &_m.Mock}
}

// AllOUIDs provides a mock function for the type OUEnumeratorMock
func (_mock *OUEnumeratorMock) AllOUIDs(ctx context.Context) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllOUIDs")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *common.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// OUEnumeratorMock_AllOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllOUIDs'
type OUEnumeratorMock_AllOUIDs_Call struct {
	*mock.Call
}

// AllOUIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OUEnumeratorMock_Expecter) AllOUIDs(ctx interface{}) *OUEnumeratorMock_AllOUIDs_Call {
	return &OUEnumeratorMock_AllOUIDs_Call{Call: _e.mock.On("AllOUIDs", ctx)}
}

func (_c *OUEnumeratorMock_AllOUIDs_Call) Run(run func(ctx context.Context)) *OUEnumeratorMock_AllOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OUEnumeratorMock_AllOUIDs_Call) Return(strings []string, serviceError *common.ServiceError) *OUEnumeratorMock_AllOUIDs_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *OUEnumeratorMock_AllOUIDs_Call) RunAndReturn(run func(ctx context.Context) ([]string, *common.ServiceError)) *OUEnumeratorMock_AllOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DescendantOUIDs provides a mock function for the type OUEnumeratorMock
func (_mock *OUEnumeratorMock) DescendantOUIDs(ctx context.Context, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, ouID)

	if len(ret) == 0 {
		panic("no return value specified for DescendantOUIDs")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// OUEnumeratorMock_DescendantOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescendantOUIDs'
type OUEnumeratorMock_DescendantOUIDs_Call struct {
	*mock.Call
}

// DescendantOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
func (_e *OUEnumeratorMock_Expecter) DescendantOUIDs(ctx interface{}, ouID interface{}) *OUEnumeratorMock_DescendantOUIDs_Call {
	return &OUEnumeratorMock_DescendantOUIDs_Call{Call: _e.mock.On("DescendantOUIDs", ctx, ouID)}
}

func (_c *OUEnumeratorMock_DescendantOUIDs_Call) Run(run func(ctx context.Context, ouID string)) *OUEnumeratorMock_DescendantOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OUEnumeratorMock_DescendantOUIDs_Call) Return(strings []string, serviceError *common.ServiceError) *OUEnumeratorMock_DescendantOUIDs_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *OUEnumeratorMock_DescendantOUIDs_Call) RunAndReturn(run func(ctx context.Context, ouID string) ([]string, *common.ServiceError)) *OUEnumeratorMock_DescendantOUIDs_Call {
	_c.Call.Return(run)
	return _c
}
