// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauthmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/authn/common"
	"github.com/thunder-id/thunderid/internal/authn/oauth"
	common0 "github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewOAuthAuthnCoreServiceInterfaceMock creates a new instance of OAuthAuthnCoreServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthAuthnCoreServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthAuthnCoreServiceInterfaceMock {
	mock := &OAuthAuthnCoreServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthAuthnCoreServiceInterfaceMock is an autogenerated mock type for the OAuthAuthnCoreServiceInterface type
type OAuthAuthnCoreServiceInterfaceMock struct {
	mock.Mock
}

type OAuthAuthnCoreServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthAuthnCoreServiceInterfaceMock) EXPECT() *OAuthAuthnCoreServiceInterfaceMock_Expecter {
	return &OAuthAuthnCoreServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) Authenticate(ctx context.Context, idpID string, code string) (*common.AuthnResult, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID, code)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *common.AuthnResult
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*common.AuthnResult, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *common.AuthnResult); ok {
		r0 = returnFunc(ctx, idpID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthnResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, code)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - code string
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) Authenticate(ctx interface{}, idpID interface{}, code interface{}) *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, idpID, code)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call) Run(run func(ctx context.Context, idpID string, code string)) *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call) Return(authnResult *common.AuthnResult, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(authnResult, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, idpID string, code string) (*common.AuthnResult, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// BuildAuthorizeURL provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) BuildAuthorizeURL(ctx context.Context, idpID string) (string, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID)

	if len(ret) == 0 {
		panic("no return value specified for BuildAuthorizeURL")
	}

	var r0 string
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, idpID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildAuthorizeURL'
type OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call struct {
	*mock.Call
}

// BuildAuthorizeURL is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) BuildAuthorizeURL(ctx interface{}, idpID interface{}) *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call{Call: _e.mock.On("BuildAuthorizeURL", ctx, idpID)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) Run(run func(ctx context.Context, idpID string)) *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) Return(s string, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) RunAndReturn(run func(ctx context.Context, idpID string) (string, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// BuildFederatedAuthResult provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) BuildFederatedAuthResult(ctx context.Context, idpID string, sub string, claims map[string]interface{}) (*common.AuthnResult, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID, sub, claims)

	if len(ret) == 0 {
		panic("no return value specified for BuildFederatedAuthResult")
	}

	var r0 *common.AuthnResult
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) (*common.AuthnResult, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID, sub, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) *common.AuthnResult); ok {
		r0 = returnFunc(ctx, idpID, sub, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthnResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, sub, claims)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildFederatedAuthResult'
type OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call struct {
	*mock.Call
}

// BuildFederatedAuthResult is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - sub string
//   - claims map[string]interface{}
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) BuildFederatedAuthResult(ctx interface{}, idpID interface{}, sub interface{}, claims interface{}) *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call{Call: _e.mock.On("BuildFederatedAuthResult", ctx, idpID, sub, claims)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call) Run(run func(ctx context.Context, idpID string, sub string, claims map[string]interface{})) *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call) Return(authnResult *common.AuthnResult, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call {
	_c.Call.Return(authnResult, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call) RunAndReturn(run func(ctx context.Context, idpID string, sub string, claims map[string]interface{}) (*common.AuthnResult, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_BuildFederatedAuthResult_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCodeForToken provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) ExchangeCodeForToken(ctx context.Context, idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID, code, validateResponse)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth.TokenResponse
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*oauth.TokenResponse, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID, code, validateResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, idpID, code, validateResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, code, validateResponse)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - code string
//   - validateResponse bool
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) ExchangeCodeForToken(ctx interface{}, idpID interface{}, code interface{}, validateResponse interface{}) *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", ctx, idpID, code, validateResponse)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) Run(run func(ctx context.Context, idpID string, code string, validateResponse bool)) *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) Return(tokenResponse *oauth.TokenResponse, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(tokenResponse, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) RunAndReturn(run func(ctx context.Context, idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserInfo provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) FetchUserInfo(ctx context.Context, idpID string, accessToken string) (map[string]interface{}, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserInfo")
	}

	var r0 map[string]interface{}
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = returnFunc(ctx, idpID, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserInfo'
type OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call struct {
	*mock.Call
}

// FetchUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - accessToken string
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) FetchUserInfo(ctx interface{}, idpID interface{}, accessToken interface{}) *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call{Call: _e.mock.On("FetchUserInfo", ctx, idpID, accessToken)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) Run(run func(ctx context.Context, idpID string, accessToken string)) *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) RunAndReturn(run func(ctx context.Context, idpID string, accessToken string) (map[string]interface{}, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthClientConfig provides a mock function for the type OAuthAuthnCoreServiceInterfaceMock
func (_mock *OAuthAuthnCoreServiceInterfaceMock) GetOAuthClientConfig(ctx context.Context, idpID string) (*oauth.OAuthClientConfig, *common0.ServiceError) {
	ret := _mock.Called(ctx, idpID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthClientConfig")
	}

	var r0 *oauth.OAuthClientConfig
	var r1 *common0.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oauth.OAuthClientConfig, *common0.ServiceError)); ok {
		return returnFunc(ctx, idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oauth.OAuthClientConfig); ok {
		r0 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.OAuthClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common0.ServiceError); ok {
		r1 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common0.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthClientConfig'
type OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call struct {
	*mock.Call
}

// GetOAuthClientConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
func (_e *OAuthAuthnCoreServiceInterfaceMock_Expecter) GetOAuthClientConfig(ctx interface{}, idpID interface{}) *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call {
	return &OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call{Call: _e.mock.On("GetOAuthClientConfig", ctx, idpID)}
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call) Run(run func(ctx context.Context, idpID string)) *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call) Return(oAuthClientConfig *oauth.OAuthClientConfig, serviceError *common0.ServiceError) *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(oAuthClientConfig, serviceError)
	return _c
}

func (_c *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call) RunAndReturn(run func(ctx context.Context, idpID string) (*oauth.OAuthClientConfig, *common0.ServiceError)) *OAuthAuthnCoreServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(run)
	return _c
}
