// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sysauthzmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewOUHierarchyResolverMock creates a new instance of OUHierarchyResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOUHierarchyResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OUHierarchyResolverMock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &OUHierarchyResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// OUHierarchyResolverMock is an autogenerated mock type for the OUHierarchyResolver type
type OUHierarchyResolverMock struct {
	mock.Mock
}

type OUHierarchyResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OUHierarchyResolverMock) EXPECT() *OUHierarchyResolverMock_Expecter {
	return &OUHierarchyResolverMock_Expecter{mock: &_m.Mock}
}

// GetAncestorOUIDs provides a mock function for the type OUHierarchyResolverMock
func (_mock *OUHierarchyResolverMock) GetAncestorOUIDs(ctx context.Context, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, ouID)

	if len(ret) == 0 {
		panic("no return value specified for GetAncestorOUIDs")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// OUHierarchyResolverMock_GetAncestorOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAncestorOUIDs'
type OUHierarchyResolverMock_GetAncestorOUIDs_Call struct {
	*mock.Call
}

// GetAncestorOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
func (_e *OUHierarchyResolverMock_Expecter) GetAncestorOUIDs(ctx any, ouID any) *OUHierarchyResolverMock_GetAncestorOUIDs_Call {
	return &OUHierarchyResolverMock_GetAncestorOUIDs_Call{Call: _e.mock.On("GetAncestorOUIDs", ctx, ouID)}
}

func (_c *OUHierarchyResolverMock_GetAncestorOUIDs_Call) Run(run func(ctx context.Context, ouID string)) *OUHierarchyResolverMock_GetAncestorOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OUHierarchyResolverMock_GetAncestorOUIDs_Call) Return(strings []string, serviceError *common.ServiceError) *OUHierarchyResolverMock_GetAncestorOUIDs_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *OUHierarchyResolverMock_GetAncestorOUIDs_Call) RunAndReturn(run func(ctx context.Context, ouID string) ([]string, *common.ServiceError)) *OUHierarchyResolverMock_GetAncestorOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IsAncestor provides a mock function for the type OUHierarchyResolverMock
func (_mock *OUHierarchyResolverMock) IsAncestor(ctx context.Context, ancestorOUID string, descendantOUID string) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, ancestorOUID, descendantOUID)

	if len(ret) == 0 {
		panic("no return value specified for IsAncestor")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, ancestorOUID, descendantOUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, ancestorOUID, descendantOUID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, ancestorOUID, descendantOUID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// OUHierarchyResolverMock_IsAncestor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAncestor'
type OUHierarchyResolverMock_IsAncestor_Call struct {
	*mock.Call
}

// IsAncestor is a helper method to define mock.On call
//   - ctx context.Context
//   - ancestorOUID string
//   - descendantOUID string
func (_e *OUHierarchyResolverMock_Expecter) IsAncestor(ctx any, ancestorOUID any, descendantOUID any) *OUHierarchyResolverMock_IsAncestor_Call {
	return &OUHierarchyResolverMock_IsAncestor_Call{Call: _e.mock.On("IsAncestor", ctx, ancestorOUID, descendantOUID)}
}

func (_c *OUHierarchyResolverMock_IsAncestor_Call) Run(run func(ctx context.Context, ancestorOUID string, descendantOUID string)) *OUHierarchyResolverMock_IsAncestor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OUHierarchyResolverMock_IsAncestor_Call) Return(b bool, serviceError *common.ServiceError) *OUHierarchyResolverMock_IsAncestor_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *OUHierarchyResolverMock_IsAncestor_Call) RunAndReturn(run func(ctx context.Context, ancestorOUID string, descendantOUID string) (bool, *common.ServiceError)) *OUHierarchyResolverMock_IsAncestor_Call {
	_c.Call.Return(run)
	return _c
}
