// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consent

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// newConsentClientInterfaceMock creates a new instance of consentClientInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newConsentClientInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *consentClientInterfaceMock {
	mock := &consentClientInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// consentClientInterfaceMock is an autogenerated mock type for the consentClientInterface type
type consentClientInterfaceMock struct {
	mock.Mock
}

type consentClientInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *consentClientInterfaceMock) EXPECT() *consentClientInterfaceMock_Expecter {
	return &consentClientInterfaceMock_Expecter{mock: &_m.Mock}
}

// createConsent provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) createConsent(ctx context.Context, ouID string, req *ConsentRequest) (*Consent, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, req)

	if len(ret) == 0 {
		panic("no return value specified for createConsent")
	}

	var r0 *Consent
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentRequest) (*Consent, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentRequest) *Consent); ok {
		r0 = returnFunc(ctx, ouID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Consent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *ConsentRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_createConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createConsent'
type consentClientInterfaceMock_createConsent_Call struct {
	*mock.Call
}

// createConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - req *ConsentRequest
func (_e *consentClientInterfaceMock_Expecter) createConsent(ctx interface{}, ouID interface{}, req interface{}) *consentClientInterfaceMock_createConsent_Call {
	return &consentClientInterfaceMock_createConsent_Call{Call: _e.mock.On("createConsent", ctx, ouID, req)}
}

func (_c *consentClientInterfaceMock_createConsent_Call) Run(run func(ctx context.Context, ouID string, req *ConsentRequest)) *consentClientInterfaceMock_createConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ConsentRequest
		if args[2] != nil {
			arg2 = args[2].(*ConsentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_createConsent_Call) Return(consent *Consent, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_createConsent_Call {
	_c.Call.Return(consent, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_createConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, req *ConsentRequest) (*Consent, *serviceerror.ServiceError)) *consentClientInterfaceMock_createConsent_Call {
	_c.Call.Return(run)
	return _c
}

// createConsentElements provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) createConsentElements(ctx context.Context, ouID string, elements []ConsentElementInput) ([]ConsentElement, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, elements)

	if len(ret) == 0 {
		panic("no return value specified for createConsentElements")
	}

	var r0 []ConsentElement
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ConsentElementInput) ([]ConsentElement, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ConsentElementInput) []ConsentElement); ok {
		r0 = returnFunc(ctx, ouID, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConsentElement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []ConsentElementInput) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, elements)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_createConsentElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createConsentElements'
type consentClientInterfaceMock_createConsentElements_Call struct {
	*mock.Call
}

// createConsentElements is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - elements []ConsentElementInput
func (_e *consentClientInterfaceMock_Expecter) createConsentElements(ctx interface{}, ouID interface{}, elements interface{}) *consentClientInterfaceMock_createConsentElements_Call {
	return &consentClientInterfaceMock_createConsentElements_Call{Call: _e.mock.On("createConsentElements", ctx, ouID, elements)}
}

func (_c *consentClientInterfaceMock_createConsentElements_Call) Run(run func(ctx context.Context, ouID string, elements []ConsentElementInput)) *consentClientInterfaceMock_createConsentElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ConsentElementInput
		if args[2] != nil {
			arg2 = args[2].([]ConsentElementInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_createConsentElements_Call) Return(consentElements []ConsentElement, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_createConsentElements_Call {
	_c.Call.Return(consentElements, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_createConsentElements_Call) RunAndReturn(run func(ctx context.Context, ouID string, elements []ConsentElementInput) ([]ConsentElement, *serviceerror.ServiceError)) *consentClientInterfaceMock_createConsentElements_Call {
	_c.Call.Return(run)
	return _c
}

// createConsentPurpose provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) createConsentPurpose(ctx context.Context, ouID string, purpose *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for createConsentPurpose")
	}

	var r0 *ConsentPurpose
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentPurposeInput) *ConsentPurpose); ok {
		r0 = returnFunc(ctx, ouID, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsentPurpose)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *ConsentPurposeInput) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, purpose)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_createConsentPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createConsentPurpose'
type consentClientInterfaceMock_createConsentPurpose_Call struct {
	*mock.Call
}

// createConsentPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - purpose *ConsentPurposeInput
func (_e *consentClientInterfaceMock_Expecter) createConsentPurpose(ctx interface{}, ouID interface{}, purpose interface{}) *consentClientInterfaceMock_createConsentPurpose_Call {
	return &consentClientInterfaceMock_createConsentPurpose_Call{Call: _e.mock.On("createConsentPurpose", ctx, ouID, purpose)}
}

func (_c *consentClientInterfaceMock_createConsentPurpose_Call) Run(run func(ctx context.Context, ouID string, purpose *ConsentPurposeInput)) *consentClientInterfaceMock_createConsentPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ConsentPurposeInput
		if args[2] != nil {
			arg2 = args[2].(*ConsentPurposeInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_createConsentPurpose_Call) Return(consentPurpose *ConsentPurpose, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_createConsentPurpose_Call {
	_c.Call.Return(consentPurpose, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_createConsentPurpose_Call) RunAndReturn(run func(ctx context.Context, ouID string, purpose *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError)) *consentClientInterfaceMock_createConsentPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// deleteConsentElement provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) deleteConsentElement(ctx context.Context, ouID string, elementID string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, ouID, elementID)

	if len(ret) == 0 {
		panic("no return value specified for deleteConsentElement")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, ouID, elementID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// consentClientInterfaceMock_deleteConsentElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteConsentElement'
type consentClientInterfaceMock_deleteConsentElement_Call struct {
	*mock.Call
}

// deleteConsentElement is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - elementID string
func (_e *consentClientInterfaceMock_Expecter) deleteConsentElement(ctx interface{}, ouID interface{}, elementID interface{}) *consentClientInterfaceMock_deleteConsentElement_Call {
	return &consentClientInterfaceMock_deleteConsentElement_Call{Call: _e.mock.On("deleteConsentElement", ctx, ouID, elementID)}
}

func (_c *consentClientInterfaceMock_deleteConsentElement_Call) Run(run func(ctx context.Context, ouID string, elementID string)) *consentClientInterfaceMock_deleteConsentElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_deleteConsentElement_Call) Return(serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_deleteConsentElement_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_deleteConsentElement_Call) RunAndReturn(run func(ctx context.Context, ouID string, elementID string) *serviceerror.ServiceError) *consentClientInterfaceMock_deleteConsentElement_Call {
	_c.Call.Return(run)
	return _c
}

// deleteConsentPurpose provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) deleteConsentPurpose(ctx context.Context, ouID string, purposeID string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, ouID, purposeID)

	if len(ret) == 0 {
		panic("no return value specified for deleteConsentPurpose")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, ouID, purposeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// consentClientInterfaceMock_deleteConsentPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteConsentPurpose'
type consentClientInterfaceMock_deleteConsentPurpose_Call struct {
	*mock.Call
}

// deleteConsentPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - purposeID string
func (_e *consentClientInterfaceMock_Expecter) deleteConsentPurpose(ctx interface{}, ouID interface{}, purposeID interface{}) *consentClientInterfaceMock_deleteConsentPurpose_Call {
	return &consentClientInterfaceMock_deleteConsentPurpose_Call{Call: _e.mock.On("deleteConsentPurpose", ctx, ouID, purposeID)}
}

func (_c *consentClientInterfaceMock_deleteConsentPurpose_Call) Run(run func(ctx context.Context, ouID string, purposeID string)) *consentClientInterfaceMock_deleteConsentPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_deleteConsentPurpose_Call) Return(serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_deleteConsentPurpose_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_deleteConsentPurpose_Call) RunAndReturn(run func(ctx context.Context, ouID string, purposeID string) *serviceerror.ServiceError) *consentClientInterfaceMock_deleteConsentPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// listConsentElements provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) listConsentElements(ctx context.Context, ouID string, ns Namespace, nameFilter string) ([]ConsentElement, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, ns, nameFilter)

	if len(ret) == 0 {
		panic("no return value specified for listConsentElements")
	}

	var r0 []ConsentElement
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Namespace, string) ([]ConsentElement, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, ns, nameFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Namespace, string) []ConsentElement); ok {
		r0 = returnFunc(ctx, ouID, ns, nameFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConsentElement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, Namespace, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, ns, nameFilter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_listConsentElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listConsentElements'
type consentClientInterfaceMock_listConsentElements_Call struct {
	*mock.Call
}

// listConsentElements is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - ns Namespace
//   - nameFilter string
func (_e *consentClientInterfaceMock_Expecter) listConsentElements(ctx interface{}, ouID interface{}, ns interface{}, nameFilter interface{}) *consentClientInterfaceMock_listConsentElements_Call {
	return &consentClientInterfaceMock_listConsentElements_Call{Call: _e.mock.On("listConsentElements", ctx, ouID, ns, nameFilter)}
}

func (_c *consentClientInterfaceMock_listConsentElements_Call) Run(run func(ctx context.Context, ouID string, ns Namespace, nameFilter string)) *consentClientInterfaceMock_listConsentElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Namespace
		if args[2] != nil {
			arg2 = args[2].(Namespace)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_listConsentElements_Call) Return(consentElements []ConsentElement, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_listConsentElements_Call {
	_c.Call.Return(consentElements, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_listConsentElements_Call) RunAndReturn(run func(ctx context.Context, ouID string, ns Namespace, nameFilter string) ([]ConsentElement, *serviceerror.ServiceError)) *consentClientInterfaceMock_listConsentElements_Call {
	_c.Call.Return(run)
	return _c
}

// listConsentPurposes provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) listConsentPurposes(ctx context.Context, ouID string, groupID string) ([]ConsentPurpose, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for listConsentPurposes")
	}

	var r0 []ConsentPurpose
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]ConsentPurpose, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []ConsentPurpose); ok {
		r0 = returnFunc(ctx, ouID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConsentPurpose)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, groupID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_listConsentPurposes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listConsentPurposes'
type consentClientInterfaceMock_listConsentPurposes_Call struct {
	*mock.Call
}

// listConsentPurposes is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - groupID string
func (_e *consentClientInterfaceMock_Expecter) listConsentPurposes(ctx interface{}, ouID interface{}, groupID interface{}) *consentClientInterfaceMock_listConsentPurposes_Call {
	return &consentClientInterfaceMock_listConsentPurposes_Call{Call: _e.mock.On("listConsentPurposes", ctx, ouID, groupID)}
}

func (_c *consentClientInterfaceMock_listConsentPurposes_Call) Run(run func(ctx context.Context, ouID string, groupID string)) *consentClientInterfaceMock_listConsentPurposes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_listConsentPurposes_Call) Return(consentPurposes []ConsentPurpose, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_listConsentPurposes_Call {
	_c.Call.Return(consentPurposes, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_listConsentPurposes_Call) RunAndReturn(run func(ctx context.Context, ouID string, groupID string) ([]ConsentPurpose, *serviceerror.ServiceError)) *consentClientInterfaceMock_listConsentPurposes_Call {
	_c.Call.Return(run)
	return _c
}

// revokeConsent provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) revokeConsent(ctx context.Context, ouID string, consentID string, payload *ConsentRevokeRequest) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, ouID, consentID, payload)

	if len(ret) == 0 {
		panic("no return value specified for revokeConsent")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentRevokeRequest) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, ouID, consentID, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// consentClientInterfaceMock_revokeConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'revokeConsent'
type consentClientInterfaceMock_revokeConsent_Call struct {
	*mock.Call
}

// revokeConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - consentID string
//   - payload *ConsentRevokeRequest
func (_e *consentClientInterfaceMock_Expecter) revokeConsent(ctx interface{}, ouID interface{}, consentID interface{}, payload interface{}) *consentClientInterfaceMock_revokeConsent_Call {
	return &consentClientInterfaceMock_revokeConsent_Call{Call: _e.mock.On("revokeConsent", ctx, ouID, consentID, payload)}
}

func (_c *consentClientInterfaceMock_revokeConsent_Call) Run(run func(ctx context.Context, ouID string, consentID string, payload *ConsentRevokeRequest)) *consentClientInterfaceMock_revokeConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *ConsentRevokeRequest
		if args[3] != nil {
			arg3 = args[3].(*ConsentRevokeRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_revokeConsent_Call) Return(serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_revokeConsent_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_revokeConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, consentID string, payload *ConsentRevokeRequest) *serviceerror.ServiceError) *consentClientInterfaceMock_revokeConsent_Call {
	_c.Call.Return(run)
	return _c
}

// searchConsents provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) searchConsents(ctx context.Context, ouID string, filter *ConsentSearchFilter) ([]Consent, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, filter)

	if len(ret) == 0 {
		panic("no return value specified for searchConsents")
	}

	var r0 []Consent
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentSearchFilter) ([]Consent, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ConsentSearchFilter) []Consent); ok {
		r0 = returnFunc(ctx, ouID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Consent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *ConsentSearchFilter) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_searchConsents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'searchConsents'
type consentClientInterfaceMock_searchConsents_Call struct {
	*mock.Call
}

// searchConsents is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - filter *ConsentSearchFilter
func (_e *consentClientInterfaceMock_Expecter) searchConsents(ctx interface{}, ouID interface{}, filter interface{}) *consentClientInterfaceMock_searchConsents_Call {
	return &consentClientInterfaceMock_searchConsents_Call{Call: _e.mock.On("searchConsents", ctx, ouID, filter)}
}

func (_c *consentClientInterfaceMock_searchConsents_Call) Run(run func(ctx context.Context, ouID string, filter *ConsentSearchFilter)) *consentClientInterfaceMock_searchConsents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ConsentSearchFilter
		if args[2] != nil {
			arg2 = args[2].(*ConsentSearchFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_searchConsents_Call) Return(consents []Consent, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_searchConsents_Call {
	_c.Call.Return(consents, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_searchConsents_Call) RunAndReturn(run func(ctx context.Context, ouID string, filter *ConsentSearchFilter) ([]Consent, *serviceerror.ServiceError)) *consentClientInterfaceMock_searchConsents_Call {
	_c.Call.Return(run)
	return _c
}

// updateConsent provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) updateConsent(ctx context.Context, ouID string, consentID string, req *ConsentRequest) (*Consent, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, consentID, req)

	if len(ret) == 0 {
		panic("no return value specified for updateConsent")
	}

	var r0 *Consent
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentRequest) (*Consent, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, consentID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentRequest) *Consent); ok {
		r0 = returnFunc(ctx, ouID, consentID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Consent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *ConsentRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, consentID, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_updateConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'updateConsent'
type consentClientInterfaceMock_updateConsent_Call struct {
	*mock.Call
}

// updateConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - consentID string
//   - req *ConsentRequest
func (_e *consentClientInterfaceMock_Expecter) updateConsent(ctx interface{}, ouID interface{}, consentID interface{}, req interface{}) *consentClientInterfaceMock_updateConsent_Call {
	return &consentClientInterfaceMock_updateConsent_Call{Call: _e.mock.On("updateConsent", ctx, ouID, consentID, req)}
}

func (_c *consentClientInterfaceMock_updateConsent_Call) Run(run func(ctx context.Context, ouID string, consentID string, req *ConsentRequest)) *consentClientInterfaceMock_updateConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *ConsentRequest
		if args[3] != nil {
			arg3 = args[3].(*ConsentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_updateConsent_Call) Return(consent *Consent, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_updateConsent_Call {
	_c.Call.Return(consent, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_updateConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, consentID string, req *ConsentRequest) (*Consent, *serviceerror.ServiceError)) *consentClientInterfaceMock_updateConsent_Call {
	_c.Call.Return(run)
	return _c
}

// updateConsentElement provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) updateConsentElement(ctx context.Context, ouID string, elementID string, element *ConsentElementInput) (*ConsentElement, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, elementID, element)

	if len(ret) == 0 {
		panic("no return value specified for updateConsentElement")
	}

	var r0 *ConsentElement
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentElementInput) (*ConsentElement, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, elementID, element)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentElementInput) *ConsentElement); ok {
		r0 = returnFunc(ctx, ouID, elementID, element)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsentElement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *ConsentElementInput) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, elementID, element)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_updateConsentElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'updateConsentElement'
type consentClientInterfaceMock_updateConsentElement_Call struct {
	*mock.Call
}

// updateConsentElement is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - elementID string
//   - element *ConsentElementInput
func (_e *consentClientInterfaceMock_Expecter) updateConsentElement(ctx interface{}, ouID interface{}, elementID interface{}, element interface{}) *consentClientInterfaceMock_updateConsentElement_Call {
	return &consentClientInterfaceMock_updateConsentElement_Call{Call: _e.mock.On("updateConsentElement", ctx, ouID, elementID, element)}
}

func (_c *consentClientInterfaceMock_updateConsentElement_Call) Run(run func(ctx context.Context, ouID string, elementID string, element *ConsentElementInput)) *consentClientInterfaceMock_updateConsentElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *ConsentElementInput
		if args[3] != nil {
			arg3 = args[3].(*ConsentElementInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_updateConsentElement_Call) Return(consentElement *ConsentElement, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_updateConsentElement_Call {
	_c.Call.Return(consentElement, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_updateConsentElement_Call) RunAndReturn(run func(ctx context.Context, ouID string, elementID string, element *ConsentElementInput) (*ConsentElement, *serviceerror.ServiceError)) *consentClientInterfaceMock_updateConsentElement_Call {
	_c.Call.Return(run)
	return _c
}

// updateConsentPurpose provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) updateConsentPurpose(ctx context.Context, ouID string, purposeID string, purpose *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, purposeID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for updateConsentPurpose")
	}

	var r0 *ConsentPurpose
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, purposeID, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ConsentPurposeInput) *ConsentPurpose); ok {
		r0 = returnFunc(ctx, ouID, purposeID, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsentPurpose)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *ConsentPurposeInput) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, purposeID, purpose)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_updateConsentPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'updateConsentPurpose'
type consentClientInterfaceMock_updateConsentPurpose_Call struct {
	*mock.Call
}

// updateConsentPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - purposeID string
//   - purpose *ConsentPurposeInput
func (_e *consentClientInterfaceMock_Expecter) updateConsentPurpose(ctx interface{}, ouID interface{}, purposeID interface{}, purpose interface{}) *consentClientInterfaceMock_updateConsentPurpose_Call {
	return &consentClientInterfaceMock_updateConsentPurpose_Call{Call: _e.mock.On("updateConsentPurpose", ctx, ouID, purposeID, purpose)}
}

func (_c *consentClientInterfaceMock_updateConsentPurpose_Call) Run(run func(ctx context.Context, ouID string, purposeID string, purpose *ConsentPurposeInput)) *consentClientInterfaceMock_updateConsentPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *ConsentPurposeInput
		if args[3] != nil {
			arg3 = args[3].(*ConsentPurposeInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_updateConsentPurpose_Call) Return(consentPurpose *ConsentPurpose, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_updateConsentPurpose_Call {
	_c.Call.Return(consentPurpose, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_updateConsentPurpose_Call) RunAndReturn(run func(ctx context.Context, ouID string, purposeID string, purpose *ConsentPurposeInput) (*ConsentPurpose, *serviceerror.ServiceError)) *consentClientInterfaceMock_updateConsentPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// validateConsent provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) validateConsent(ctx context.Context, ouID string, consentID string) (*ConsentValidationResult, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, consentID)

	if len(ret) == 0 {
		panic("no return value specified for validateConsent")
	}

	var r0 *ConsentValidationResult
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ConsentValidationResult, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, consentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ConsentValidationResult); ok {
		r0 = returnFunc(ctx, ouID, consentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsentValidationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, consentID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_validateConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validateConsent'
type consentClientInterfaceMock_validateConsent_Call struct {
	*mock.Call
}

// validateConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - consentID string
func (_e *consentClientInterfaceMock_Expecter) validateConsent(ctx interface{}, ouID interface{}, consentID interface{}) *consentClientInterfaceMock_validateConsent_Call {
	return &consentClientInterfaceMock_validateConsent_Call{Call: _e.mock.On("validateConsent", ctx, ouID, consentID)}
}

func (_c *consentClientInterfaceMock_validateConsent_Call) Run(run func(ctx context.Context, ouID string, consentID string)) *consentClientInterfaceMock_validateConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_validateConsent_Call) Return(consentValidationResult *ConsentValidationResult, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_validateConsent_Call {
	_c.Call.Return(consentValidationResult, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_validateConsent_Call) RunAndReturn(run func(ctx context.Context, ouID string, consentID string) (*ConsentValidationResult, *serviceerror.ServiceError)) *consentClientInterfaceMock_validateConsent_Call {
	_c.Call.Return(run)
	return _c
}

// validateConsentElements provides a mock function for the type consentClientInterfaceMock
func (_mock *consentClientInterfaceMock) validateConsentElements(ctx context.Context, ouID string, names []string) ([]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, ouID, names)

	if len(ret) == 0 {
		panic("no return value specified for validateConsentElements")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, ouID, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, ouID, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// consentClientInterfaceMock_validateConsentElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validateConsentElements'
type consentClientInterfaceMock_validateConsentElements_Call struct {
	*mock.Call
}

// validateConsentElements is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - names []string
func (_e *consentClientInterfaceMock_Expecter) validateConsentElements(ctx interface{}, ouID interface{}, names interface{}) *consentClientInterfaceMock_validateConsentElements_Call {
	return &consentClientInterfaceMock_validateConsentElements_Call{Call: _e.mock.On("validateConsentElements", ctx, ouID, names)}
}

func (_c *consentClientInterfaceMock_validateConsentElements_Call) Run(run func(ctx context.Context, ouID string, names []string)) *consentClientInterfaceMock_validateConsentElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *consentClientInterfaceMock_validateConsentElements_Call) Return(strings []string, serviceError *serviceerror.ServiceError) *consentClientInterfaceMock_validateConsentElements_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *consentClientInterfaceMock_validateConsentElements_Call) RunAndReturn(run func(ctx context.Context, ouID string, names []string) ([]string, *serviceerror.ServiceError)) *consentClientInterfaceMock_validateConsentElements_Call {
	_c.Call.Return(run)
	return _c
}
