// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entitymock

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/entity"
)

// NewEntityServiceInterfaceMock creates a new instance of EntityServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityServiceInterfaceMock {
	mock := &EntityServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntityServiceInterfaceMock is an autogenerated mock type for the EntityServiceInterface type
type EntityServiceInterfaceMock struct {
	mock.Mock
}

type EntityServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EntityServiceInterfaceMock) EXPECT() *EntityServiceInterfaceMock_Expecter {
	return &EntityServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// AuthenticateEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) AuthenticateEntity(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{}) (*entity.AuthenticateResult, error) {
	ret := _mock.Called(ctx, identifiers, credentials)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateEntity")
	}

	var r0 *entity.AuthenticateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}, map[string]interface{}) (*entity.AuthenticateResult, error)); ok {
		return returnFunc(ctx, identifiers, credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}, map[string]interface{}) *entity.AuthenticateResult); ok {
		r0 = returnFunc(ctx, identifiers, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthenticateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, identifiers, credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_AuthenticateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateEntity'
type EntityServiceInterfaceMock_AuthenticateEntity_Call struct {
	*mock.Call
}

// AuthenticateEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - identifiers map[string]interface{}
//   - credentials map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) AuthenticateEntity(ctx interface{}, identifiers interface{}, credentials interface{}) *EntityServiceInterfaceMock_AuthenticateEntity_Call {
	return &EntityServiceInterfaceMock_AuthenticateEntity_Call{Call: _e.mock.On("AuthenticateEntity", ctx, identifiers, credentials)}
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntity_Call) Run(run func(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{})) *EntityServiceInterfaceMock_AuthenticateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntity_Call) Return(authenticateResult *entity.AuthenticateResult, err error) *EntityServiceInterfaceMock_AuthenticateEntity_Call {
	_c.Call.Return(authenticateResult, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntity_Call) RunAndReturn(run func(ctx context.Context, identifiers map[string]interface{}, credentials map[string]interface{}) (*entity.AuthenticateResult, error)) *EntityServiceInterfaceMock_AuthenticateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateEntityByID provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) AuthenticateEntityByID(ctx context.Context, entityID string, credentials map[string]interface{}) (*entity.AuthenticateResult, error) {
	ret := _mock.Called(ctx, entityID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateEntityByID")
	}

	var r0 *entity.AuthenticateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (*entity.AuthenticateResult, error)); ok {
		return returnFunc(ctx, entityID, credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) *entity.AuthenticateResult); ok {
		r0 = returnFunc(ctx, entityID, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthenticateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, entityID, credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_AuthenticateEntityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateEntityByID'
type EntityServiceInterfaceMock_AuthenticateEntityByID_Call struct {
	*mock.Call
}

// AuthenticateEntityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - credentials map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) AuthenticateEntityByID(ctx interface{}, entityID interface{}, credentials interface{}) *EntityServiceInterfaceMock_AuthenticateEntityByID_Call {
	return &EntityServiceInterfaceMock_AuthenticateEntityByID_Call{Call: _e.mock.On("AuthenticateEntityByID", ctx, entityID, credentials)}
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntityByID_Call) Run(run func(ctx context.Context, entityID string, credentials map[string]interface{})) *EntityServiceInterfaceMock_AuthenticateEntityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntityByID_Call) Return(authenticateResult *entity.AuthenticateResult, err error) *EntityServiceInterfaceMock_AuthenticateEntityByID_Call {
	_c.Call.Return(authenticateResult, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_AuthenticateEntityByID_Call) RunAndReturn(run func(ctx context.Context, entityID string, credentials map[string]interface{}) (*entity.AuthenticateResult, error)) *EntityServiceInterfaceMock_AuthenticateEntityByID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) CreateEntity(ctx context.Context, entity1 *entity.Entity, systemCredentials json.RawMessage) (*entity.Entity, error) {
	ret := _mock.Called(ctx, entity1, systemCredentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntity")
	}

	var r0 *entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Entity, json.RawMessage) (*entity.Entity, error)); ok {
		return returnFunc(ctx, entity1, systemCredentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Entity, json.RawMessage) *entity.Entity); ok {
		r0 = returnFunc(ctx, entity1, systemCredentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Entity, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, entity1, systemCredentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_CreateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntity'
type EntityServiceInterfaceMock_CreateEntity_Call struct {
	*mock.Call
}

// CreateEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entity1 *entity.Entity
//   - systemCredentials json.RawMessage
func (_e *EntityServiceInterfaceMock_Expecter) CreateEntity(ctx interface{}, entity1 interface{}, systemCredentials interface{}) *EntityServiceInterfaceMock_CreateEntity_Call {
	return &EntityServiceInterfaceMock_CreateEntity_Call{Call: _e.mock.On("CreateEntity", ctx, entity1, systemCredentials)}
}

func (_c *EntityServiceInterfaceMock_CreateEntity_Call) Run(run func(ctx context.Context, entity1 *entity.Entity, systemCredentials json.RawMessage)) *EntityServiceInterfaceMock_CreateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Entity
		if args[1] != nil {
			arg1 = args[1].(*entity.Entity)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_CreateEntity_Call) Return(entity11 *entity.Entity, err error) *EntityServiceInterfaceMock_CreateEntity_Call {
	_c.Call.Return(entity11, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_CreateEntity_Call) RunAndReturn(run func(ctx context.Context, entity1 *entity.Entity, systemCredentials json.RawMessage) (*entity.Entity, error)) *EntityServiceInterfaceMock_CreateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) DeleteEntity(ctx context.Context, entityID string) error {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_DeleteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntity'
type EntityServiceInterfaceMock_DeleteEntity_Call struct {
	*mock.Call
}

// DeleteEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *EntityServiceInterfaceMock_Expecter) DeleteEntity(ctx interface{}, entityID interface{}) *EntityServiceInterfaceMock_DeleteEntity_Call {
	return &EntityServiceInterfaceMock_DeleteEntity_Call{Call: _e.mock.On("DeleteEntity", ctx, entityID)}
}

func (_c *EntityServiceInterfaceMock_DeleteEntity_Call) Run(run func(ctx context.Context, entityID string)) *EntityServiceInterfaceMock_DeleteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_DeleteEntity_Call) Return(err error) *EntityServiceInterfaceMock_DeleteEntity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_DeleteEntity_Call) RunAndReturn(run func(ctx context.Context, entityID string) error) *EntityServiceInterfaceMock_DeleteEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialsByType provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetCredentialsByType(ctx context.Context, entityID string, credType string) ([]entity.StoredCredential, error) {
	ret := _mock.Called(ctx, entityID, credType)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsByType")
	}

	var r0 []entity.StoredCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.StoredCredential, error)); ok {
		return returnFunc(ctx, entityID, credType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.StoredCredential); ok {
		r0 = returnFunc(ctx, entityID, credType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.StoredCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, entityID, credType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetCredentialsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialsByType'
type EntityServiceInterfaceMock_GetCredentialsByType_Call struct {
	*mock.Call
}

// GetCredentialsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - credType string
func (_e *EntityServiceInterfaceMock_Expecter) GetCredentialsByType(ctx interface{}, entityID interface{}, credType interface{}) *EntityServiceInterfaceMock_GetCredentialsByType_Call {
	return &EntityServiceInterfaceMock_GetCredentialsByType_Call{Call: _e.mock.On("GetCredentialsByType", ctx, entityID, credType)}
}

func (_c *EntityServiceInterfaceMock_GetCredentialsByType_Call) Run(run func(ctx context.Context, entityID string, credType string)) *EntityServiceInterfaceMock_GetCredentialsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetCredentialsByType_Call) Return(storedCredentials []entity.StoredCredential, err error) *EntityServiceInterfaceMock_GetCredentialsByType_Call {
	_c.Call.Return(storedCredentials, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetCredentialsByType_Call) RunAndReturn(run func(ctx context.Context, entityID string, credType string) ([]entity.StoredCredential, error)) *EntityServiceInterfaceMock_GetCredentialsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntitiesByIDs provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntitiesByIDs(ctx context.Context, entityIDs []string) ([]entity.Entity, error) {
	ret := _mock.Called(ctx, entityIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetEntitiesByIDs")
	}

	var r0 []entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]entity.Entity, error)); ok {
		return returnFunc(ctx, entityIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []entity.Entity); ok {
		r0 = returnFunc(ctx, entityIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, entityIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntitiesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntitiesByIDs'
type EntityServiceInterfaceMock_GetEntitiesByIDs_Call struct {
	*mock.Call
}

// GetEntitiesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - entityIDs []string
func (_e *EntityServiceInterfaceMock_Expecter) GetEntitiesByIDs(ctx interface{}, entityIDs interface{}) *EntityServiceInterfaceMock_GetEntitiesByIDs_Call {
	return &EntityServiceInterfaceMock_GetEntitiesByIDs_Call{Call: _e.mock.On("GetEntitiesByIDs", ctx, entityIDs)}
}

func (_c *EntityServiceInterfaceMock_GetEntitiesByIDs_Call) Run(run func(ctx context.Context, entityIDs []string)) *EntityServiceInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntitiesByIDs_Call) Return(entitys []entity.Entity, err error) *EntityServiceInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntitiesByIDs_Call) RunAndReturn(run func(ctx context.Context, entityIDs []string) ([]entity.Entity, error)) *EntityServiceInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntity(ctx context.Context, entityID string) (*entity.Entity, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntity")
	}

	var r0 *entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Entity, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Entity); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntity'
type EntityServiceInterfaceMock_GetEntity_Call struct {
	*mock.Call
}

// GetEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *EntityServiceInterfaceMock_Expecter) GetEntity(ctx interface{}, entityID interface{}) *EntityServiceInterfaceMock_GetEntity_Call {
	return &EntityServiceInterfaceMock_GetEntity_Call{Call: _e.mock.On("GetEntity", ctx, entityID)}
}

func (_c *EntityServiceInterfaceMock_GetEntity_Call) Run(run func(ctx context.Context, entityID string)) *EntityServiceInterfaceMock_GetEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntity_Call) Return(entity1 *entity.Entity, err error) *EntityServiceInterfaceMock_GetEntity_Call {
	_c.Call.Return(entity1, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntity_Call) RunAndReturn(run func(ctx context.Context, entityID string) (*entity.Entity, error)) *EntityServiceInterfaceMock_GetEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityGroups provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntityGroups(ctx context.Context, entityID string, limit int, offset int) ([]entity.EntityGroup, error) {
	ret := _mock.Called(ctx, entityID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityGroups")
	}

	var r0 []entity.EntityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.EntityGroup, error)); ok {
		return returnFunc(ctx, entityID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.EntityGroup); ok {
		r0 = returnFunc(ctx, entityID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EntityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, entityID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityGroups'
type EntityServiceInterfaceMock_GetEntityGroups_Call struct {
	*mock.Call
}

// GetEntityGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - limit int
//   - offset int
func (_e *EntityServiceInterfaceMock_Expecter) GetEntityGroups(ctx interface{}, entityID interface{}, limit interface{}, offset interface{}) *EntityServiceInterfaceMock_GetEntityGroups_Call {
	return &EntityServiceInterfaceMock_GetEntityGroups_Call{Call: _e.mock.On("GetEntityGroups", ctx, entityID, limit, offset)}
}

func (_c *EntityServiceInterfaceMock_GetEntityGroups_Call) Run(run func(ctx context.Context, entityID string, limit int, offset int)) *EntityServiceInterfaceMock_GetEntityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityGroups_Call) Return(entityGroups []entity.EntityGroup, err error) *EntityServiceInterfaceMock_GetEntityGroups_Call {
	_c.Call.Return(entityGroups, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityGroups_Call) RunAndReturn(run func(ctx context.Context, entityID string, limit int, offset int) ([]entity.EntityGroup, error)) *EntityServiceInterfaceMock_GetEntityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityList provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntityList(ctx context.Context, category entity.EntityCategory, limit int, offset int, filters map[string]interface{}) ([]entity.Entity, error) {
	ret := _mock.Called(ctx, category, limit, offset, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityList")
	}

	var r0 []entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, int, int, map[string]interface{}) ([]entity.Entity, error)); ok {
		return returnFunc(ctx, category, limit, offset, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, int, int, map[string]interface{}) []entity.Entity); ok {
		r0 = returnFunc(ctx, category, limit, offset, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntityCategory, int, int, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, category, limit, offset, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntityList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityList'
type EntityServiceInterfaceMock_GetEntityList_Call struct {
	*mock.Call
}

// GetEntityList is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.EntityCategory
//   - limit int
//   - offset int
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) GetEntityList(ctx interface{}, category interface{}, limit interface{}, offset interface{}, filters interface{}) *EntityServiceInterfaceMock_GetEntityList_Call {
	return &EntityServiceInterfaceMock_GetEntityList_Call{Call: _e.mock.On("GetEntityList", ctx, category, limit, offset, filters)}
}

func (_c *EntityServiceInterfaceMock_GetEntityList_Call) Run(run func(ctx context.Context, category entity.EntityCategory, limit int, offset int, filters map[string]interface{})) *EntityServiceInterfaceMock_GetEntityList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntityCategory
		if args[1] != nil {
			arg1 = args[1].(entity.EntityCategory)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityList_Call) Return(entitys []entity.Entity, err error) *EntityServiceInterfaceMock_GetEntityList_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityList_Call) RunAndReturn(run func(ctx context.Context, category entity.EntityCategory, limit int, offset int, filters map[string]interface{}) ([]entity.Entity, error)) *EntityServiceInterfaceMock_GetEntityList_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityListByOUIDs provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntityListByOUIDs(ctx context.Context, category entity.EntityCategory, ouIDs []string, limit int, offset int, filters map[string]interface{}) ([]entity.Entity, error) {
	ret := _mock.Called(ctx, category, ouIDs, limit, offset, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityListByOUIDs")
	}

	var r0 []entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, []string, int, int, map[string]interface{}) ([]entity.Entity, error)); ok {
		return returnFunc(ctx, category, ouIDs, limit, offset, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, []string, int, int, map[string]interface{}) []entity.Entity); ok {
		r0 = returnFunc(ctx, category, ouIDs, limit, offset, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntityCategory, []string, int, int, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, category, ouIDs, limit, offset, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntityListByOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityListByOUIDs'
type EntityServiceInterfaceMock_GetEntityListByOUIDs_Call struct {
	*mock.Call
}

// GetEntityListByOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.EntityCategory
//   - ouIDs []string
//   - limit int
//   - offset int
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) GetEntityListByOUIDs(ctx interface{}, category interface{}, ouIDs interface{}, limit interface{}, offset interface{}, filters interface{}) *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call {
	return &EntityServiceInterfaceMock_GetEntityListByOUIDs_Call{Call: _e.mock.On("GetEntityListByOUIDs", ctx, category, ouIDs, limit, offset, filters)}
}

func (_c *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call) Run(run func(ctx context.Context, category entity.EntityCategory, ouIDs []string, limit int, offset int, filters map[string]interface{})) *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntityCategory
		if args[1] != nil {
			arg1 = args[1].(entity.EntityCategory)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 map[string]interface{}
		if args[5] != nil {
			arg5 = args[5].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call) Return(entitys []entity.Entity, err error) *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call) RunAndReturn(run func(ctx context.Context, category entity.EntityCategory, ouIDs []string, limit int, offset int, filters map[string]interface{}) ([]entity.Entity, error)) *EntityServiceInterfaceMock_GetEntityListByOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityListCount provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntityListCount(ctx context.Context, category entity.EntityCategory, filters map[string]interface{}) (int, error) {
	ret := _mock.Called(ctx, category, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, map[string]interface{}) (int, error)); ok {
		return returnFunc(ctx, category, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, map[string]interface{}) int); ok {
		r0 = returnFunc(ctx, category, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntityCategory, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, category, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntityListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityListCount'
type EntityServiceInterfaceMock_GetEntityListCount_Call struct {
	*mock.Call
}

// GetEntityListCount is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.EntityCategory
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) GetEntityListCount(ctx interface{}, category interface{}, filters interface{}) *EntityServiceInterfaceMock_GetEntityListCount_Call {
	return &EntityServiceInterfaceMock_GetEntityListCount_Call{Call: _e.mock.On("GetEntityListCount", ctx, category, filters)}
}

func (_c *EntityServiceInterfaceMock_GetEntityListCount_Call) Run(run func(ctx context.Context, category entity.EntityCategory, filters map[string]interface{})) *EntityServiceInterfaceMock_GetEntityListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntityCategory
		if args[1] != nil {
			arg1 = args[1].(entity.EntityCategory)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListCount_Call) Return(n int, err error) *EntityServiceInterfaceMock_GetEntityListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListCount_Call) RunAndReturn(run func(ctx context.Context, category entity.EntityCategory, filters map[string]interface{}) (int, error)) *EntityServiceInterfaceMock_GetEntityListCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityListCountByOUIDs provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetEntityListCountByOUIDs(ctx context.Context, category entity.EntityCategory, ouIDs []string, filters map[string]interface{}) (int, error) {
	ret := _mock.Called(ctx, category, ouIDs, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityListCountByOUIDs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, []string, map[string]interface{}) (int, error)); ok {
		return returnFunc(ctx, category, ouIDs, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntityCategory, []string, map[string]interface{}) int); ok {
		r0 = returnFunc(ctx, category, ouIDs, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntityCategory, []string, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, category, ouIDs, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityListCountByOUIDs'
type EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call struct {
	*mock.Call
}

// GetEntityListCountByOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.EntityCategory
//   - ouIDs []string
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) GetEntityListCountByOUIDs(ctx interface{}, category interface{}, ouIDs interface{}, filters interface{}) *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call {
	return &EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call{Call: _e.mock.On("GetEntityListCountByOUIDs", ctx, category, ouIDs, filters)}
}

func (_c *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call) Run(run func(ctx context.Context, category entity.EntityCategory, ouIDs []string, filters map[string]interface{})) *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntityCategory
		if args[1] != nil {
			arg1 = args[1].(entity.EntityCategory)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call) Return(n int, err error) *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call) RunAndReturn(run func(ctx context.Context, category entity.EntityCategory, ouIDs []string, filters map[string]interface{}) (int, error)) *EntityServiceInterfaceMock_GetEntityListCountByOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupCountForEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetGroupCountForEntity(ctx context.Context, entityID string) (int, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupCountForEntity")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetGroupCountForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupCountForEntity'
type EntityServiceInterfaceMock_GetGroupCountForEntity_Call struct {
	*mock.Call
}

// GetGroupCountForEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *EntityServiceInterfaceMock_Expecter) GetGroupCountForEntity(ctx interface{}, entityID interface{}) *EntityServiceInterfaceMock_GetGroupCountForEntity_Call {
	return &EntityServiceInterfaceMock_GetGroupCountForEntity_Call{Call: _e.mock.On("GetGroupCountForEntity", ctx, entityID)}
}

func (_c *EntityServiceInterfaceMock_GetGroupCountForEntity_Call) Run(run func(ctx context.Context, entityID string)) *EntityServiceInterfaceMock_GetGroupCountForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetGroupCountForEntity_Call) Return(n int, err error) *EntityServiceInterfaceMock_GetGroupCountForEntity_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetGroupCountForEntity_Call) RunAndReturn(run func(ctx context.Context, entityID string) (int, error)) *EntityServiceInterfaceMock_GetGroupCountForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitiveEntityGroups provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) GetTransitiveEntityGroups(ctx context.Context, entityID string) ([]entity.EntityGroup, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitiveEntityGroups")
	}

	var r0 []entity.EntityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.EntityGroup, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.EntityGroup); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EntityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitiveEntityGroups'
type EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call struct {
	*mock.Call
}

// GetTransitiveEntityGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *EntityServiceInterfaceMock_Expecter) GetTransitiveEntityGroups(ctx interface{}, entityID interface{}) *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call {
	return &EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call{Call: _e.mock.On("GetTransitiveEntityGroups", ctx, entityID)}
}

func (_c *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call) Run(run func(ctx context.Context, entityID string)) *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call) Return(entityGroups []entity.EntityGroup, err error) *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Return(entityGroups, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call) RunAndReturn(run func(ctx context.Context, entityID string) ([]entity.EntityGroup, error)) *EntityServiceInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) IdentifyEntity(ctx context.Context, filters map[string]interface{}) (*string, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyEntity")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (*string, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) *string); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_IdentifyEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyEntity'
type EntityServiceInterfaceMock_IdentifyEntity_Call struct {
	*mock.Call
}

// IdentifyEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) IdentifyEntity(ctx interface{}, filters interface{}) *EntityServiceInterfaceMock_IdentifyEntity_Call {
	return &EntityServiceInterfaceMock_IdentifyEntity_Call{Call: _e.mock.On("IdentifyEntity", ctx, filters)}
}

func (_c *EntityServiceInterfaceMock_IdentifyEntity_Call) Run(run func(ctx context.Context, filters map[string]interface{})) *EntityServiceInterfaceMock_IdentifyEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_IdentifyEntity_Call) Return(s *string, err error) *EntityServiceInterfaceMock_IdentifyEntity_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_IdentifyEntity_Call) RunAndReturn(run func(ctx context.Context, filters map[string]interface{}) (*string, error)) *EntityServiceInterfaceMock_IdentifyEntity_Call {
	_c.Call.Return(run)
	return _c
}

// IsEntityDeclarative provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) IsEntityDeclarative(ctx context.Context, entityID string) (bool, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for IsEntityDeclarative")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_IsEntityDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEntityDeclarative'
type EntityServiceInterfaceMock_IsEntityDeclarative_Call struct {
	*mock.Call
}

// IsEntityDeclarative is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *EntityServiceInterfaceMock_Expecter) IsEntityDeclarative(ctx interface{}, entityID interface{}) *EntityServiceInterfaceMock_IsEntityDeclarative_Call {
	return &EntityServiceInterfaceMock_IsEntityDeclarative_Call{Call: _e.mock.On("IsEntityDeclarative", ctx, entityID)}
}

func (_c *EntityServiceInterfaceMock_IsEntityDeclarative_Call) Run(run func(ctx context.Context, entityID string)) *EntityServiceInterfaceMock_IsEntityDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_IsEntityDeclarative_Call) Return(b bool, err error) *EntityServiceInterfaceMock_IsEntityDeclarative_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_IsEntityDeclarative_Call) RunAndReturn(run func(ctx context.Context, entityID string) (bool, error)) *EntityServiceInterfaceMock_IsEntityDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// LoadDeclarativeResources provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) LoadDeclarativeResources(config entity.DeclarativeLoaderConfig) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for LoadDeclarativeResources")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(entity.DeclarativeLoaderConfig) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_LoadDeclarativeResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadDeclarativeResources'
type EntityServiceInterfaceMock_LoadDeclarativeResources_Call struct {
	*mock.Call
}

// LoadDeclarativeResources is a helper method to define mock.On call
//   - config entity.DeclarativeLoaderConfig
func (_e *EntityServiceInterfaceMock_Expecter) LoadDeclarativeResources(config interface{}) *EntityServiceInterfaceMock_LoadDeclarativeResources_Call {
	return &EntityServiceInterfaceMock_LoadDeclarativeResources_Call{Call: _e.mock.On("LoadDeclarativeResources", config)}
}

func (_c *EntityServiceInterfaceMock_LoadDeclarativeResources_Call) Run(run func(config entity.DeclarativeLoaderConfig)) *EntityServiceInterfaceMock_LoadDeclarativeResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.DeclarativeLoaderConfig
		if args[0] != nil {
			arg0 = args[0].(entity.DeclarativeLoaderConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_LoadDeclarativeResources_Call) Return(err error) *EntityServiceInterfaceMock_LoadDeclarativeResources_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_LoadDeclarativeResources_Call) RunAndReturn(run func(config entity.DeclarativeLoaderConfig) error) *EntityServiceInterfaceMock_LoadDeclarativeResources_Call {
	_c.Call.Return(run)
	return _c
}

// LoadIndexedAttributes provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) LoadIndexedAttributes(attributes []string) error {
	ret := _mock.Called(attributes)

	if len(ret) == 0 {
		panic("no return value specified for LoadIndexedAttributes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(attributes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_LoadIndexedAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadIndexedAttributes'
type EntityServiceInterfaceMock_LoadIndexedAttributes_Call struct {
	*mock.Call
}

// LoadIndexedAttributes is a helper method to define mock.On call
//   - attributes []string
func (_e *EntityServiceInterfaceMock_Expecter) LoadIndexedAttributes(attributes interface{}) *EntityServiceInterfaceMock_LoadIndexedAttributes_Call {
	return &EntityServiceInterfaceMock_LoadIndexedAttributes_Call{Call: _e.mock.On("LoadIndexedAttributes", attributes)}
}

func (_c *EntityServiceInterfaceMock_LoadIndexedAttributes_Call) Run(run func(attributes []string)) *EntityServiceInterfaceMock_LoadIndexedAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_LoadIndexedAttributes_Call) Return(err error) *EntityServiceInterfaceMock_LoadIndexedAttributes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_LoadIndexedAttributes_Call) RunAndReturn(run func(attributes []string) error) *EntityServiceInterfaceMock_LoadIndexedAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// SearchEntities provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) SearchEntities(ctx context.Context, filters map[string]interface{}) ([]entity.Entity, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchEntities")
	}

	var r0 []entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]entity.Entity, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []entity.Entity); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_SearchEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchEntities'
type EntityServiceInterfaceMock_SearchEntities_Call struct {
	*mock.Call
}

// SearchEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]interface{}
func (_e *EntityServiceInterfaceMock_Expecter) SearchEntities(ctx interface{}, filters interface{}) *EntityServiceInterfaceMock_SearchEntities_Call {
	return &EntityServiceInterfaceMock_SearchEntities_Call{Call: _e.mock.On("SearchEntities", ctx, filters)}
}

func (_c *EntityServiceInterfaceMock_SearchEntities_Call) Run(run func(ctx context.Context, filters map[string]interface{})) *EntityServiceInterfaceMock_SearchEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_SearchEntities_Call) Return(entitys []entity.Entity, err error) *EntityServiceInterfaceMock_SearchEntities_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_SearchEntities_Call) RunAndReturn(run func(ctx context.Context, filters map[string]interface{}) ([]entity.Entity, error)) *EntityServiceInterfaceMock_SearchEntities_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttributes provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) UpdateAttributes(ctx context.Context, entityID string, attributes json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, attributes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttributes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, attributes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_UpdateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttributes'
type EntityServiceInterfaceMock_UpdateAttributes_Call struct {
	*mock.Call
}

// UpdateAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - attributes json.RawMessage
func (_e *EntityServiceInterfaceMock_Expecter) UpdateAttributes(ctx interface{}, entityID interface{}, attributes interface{}) *EntityServiceInterfaceMock_UpdateAttributes_Call {
	return &EntityServiceInterfaceMock_UpdateAttributes_Call{Call: _e.mock.On("UpdateAttributes", ctx, entityID, attributes)}
}

func (_c *EntityServiceInterfaceMock_UpdateAttributes_Call) Run(run func(ctx context.Context, entityID string, attributes json.RawMessage)) *EntityServiceInterfaceMock_UpdateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateAttributes_Call) Return(err error) *EntityServiceInterfaceMock_UpdateAttributes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateAttributes_Call) RunAndReturn(run func(ctx context.Context, entityID string, attributes json.RawMessage) error) *EntityServiceInterfaceMock_UpdateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCredentials provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) UpdateCredentials(ctx context.Context, entityID string, plaintextUpdates json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, plaintextUpdates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredentials")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, plaintextUpdates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_UpdateCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCredentials'
type EntityServiceInterfaceMock_UpdateCredentials_Call struct {
	*mock.Call
}

// UpdateCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - plaintextUpdates json.RawMessage
func (_e *EntityServiceInterfaceMock_Expecter) UpdateCredentials(ctx interface{}, entityID interface{}, plaintextUpdates interface{}) *EntityServiceInterfaceMock_UpdateCredentials_Call {
	return &EntityServiceInterfaceMock_UpdateCredentials_Call{Call: _e.mock.On("UpdateCredentials", ctx, entityID, plaintextUpdates)}
}

func (_c *EntityServiceInterfaceMock_UpdateCredentials_Call) Run(run func(ctx context.Context, entityID string, plaintextUpdates json.RawMessage)) *EntityServiceInterfaceMock_UpdateCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateCredentials_Call) Return(err error) *EntityServiceInterfaceMock_UpdateCredentials_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateCredentials_Call) RunAndReturn(run func(ctx context.Context, entityID string, plaintextUpdates json.RawMessage) error) *EntityServiceInterfaceMock_UpdateCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntity provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) UpdateEntity(ctx context.Context, entityID string, entity1 *entity.Entity) (*entity.Entity, error) {
	ret := _mock.Called(ctx, entityID, entity1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntity")
	}

	var r0 *entity.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *entity.Entity) (*entity.Entity, error)); ok {
		return returnFunc(ctx, entityID, entity1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *entity.Entity) *entity.Entity); ok {
		r0 = returnFunc(ctx, entityID, entity1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *entity.Entity) error); ok {
		r1 = returnFunc(ctx, entityID, entity1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_UpdateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntity'
type EntityServiceInterfaceMock_UpdateEntity_Call struct {
	*mock.Call
}

// UpdateEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - entity1 *entity.Entity
func (_e *EntityServiceInterfaceMock_Expecter) UpdateEntity(ctx interface{}, entityID interface{}, entity1 interface{}) *EntityServiceInterfaceMock_UpdateEntity_Call {
	return &EntityServiceInterfaceMock_UpdateEntity_Call{Call: _e.mock.On("UpdateEntity", ctx, entityID, entity1)}
}

func (_c *EntityServiceInterfaceMock_UpdateEntity_Call) Run(run func(ctx context.Context, entityID string, entity1 *entity.Entity)) *EntityServiceInterfaceMock_UpdateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.Entity
		if args[2] != nil {
			arg2 = args[2].(*entity.Entity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateEntity_Call) Return(entity11 *entity.Entity, err error) *EntityServiceInterfaceMock_UpdateEntity_Call {
	_c.Call.Return(entity11, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateEntity_Call) RunAndReturn(run func(ctx context.Context, entityID string, entity1 *entity.Entity) (*entity.Entity, error)) *EntityServiceInterfaceMock_UpdateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSystemAttributes provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) UpdateSystemAttributes(ctx context.Context, entityID string, attrs json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, attrs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSystemAttributes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, attrs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_UpdateSystemAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSystemAttributes'
type EntityServiceInterfaceMock_UpdateSystemAttributes_Call struct {
	*mock.Call
}

// UpdateSystemAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - attrs json.RawMessage
func (_e *EntityServiceInterfaceMock_Expecter) UpdateSystemAttributes(ctx interface{}, entityID interface{}, attrs interface{}) *EntityServiceInterfaceMock_UpdateSystemAttributes_Call {
	return &EntityServiceInterfaceMock_UpdateSystemAttributes_Call{Call: _e.mock.On("UpdateSystemAttributes", ctx, entityID, attrs)}
}

func (_c *EntityServiceInterfaceMock_UpdateSystemAttributes_Call) Run(run func(ctx context.Context, entityID string, attrs json.RawMessage)) *EntityServiceInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateSystemAttributes_Call) Return(err error) *EntityServiceInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateSystemAttributes_Call) RunAndReturn(run func(ctx context.Context, entityID string, attrs json.RawMessage) error) *EntityServiceInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSystemCredentials provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) UpdateSystemCredentials(ctx context.Context, entityID string, plaintextUpdates json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, plaintextUpdates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSystemCredentials")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, plaintextUpdates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntityServiceInterfaceMock_UpdateSystemCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSystemCredentials'
type EntityServiceInterfaceMock_UpdateSystemCredentials_Call struct {
	*mock.Call
}

// UpdateSystemCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - plaintextUpdates json.RawMessage
func (_e *EntityServiceInterfaceMock_Expecter) UpdateSystemCredentials(ctx interface{}, entityID interface{}, plaintextUpdates interface{}) *EntityServiceInterfaceMock_UpdateSystemCredentials_Call {
	return &EntityServiceInterfaceMock_UpdateSystemCredentials_Call{Call: _e.mock.On("UpdateSystemCredentials", ctx, entityID, plaintextUpdates)}
}

func (_c *EntityServiceInterfaceMock_UpdateSystemCredentials_Call) Run(run func(ctx context.Context, entityID string, plaintextUpdates json.RawMessage)) *EntityServiceInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateSystemCredentials_Call) Return(err error) *EntityServiceInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntityServiceInterfaceMock_UpdateSystemCredentials_Call) RunAndReturn(run func(ctx context.Context, entityID string, plaintextUpdates json.RawMessage) error) *EntityServiceInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEntityIDs provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) ValidateEntityIDs(ctx context.Context, entityIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, entityIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEntityIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, entityIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, entityIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, entityIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_ValidateEntityIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEntityIDs'
type EntityServiceInterfaceMock_ValidateEntityIDs_Call struct {
	*mock.Call
}

// ValidateEntityIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - entityIDs []string
func (_e *EntityServiceInterfaceMock_Expecter) ValidateEntityIDs(ctx interface{}, entityIDs interface{}) *EntityServiceInterfaceMock_ValidateEntityIDs_Call {
	return &EntityServiceInterfaceMock_ValidateEntityIDs_Call{Call: _e.mock.On("ValidateEntityIDs", ctx, entityIDs)}
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDs_Call) Run(run func(ctx context.Context, entityIDs []string)) *EntityServiceInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDs_Call) Return(strings []string, err error) *EntityServiceInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDs_Call) RunAndReturn(run func(ctx context.Context, entityIDs []string) ([]string, error)) *EntityServiceInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEntityIDsInOUs provides a mock function for the type EntityServiceInterfaceMock
func (_mock *EntityServiceInterfaceMock) ValidateEntityIDsInOUs(ctx context.Context, entityIDs []string, ouIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, entityIDs, ouIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEntityIDsInOUs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) ([]string, error)); ok {
		return returnFunc(ctx, entityIDs, ouIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) []string); ok {
		r0 = returnFunc(ctx, entityIDs, ouIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = returnFunc(ctx, entityIDs, ouIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEntityIDsInOUs'
type EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call struct {
	*mock.Call
}

// ValidateEntityIDsInOUs is a helper method to define mock.On call
//   - ctx context.Context
//   - entityIDs []string
//   - ouIDs []string
func (_e *EntityServiceInterfaceMock_Expecter) ValidateEntityIDsInOUs(ctx interface{}, entityIDs interface{}, ouIDs interface{}) *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call {
	return &EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call{Call: _e.mock.On("ValidateEntityIDsInOUs", ctx, entityIDs, ouIDs)}
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call) Run(run func(ctx context.Context, entityIDs []string, ouIDs []string)) *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call) Return(strings []string, err error) *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call) RunAndReturn(run func(ctx context.Context, entityIDs []string, ouIDs []string) ([]string, error)) *EntityServiceInterfaceMock_ValidateEntityIDsInOUs_Call {
	_c.Call.Return(run)
	return _c
}
