/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * Organization Unit Response Model
 *
 * Complete organization unit information returned by the server.
 * This is the primary entity representing a hierarchical organizational unit
 * within the platform.
 *
 * @public
 * @remarks
 * This model is returned by:
 * - GET /organization-units/:id (get by ID)
 * - POST /organization-units (create)
 * - PUT /organization-units/:id (update)
 *
 * Organization units form a tree hierarchy via the `parent` field.
 * Each unit can have its own theme, layout, and branding configuration.
 *
 * @example
 * ```typescript
 * const ou: OrganizationUnit = {
 *   id: '550e8400-e29b-41d4-a716-446655440000',
 *   handle: 'engineering',
 *   name: 'Engineering Department',
 *   description: 'Software engineering team',
 *   parent: 'root-ou-id',
 *   themeId: '96c62e6d-9297-4295-8195-d28dfe0c9ff7',
 *   logoUrl: 'https://example.com/logo.png'
 * };
 * ```
 */
export interface OrganizationUnit {
  /**
   * Unique identifier of the organization unit
   * Generated by the server upon creation
   * @example '550e8400-e29b-41d4-a716-446655440000'
   */
  id: string;

  /**
   * URL-friendly handle for the organization unit
   * Must be unique across all organization units
   * @example 'engineering'
   */
  handle: string;

  /**
   * Display name of the organization unit
   * @example 'Engineering Department'
   */
  name: string;

  /**
   * Optional description of the organization unit
   * @example 'Software engineering team'
   */
  description?: string | null;

  /**
   * ID of the parent organization unit
   * Null or undefined for root-level units
   * @example 'root-ou-id'
   */
  parent?: string | null;

  /**
   * Theme configuration ID
   * References a theme that customizes the visual styling
   * @example '96c62e6d-9297-4295-8195-d28dfe0c9ff7'
   */
  themeId?: string | null;

  /**
   * Layout configuration ID
   * References a layout that customizes the page structure
   * @example 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
   */
  layoutId?: string | null;

  /**
   * Organization unit logo URL
   * @example 'https://example.com/logo.png'
   */
  logoUrl?: string;

  /**
   * Whether the organization unit is read-only and cannot be modified or deleted.
   */
  isReadOnly?: boolean;
}
