// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package githubmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/authn/common"
	"github.com/thunder-id/thunderid/internal/authn/oauth"
	"github.com/thunder-id/thunderid/internal/entityprovider"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewGithubOAuthAuthnServiceInterfaceMock creates a new instance of GithubOAuthAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGithubOAuthAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GithubOAuthAuthnServiceInterfaceMock {
	mock := &GithubOAuthAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GithubOAuthAuthnServiceInterfaceMock is an autogenerated mock type for the GithubOAuthAuthnServiceInterface type
type GithubOAuthAuthnServiceInterfaceMock struct {
	mock.Mock
}

type GithubOAuthAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GithubOAuthAuthnServiceInterfaceMock) EXPECT() *GithubOAuthAuthnServiceInterfaceMock_Expecter {
	return &GithubOAuthAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) Authenticate(ctx context.Context, idpID string, code string) (*common.FederatedAuthResult, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, idpID, code)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *common.FederatedAuthResult
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*common.FederatedAuthResult, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, idpID, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *common.FederatedAuthResult); ok {
		r0 = returnFunc(ctx, idpID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.FederatedAuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, code)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - code string
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) Authenticate(ctx interface{}, idpID interface{}, code interface{}) *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, idpID, code)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call) Run(run func(ctx context.Context, idpID string, code string)) *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call) Return(federatedAuthResult *common.FederatedAuthResult, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(federatedAuthResult, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, idpID string, code string) (*common.FederatedAuthResult, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// BuildAuthorizeURL provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) BuildAuthorizeURL(ctx context.Context, idpID string) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, idpID)

	if len(ret) == 0 {
		panic("no return value specified for BuildAuthorizeURL")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, idpID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildAuthorizeURL'
type GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call struct {
	*mock.Call
}

// BuildAuthorizeURL is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) BuildAuthorizeURL(ctx interface{}, idpID interface{}) *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call{Call: _e.mock.On("BuildAuthorizeURL", ctx, idpID)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) Run(run func(ctx context.Context, idpID string)) *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) Return(s string, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) RunAndReturn(run func(ctx context.Context, idpID string) (string, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCodeForToken provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) ExchangeCodeForToken(ctx context.Context, idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, idpID, code, validateResponse)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth.TokenResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*oauth.TokenResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, idpID, code, validateResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, idpID, code, validateResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, code, validateResponse)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - code string
//   - validateResponse bool
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) ExchangeCodeForToken(ctx interface{}, idpID interface{}, code interface{}, validateResponse interface{}) *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", ctx, idpID, code, validateResponse)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) Run(run func(ctx context.Context, idpID string, code string, validateResponse bool)) *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) Return(tokenResponse *oauth.TokenResponse, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(tokenResponse, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) RunAndReturn(run func(ctx context.Context, idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserInfo provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) FetchUserInfo(ctx context.Context, idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, idpID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserInfo")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, idpID, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = returnFunc(ctx, idpID, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, idpID, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserInfo'
type GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call struct {
	*mock.Call
}

// FetchUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
//   - accessToken string
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) FetchUserInfo(ctx interface{}, idpID interface{}, accessToken interface{}) *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call{Call: _e.mock.On("FetchUserInfo", ctx, idpID, accessToken)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) Run(run func(ctx context.Context, idpID string, accessToken string)) *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) RunAndReturn(run func(ctx context.Context, idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalUser provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) GetInternalUser(sub string) (*entityprovider.Entity, *serviceerror.ServiceError) {
	ret := _mock.Called(sub)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalUser")
	}

	var r0 *entityprovider.Entity
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*entityprovider.Entity, *serviceerror.ServiceError)); ok {
		return returnFunc(sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entityprovider.Entity); ok {
		r0 = returnFunc(sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(sub)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalUser'
type GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call struct {
	*mock.Call
}

// GetInternalUser is a helper method to define mock.On call
//   - sub string
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) GetInternalUser(sub interface{}) *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call{Call: _e.mock.On("GetInternalUser", sub)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call) Run(run func(sub string)) *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call) Return(entity *entityprovider.Entity, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(entity, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call) RunAndReturn(run func(sub string) (*entityprovider.Entity, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthClientConfig provides a mock function for the type GithubOAuthAuthnServiceInterfaceMock
func (_mock *GithubOAuthAuthnServiceInterfaceMock) GetOAuthClientConfig(ctx context.Context, idpID string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, idpID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthClientConfig")
	}

	var r0 *oauth.OAuthClientConfig
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oauth.OAuthClientConfig); ok {
		r0 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.OAuthClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthClientConfig'
type GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call struct {
	*mock.Call
}

// GetOAuthClientConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - idpID string
func (_e *GithubOAuthAuthnServiceInterfaceMock_Expecter) GetOAuthClientConfig(ctx interface{}, idpID interface{}) *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	return &GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call{Call: _e.mock.On("GetOAuthClientConfig", ctx, idpID)}
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) Run(run func(ctx context.Context, idpID string)) *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) Return(oAuthClientConfig *oauth.OAuthClientConfig, serviceError *serviceerror.ServiceError) *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(oAuthClientConfig, serviceError)
	return _c
}

func (_c *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) RunAndReturn(run func(ctx context.Context, idpID string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError)) *GithubOAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(run)
	return _c
}
