# Copyright 2026 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thunderid-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thunderid-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "thunderid-operator.selectorLabels" . | nindent 4 }}
{{- end }}
