// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package inboundclient

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/inboundclient/model"
)

// newInboundClientStoreInterfaceMock creates a new instance of inboundClientStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInboundClientStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *inboundClientStoreInterfaceMock {
	mock := &inboundClientStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// inboundClientStoreInterfaceMock is an autogenerated mock type for the inboundClientStoreInterface type
type inboundClientStoreInterfaceMock struct {
	mock.Mock
}

type inboundClientStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *inboundClientStoreInterfaceMock) EXPECT() *inboundClientStoreInterfaceMock_Expecter {
	return &inboundClientStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateInboundClient provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) CreateInboundClient(ctx context.Context, client model.InboundClient) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for CreateInboundClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.InboundClient) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_CreateInboundClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInboundClient'
type inboundClientStoreInterfaceMock_CreateInboundClient_Call struct {
	*mock.Call
}

// CreateInboundClient is a helper method to define mock.On call
//   - ctx context.Context
//   - client model.InboundClient
func (_e *inboundClientStoreInterfaceMock_Expecter) CreateInboundClient(ctx interface{}, client interface{}) *inboundClientStoreInterfaceMock_CreateInboundClient_Call {
	return &inboundClientStoreInterfaceMock_CreateInboundClient_Call{Call: _e.mock.On("CreateInboundClient", ctx, client)}
}

func (_c *inboundClientStoreInterfaceMock_CreateInboundClient_Call) Run(run func(ctx context.Context, client model.InboundClient)) *inboundClientStoreInterfaceMock_CreateInboundClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.InboundClient
		if args[1] != nil {
			arg1 = args[1].(model.InboundClient)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_CreateInboundClient_Call) Return(err error) *inboundClientStoreInterfaceMock_CreateInboundClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_CreateInboundClient_Call) RunAndReturn(run func(ctx context.Context, client model.InboundClient) error) *inboundClientStoreInterfaceMock_CreateInboundClient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOAuthProfile provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) CreateOAuthProfile(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile) error {
	ret := _mock.Called(ctx, entityID, oauthProfile)

	if len(ret) == 0 {
		panic("no return value specified for CreateOAuthProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.OAuthProfile) error); ok {
		r0 = returnFunc(ctx, entityID, oauthProfile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_CreateOAuthProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOAuthProfile'
type inboundClientStoreInterfaceMock_CreateOAuthProfile_Call struct {
	*mock.Call
}

// CreateOAuthProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - oauthProfile *model.OAuthProfile
func (_e *inboundClientStoreInterfaceMock_Expecter) CreateOAuthProfile(ctx interface{}, entityID interface{}, oauthProfile interface{}) *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call {
	return &inboundClientStoreInterfaceMock_CreateOAuthProfile_Call{Call: _e.mock.On("CreateOAuthProfile", ctx, entityID, oauthProfile)}
}

func (_c *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call) Run(run func(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile)) *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.OAuthProfile
		if args[2] != nil {
			arg2 = args[2].(*model.OAuthProfile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call) Return(err error) *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call) RunAndReturn(run func(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile) error) *inboundClientStoreInterfaceMock_CreateOAuthProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInboundClient provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) DeleteInboundClient(ctx context.Context, entityID string) error {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInboundClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_DeleteInboundClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInboundClient'
type inboundClientStoreInterfaceMock_DeleteInboundClient_Call struct {
	*mock.Call
}

// DeleteInboundClient is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) DeleteInboundClient(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_DeleteInboundClient_Call {
	return &inboundClientStoreInterfaceMock_DeleteInboundClient_Call{Call: _e.mock.On("DeleteInboundClient", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_DeleteInboundClient_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_DeleteInboundClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_DeleteInboundClient_Call) Return(err error) *inboundClientStoreInterfaceMock_DeleteInboundClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_DeleteInboundClient_Call) RunAndReturn(run func(ctx context.Context, entityID string) error) *inboundClientStoreInterfaceMock_DeleteInboundClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOAuthProfile provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) DeleteOAuthProfile(ctx context.Context, entityID string) error {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOAuthProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOAuthProfile'
type inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call struct {
	*mock.Call
}

// DeleteOAuthProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) DeleteOAuthProfile(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call {
	return &inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call{Call: _e.mock.On("DeleteOAuthProfile", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call) Return(err error) *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call) RunAndReturn(run func(ctx context.Context, entityID string) error) *inboundClientStoreInterfaceMock_DeleteOAuthProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetInboundClientByEntityID provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) GetInboundClientByEntityID(ctx context.Context, entityID string) (*model.InboundClient, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetInboundClientByEntityID")
	}

	var r0 *model.InboundClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.InboundClient, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.InboundClient); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InboundClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInboundClientByEntityID'
type inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call struct {
	*mock.Call
}

// GetInboundClientByEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) GetInboundClientByEntityID(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call {
	return &inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call{Call: _e.mock.On("GetInboundClientByEntityID", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call) Return(inboundClient *model.InboundClient, err error) *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call {
	_c.Call.Return(inboundClient, err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call) RunAndReturn(run func(ctx context.Context, entityID string) (*model.InboundClient, error)) *inboundClientStoreInterfaceMock_GetInboundClientByEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInboundClientList provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) GetInboundClientList(ctx context.Context, limit int) ([]model.InboundClient, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetInboundClientList")
	}

	var r0 []model.InboundClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.InboundClient, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.InboundClient); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.InboundClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inboundClientStoreInterfaceMock_GetInboundClientList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInboundClientList'
type inboundClientStoreInterfaceMock_GetInboundClientList_Call struct {
	*mock.Call
}

// GetInboundClientList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *inboundClientStoreInterfaceMock_Expecter) GetInboundClientList(ctx interface{}, limit interface{}) *inboundClientStoreInterfaceMock_GetInboundClientList_Call {
	return &inboundClientStoreInterfaceMock_GetInboundClientList_Call{Call: _e.mock.On("GetInboundClientList", ctx, limit)}
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientList_Call) Run(run func(ctx context.Context, limit int)) *inboundClientStoreInterfaceMock_GetInboundClientList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientList_Call) Return(inboundClients []model.InboundClient, err error) *inboundClientStoreInterfaceMock_GetInboundClientList_Call {
	_c.Call.Return(inboundClients, err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetInboundClientList_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]model.InboundClient, error)) *inboundClientStoreInterfaceMock_GetInboundClientList_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthProfileByEntityID provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) GetOAuthProfileByEntityID(ctx context.Context, entityID string) (*model.OAuthProfile, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthProfileByEntityID")
	}

	var r0 *model.OAuthProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.OAuthProfile, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.OAuthProfile); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OAuthProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthProfileByEntityID'
type inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call struct {
	*mock.Call
}

// GetOAuthProfileByEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) GetOAuthProfileByEntityID(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call {
	return &inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call{Call: _e.mock.On("GetOAuthProfileByEntityID", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call) Return(oAuthProfile *model.OAuthProfile, err error) *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call {
	_c.Call.Return(oAuthProfile, err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call) RunAndReturn(run func(ctx context.Context, entityID string) (*model.OAuthProfile, error)) *inboundClientStoreInterfaceMock_GetOAuthProfileByEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalInboundClientCount provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) GetTotalInboundClientCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalInboundClientCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalInboundClientCount'
type inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call struct {
	*mock.Call
}

// GetTotalInboundClientCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *inboundClientStoreInterfaceMock_Expecter) GetTotalInboundClientCount(ctx interface{}) *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call {
	return &inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call{Call: _e.mock.On("GetTotalInboundClientCount", ctx)}
}

func (_c *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call) Run(run func(ctx context.Context)) *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call) Return(n int, err error) *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *inboundClientStoreInterfaceMock_GetTotalInboundClientCount_Call {
	_c.Call.Return(run)
	return _c
}

// InboundClientExists provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) InboundClientExists(ctx context.Context, entityID string) (bool, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for InboundClientExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inboundClientStoreInterfaceMock_InboundClientExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InboundClientExists'
type inboundClientStoreInterfaceMock_InboundClientExists_Call struct {
	*mock.Call
}

// InboundClientExists is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) InboundClientExists(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_InboundClientExists_Call {
	return &inboundClientStoreInterfaceMock_InboundClientExists_Call{Call: _e.mock.On("InboundClientExists", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_InboundClientExists_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_InboundClientExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_InboundClientExists_Call) Return(b bool, err error) *inboundClientStoreInterfaceMock_InboundClientExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_InboundClientExists_Call) RunAndReturn(run func(ctx context.Context, entityID string) (bool, error)) *inboundClientStoreInterfaceMock_InboundClientExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsDeclarative provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) IsDeclarative(ctx context.Context, entityID string) bool {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for IsDeclarative")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// inboundClientStoreInterfaceMock_IsDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDeclarative'
type inboundClientStoreInterfaceMock_IsDeclarative_Call struct {
	*mock.Call
}

// IsDeclarative is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *inboundClientStoreInterfaceMock_Expecter) IsDeclarative(ctx interface{}, entityID interface{}) *inboundClientStoreInterfaceMock_IsDeclarative_Call {
	return &inboundClientStoreInterfaceMock_IsDeclarative_Call{Call: _e.mock.On("IsDeclarative", ctx, entityID)}
}

func (_c *inboundClientStoreInterfaceMock_IsDeclarative_Call) Run(run func(ctx context.Context, entityID string)) *inboundClientStoreInterfaceMock_IsDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_IsDeclarative_Call) Return(b bool) *inboundClientStoreInterfaceMock_IsDeclarative_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_IsDeclarative_Call) RunAndReturn(run func(ctx context.Context, entityID string) bool) *inboundClientStoreInterfaceMock_IsDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInboundClient provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) UpdateInboundClient(ctx context.Context, client model.InboundClient) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInboundClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.InboundClient) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_UpdateInboundClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInboundClient'
type inboundClientStoreInterfaceMock_UpdateInboundClient_Call struct {
	*mock.Call
}

// UpdateInboundClient is a helper method to define mock.On call
//   - ctx context.Context
//   - client model.InboundClient
func (_e *inboundClientStoreInterfaceMock_Expecter) UpdateInboundClient(ctx interface{}, client interface{}) *inboundClientStoreInterfaceMock_UpdateInboundClient_Call {
	return &inboundClientStoreInterfaceMock_UpdateInboundClient_Call{Call: _e.mock.On("UpdateInboundClient", ctx, client)}
}

func (_c *inboundClientStoreInterfaceMock_UpdateInboundClient_Call) Run(run func(ctx context.Context, client model.InboundClient)) *inboundClientStoreInterfaceMock_UpdateInboundClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.InboundClient
		if args[1] != nil {
			arg1 = args[1].(model.InboundClient)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_UpdateInboundClient_Call) Return(err error) *inboundClientStoreInterfaceMock_UpdateInboundClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_UpdateInboundClient_Call) RunAndReturn(run func(ctx context.Context, client model.InboundClient) error) *inboundClientStoreInterfaceMock_UpdateInboundClient_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOAuthProfile provides a mock function for the type inboundClientStoreInterfaceMock
func (_mock *inboundClientStoreInterfaceMock) UpdateOAuthProfile(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile) error {
	ret := _mock.Called(ctx, entityID, oauthProfile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOAuthProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.OAuthProfile) error); ok {
		r0 = returnFunc(ctx, entityID, oauthProfile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOAuthProfile'
type inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call struct {
	*mock.Call
}

// UpdateOAuthProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - oauthProfile *model.OAuthProfile
func (_e *inboundClientStoreInterfaceMock_Expecter) UpdateOAuthProfile(ctx interface{}, entityID interface{}, oauthProfile interface{}) *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call {
	return &inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call{Call: _e.mock.On("UpdateOAuthProfile", ctx, entityID, oauthProfile)}
}

func (_c *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call) Run(run func(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile)) *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.OAuthProfile
		if args[2] != nil {
			arg2 = args[2].(*model.OAuthProfile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call) Return(err error) *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call) RunAndReturn(run func(ctx context.Context, entityID string, oauthProfile *model.OAuthProfile) error) *inboundClientStoreInterfaceMock_UpdateOAuthProfile_Call {
	_c.Call.Return(run)
	return _c
}
