handle: "self-registration-invite-sms"
displayName: "Self Registration Invite SMS"
channel: "sms"
content:
  body: "{{ctx(appName)}}: {{ t(notification:template.registration_link_instructions) }} {{ctx(inviteLink)}}"
