handle: "ciba-notification-sms"
displayName: "CIBA Authentication Notification SMS"
channel: "sms"
content:
  body: "{{ctx(appName)}}: {{ctx(bindingMessage)}} {{ t(notification:template.approval_link_instructions) }} {{ctx(inviteLink)}}"
