// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authzenpdp

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewAuthZENPDPServiceInterfaceMock creates a new instance of AuthZENPDPServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthZENPDPServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthZENPDPServiceInterfaceMock {
	mock := &AuthZENPDPServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthZENPDPServiceInterfaceMock is an autogenerated mock type for the AuthZENPDPServiceInterface type
type AuthZENPDPServiceInterfaceMock struct {
	mock.Mock
}

type AuthZENPDPServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthZENPDPServiceInterfaceMock) EXPECT() *AuthZENPDPServiceInterfaceMock_Expecter {
	return &AuthZENPDPServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateAuthZENPDPConnection provides a mock function for the type AuthZENPDPServiceInterfaceMock
func (_mock *AuthZENPDPServiceInterfaceMock) CreateAuthZENPDPConnection(ctx context.Context, request ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthZENPDPConnection")
	}

	var r0 *AuthZENPDPConnection
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConnectionRequest) *AuthZENPDPConnection); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthZENPDPConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ConnectionRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthZENPDPConnection'
type AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call struct {
	*mock.Call
}

// CreateAuthZENPDPConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - request ConnectionRequest
func (_e *AuthZENPDPServiceInterfaceMock_Expecter) CreateAuthZENPDPConnection(ctx interface{}, request interface{}) *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call {
	return &AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call{Call: _e.mock.On("CreateAuthZENPDPConnection", ctx, request)}
}

func (_c *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call) Run(run func(ctx context.Context, request ConnectionRequest)) *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ConnectionRequest
		if args[1] != nil {
			arg1 = args[1].(ConnectionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call) Return(authZENPDPConnection *AuthZENPDPConnection, serviceError *common.ServiceError) *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call {
	_c.Call.Return(authZENPDPConnection, serviceError)
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call) RunAndReturn(run func(ctx context.Context, request ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError)) *AuthZENPDPServiceInterfaceMock_CreateAuthZENPDPConnection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthZENPDPConnection provides a mock function for the type AuthZENPDPServiceInterfaceMock
func (_mock *AuthZENPDPServiceInterfaceMock) DeleteAuthZENPDPConnection(ctx context.Context, id string) *common.ServiceError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthZENPDPConnection")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthZENPDPConnection'
type AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call struct {
	*mock.Call
}

// DeleteAuthZENPDPConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthZENPDPServiceInterfaceMock_Expecter) DeleteAuthZENPDPConnection(ctx interface{}, id interface{}) *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call {
	return &AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call{Call: _e.mock.On("DeleteAuthZENPDPConnection", ctx, id)}
}

func (_c *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call) Run(run func(ctx context.Context, id string)) *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call) Return(serviceError *common.ServiceError) *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call) RunAndReturn(run func(ctx context.Context, id string) *common.ServiceError) *AuthZENPDPServiceInterfaceMock_DeleteAuthZENPDPConnection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthZENPDP provides a mock function for the type AuthZENPDPServiceInterfaceMock
func (_mock *AuthZENPDPServiceInterfaceMock) GetAuthZENPDP(ctx context.Context, id string) (*AuthZENPDPConnection, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthZENPDP")
	}

	var r0 *AuthZENPDPConnection
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AuthZENPDPConnection, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AuthZENPDPConnection); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthZENPDPConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthZENPDP'
type AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call struct {
	*mock.Call
}

// GetAuthZENPDP is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthZENPDPServiceInterfaceMock_Expecter) GetAuthZENPDP(ctx interface{}, id interface{}) *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call {
	return &AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call{Call: _e.mock.On("GetAuthZENPDP", ctx, id)}
}

func (_c *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call) Run(run func(ctx context.Context, id string)) *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call) Return(authZENPDPConnection *AuthZENPDPConnection, serviceError *common.ServiceError) *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call {
	_c.Call.Return(authZENPDPConnection, serviceError)
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call) RunAndReturn(run func(ctx context.Context, id string) (*AuthZENPDPConnection, *common.ServiceError)) *AuthZENPDPServiceInterfaceMock_GetAuthZENPDP_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthZENPDPs provides a mock function for the type AuthZENPDPServiceInterfaceMock
func (_mock *AuthZENPDPServiceInterfaceMock) ListAuthZENPDPs(ctx context.Context) ([]AuthZENPDPConnection, *common.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthZENPDPs")
	}

	var r0 []AuthZENPDPConnection
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]AuthZENPDPConnection, *common.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []AuthZENPDPConnection); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AuthZENPDPConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *common.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthZENPDPs'
type AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call struct {
	*mock.Call
}

// ListAuthZENPDPs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthZENPDPServiceInterfaceMock_Expecter) ListAuthZENPDPs(ctx interface{}) *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call {
	return &AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call{Call: _e.mock.On("ListAuthZENPDPs", ctx)}
}

func (_c *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call) Run(run func(ctx context.Context)) *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call) Return(authZENPDPConnections []AuthZENPDPConnection, serviceError *common.ServiceError) *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call {
	_c.Call.Return(authZENPDPConnections, serviceError)
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call) RunAndReturn(run func(ctx context.Context) ([]AuthZENPDPConnection, *common.ServiceError)) *AuthZENPDPServiceInterfaceMock_ListAuthZENPDPs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuthZENPDPConnection provides a mock function for the type AuthZENPDPServiceInterfaceMock
func (_mock *AuthZENPDPServiceInterfaceMock) UpdateAuthZENPDPConnection(ctx context.Context, id string, request ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthZENPDPConnection")
	}

	var r0 *AuthZENPDPConnection
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ConnectionRequest) *AuthZENPDPConnection); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthZENPDPConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ConnectionRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuthZENPDPConnection'
type AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call struct {
	*mock.Call
}

// UpdateAuthZENPDPConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request ConnectionRequest
func (_e *AuthZENPDPServiceInterfaceMock_Expecter) UpdateAuthZENPDPConnection(ctx interface{}, id interface{}, request interface{}) *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call {
	return &AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call{Call: _e.mock.On("UpdateAuthZENPDPConnection", ctx, id, request)}
}

func (_c *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call) Run(run func(ctx context.Context, id string, request ConnectionRequest)) *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ConnectionRequest
		if args[2] != nil {
			arg2 = args[2].(ConnectionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call) Return(authZENPDPConnection *AuthZENPDPConnection, serviceError *common.ServiceError) *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call {
	_c.Call.Return(authZENPDPConnection, serviceError)
	return _c
}

func (_c *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call) RunAndReturn(run func(ctx context.Context, id string, request ConnectionRequest) (*AuthZENPDPConnection, *common.ServiceError)) *AuthZENPDPServiceInterfaceMock_UpdateAuthZENPDPConnection_Call {
	_c.Call.Return(run)
	return _c
}
