// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// NewFlowFactoryInterfaceMock creates a new instance of FlowFactoryInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowFactoryInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowFactoryInterfaceMock {
	mock := &FlowFactoryInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FlowFactoryInterfaceMock is an autogenerated mock type for the FlowFactoryInterface type
type FlowFactoryInterfaceMock struct {
	mock.Mock
}

type FlowFactoryInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowFactoryInterfaceMock) EXPECT() *FlowFactoryInterfaceMock_Expecter {
	return &FlowFactoryInterfaceMock_Expecter{mock: &_m.Mock}
}

// CloneNode provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CloneNode(source NodeInterface) (NodeInterface, error) {
	ret := _mock.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for CloneNode")
	}

	var r0 NodeInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(NodeInterface) (NodeInterface, error)); ok {
		return returnFunc(source)
	}
	if returnFunc, ok := ret.Get(0).(func(NodeInterface) NodeInterface); ok {
		r0 = returnFunc(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(NodeInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(NodeInterface) error); ok {
		r1 = returnFunc(source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowFactoryInterfaceMock_CloneNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneNode'
type FlowFactoryInterfaceMock_CloneNode_Call struct {
	*mock.Call
}

// CloneNode is a helper method to define mock.On call
//   - source NodeInterface
func (_e *FlowFactoryInterfaceMock_Expecter) CloneNode(source interface{}) *FlowFactoryInterfaceMock_CloneNode_Call {
	return &FlowFactoryInterfaceMock_CloneNode_Call{Call: _e.mock.On("CloneNode", source)}
}

func (_c *FlowFactoryInterfaceMock_CloneNode_Call) Run(run func(source NodeInterface)) *FlowFactoryInterfaceMock_CloneNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 NodeInterface
		if args[0] != nil {
			arg0 = args[0].(NodeInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CloneNode_Call) Return(nodeInterface NodeInterface, err error) *FlowFactoryInterfaceMock_CloneNode_Call {
	_c.Call.Return(nodeInterface, err)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CloneNode_Call) RunAndReturn(run func(source NodeInterface) (NodeInterface, error)) *FlowFactoryInterfaceMock_CloneNode_Call {
	_c.Call.Return(run)
	return _c
}

// CloneNodes provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CloneNodes(nodes map[string]NodeInterface) (map[string]NodeInterface, error) {
	ret := _mock.Called(nodes)

	if len(ret) == 0 {
		panic("no return value specified for CloneNodes")
	}

	var r0 map[string]NodeInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]NodeInterface) (map[string]NodeInterface, error)); ok {
		return returnFunc(nodes)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]NodeInterface) map[string]NodeInterface); ok {
		r0 = returnFunc(nodes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]NodeInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]NodeInterface) error); ok {
		r1 = returnFunc(nodes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowFactoryInterfaceMock_CloneNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneNodes'
type FlowFactoryInterfaceMock_CloneNodes_Call struct {
	*mock.Call
}

// CloneNodes is a helper method to define mock.On call
//   - nodes map[string]NodeInterface
func (_e *FlowFactoryInterfaceMock_Expecter) CloneNodes(nodes interface{}) *FlowFactoryInterfaceMock_CloneNodes_Call {
	return &FlowFactoryInterfaceMock_CloneNodes_Call{Call: _e.mock.On("CloneNodes", nodes)}
}

func (_c *FlowFactoryInterfaceMock_CloneNodes_Call) Run(run func(nodes map[string]NodeInterface)) *FlowFactoryInterfaceMock_CloneNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]NodeInterface
		if args[0] != nil {
			arg0 = args[0].(map[string]NodeInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CloneNodes_Call) Return(stringToNodeInterface map[string]NodeInterface, err error) *FlowFactoryInterfaceMock_CloneNodes_Call {
	_c.Call.Return(stringToNodeInterface, err)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CloneNodes_Call) RunAndReturn(run func(nodes map[string]NodeInterface) (map[string]NodeInterface, error)) *FlowFactoryInterfaceMock_CloneNodes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExecutor provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CreateExecutor(name string, executorType providers.ExecutorType, defaultInputs []providers.Input, prerequisites []providers.Input, meta *providers.ExecutorMeta) providers.Executor {
	ret := _mock.Called(name, executorType, defaultInputs, prerequisites, meta)

	if len(ret) == 0 {
		panic("no return value specified for CreateExecutor")
	}

	var r0 providers.Executor
	if returnFunc, ok := ret.Get(0).(func(string, providers.ExecutorType, []providers.Input, []providers.Input, *providers.ExecutorMeta) providers.Executor); ok {
		r0 = returnFunc(name, executorType, defaultInputs, prerequisites, meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(providers.Executor)
		}
	}
	return r0
}

// FlowFactoryInterfaceMock_CreateExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExecutor'
type FlowFactoryInterfaceMock_CreateExecutor_Call struct {
	*mock.Call
}

// CreateExecutor is a helper method to define mock.On call
//   - name string
//   - executorType providers.ExecutorType
//   - defaultInputs []providers.Input
//   - prerequisites []providers.Input
//   - meta *providers.ExecutorMeta
func (_e *FlowFactoryInterfaceMock_Expecter) CreateExecutor(name interface{}, executorType interface{}, defaultInputs interface{}, prerequisites interface{}, meta interface{}) *FlowFactoryInterfaceMock_CreateExecutor_Call {
	return &FlowFactoryInterfaceMock_CreateExecutor_Call{Call: _e.mock.On("CreateExecutor", name, executorType, defaultInputs, prerequisites, meta)}
}

func (_c *FlowFactoryInterfaceMock_CreateExecutor_Call) Run(run func(name string, executorType providers.ExecutorType, defaultInputs []providers.Input, prerequisites []providers.Input, meta *providers.ExecutorMeta)) *FlowFactoryInterfaceMock_CreateExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 providers.ExecutorType
		if args[1] != nil {
			arg1 = args[1].(providers.ExecutorType)
		}
		var arg2 []providers.Input
		if args[2] != nil {
			arg2 = args[2].([]providers.Input)
		}
		var arg3 []providers.Input
		if args[3] != nil {
			arg3 = args[3].([]providers.Input)
		}
		var arg4 *providers.ExecutorMeta
		if args[4] != nil {
			arg4 = args[4].(*providers.ExecutorMeta)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateExecutor_Call) Return(executor providers.Executor) *FlowFactoryInterfaceMock_CreateExecutor_Call {
	_c.Call.Return(executor)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateExecutor_Call) RunAndReturn(run func(name string, executorType providers.ExecutorType, defaultInputs []providers.Input, prerequisites []providers.Input, meta *providers.ExecutorMeta) providers.Executor) *FlowFactoryInterfaceMock_CreateExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGraph provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CreateGraph(id string, _type providers.FlowType, version int) GraphInterface {
	ret := _mock.Called(id, _type, version)

	if len(ret) == 0 {
		panic("no return value specified for CreateGraph")
	}

	var r0 GraphInterface
	if returnFunc, ok := ret.Get(0).(func(string, providers.FlowType, int) GraphInterface); ok {
		r0 = returnFunc(id, _type, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(GraphInterface)
		}
	}
	return r0
}

// FlowFactoryInterfaceMock_CreateGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGraph'
type FlowFactoryInterfaceMock_CreateGraph_Call struct {
	*mock.Call
}

// CreateGraph is a helper method to define mock.On call
//   - id string
//   - _type providers.FlowType
//   - version int
func (_e *FlowFactoryInterfaceMock_Expecter) CreateGraph(id interface{}, _type interface{}, version interface{}) *FlowFactoryInterfaceMock_CreateGraph_Call {
	return &FlowFactoryInterfaceMock_CreateGraph_Call{Call: _e.mock.On("CreateGraph", id, _type, version)}
}

func (_c *FlowFactoryInterfaceMock_CreateGraph_Call) Run(run func(id string, _type providers.FlowType, version int)) *FlowFactoryInterfaceMock_CreateGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 providers.FlowType
		if args[1] != nil {
			arg1 = args[1].(providers.FlowType)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateGraph_Call) Return(graphInterface GraphInterface) *FlowFactoryInterfaceMock_CreateGraph_Call {
	_c.Call.Return(graphInterface)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateGraph_Call) RunAndReturn(run func(id string, _type providers.FlowType, version int) GraphInterface) *FlowFactoryInterfaceMock_CreateGraph_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterceptor provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CreateInterceptor(name string, isDefault bool, priority int) InterceptorInterface {
	ret := _mock.Called(name, isDefault, priority)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterceptor")
	}

	var r0 InterceptorInterface
	if returnFunc, ok := ret.Get(0).(func(string, bool, int) InterceptorInterface); ok {
		r0 = returnFunc(name, isDefault, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterceptorInterface)
		}
	}
	return r0
}

// FlowFactoryInterfaceMock_CreateInterceptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterceptor'
type FlowFactoryInterfaceMock_CreateInterceptor_Call struct {
	*mock.Call
}

// CreateInterceptor is a helper method to define mock.On call
//   - name string
//   - isDefault bool
//   - priority int
func (_e *FlowFactoryInterfaceMock_Expecter) CreateInterceptor(name interface{}, isDefault interface{}, priority interface{}) *FlowFactoryInterfaceMock_CreateInterceptor_Call {
	return &FlowFactoryInterfaceMock_CreateInterceptor_Call{Call: _e.mock.On("CreateInterceptor", name, isDefault, priority)}
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptor_Call) Run(run func(name string, isDefault bool, priority int)) *FlowFactoryInterfaceMock_CreateInterceptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptor_Call) Return(interceptorInterface InterceptorInterface) *FlowFactoryInterfaceMock_CreateInterceptor_Call {
	_c.Call.Return(interceptorInterface)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptor_Call) RunAndReturn(run func(name string, isDefault bool, priority int) InterceptorInterface) *FlowFactoryInterfaceMock_CreateInterceptor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInterceptorUnit provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CreateInterceptorUnit(name string, mode providers.InterceptorMode, scope providers.InterceptorScope, applyTo []string, properties map[string]interface{}) InterceptorUnitInterface {
	ret := _mock.Called(name, mode, scope, applyTo, properties)

	if len(ret) == 0 {
		panic("no return value specified for CreateInterceptorUnit")
	}

	var r0 InterceptorUnitInterface
	if returnFunc, ok := ret.Get(0).(func(string, providers.InterceptorMode, providers.InterceptorScope, []string, map[string]interface{}) InterceptorUnitInterface); ok {
		r0 = returnFunc(name, mode, scope, applyTo, properties)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterceptorUnitInterface)
		}
	}
	return r0
}

// FlowFactoryInterfaceMock_CreateInterceptorUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInterceptorUnit'
type FlowFactoryInterfaceMock_CreateInterceptorUnit_Call struct {
	*mock.Call
}

// CreateInterceptorUnit is a helper method to define mock.On call
//   - name string
//   - mode providers.InterceptorMode
//   - scope providers.InterceptorScope
//   - applyTo []string
//   - properties map[string]interface{}
func (_e *FlowFactoryInterfaceMock_Expecter) CreateInterceptorUnit(name interface{}, mode interface{}, scope interface{}, applyTo interface{}, properties interface{}) *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call {
	return &FlowFactoryInterfaceMock_CreateInterceptorUnit_Call{Call: _e.mock.On("CreateInterceptorUnit", name, mode, scope, applyTo, properties)}
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call) Run(run func(name string, mode providers.InterceptorMode, scope providers.InterceptorScope, applyTo []string, properties map[string]interface{})) *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 providers.InterceptorMode
		if args[1] != nil {
			arg1 = args[1].(providers.InterceptorMode)
		}
		var arg2 providers.InterceptorScope
		if args[2] != nil {
			arg2 = args[2].(providers.InterceptorScope)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call) Return(interceptorUnitInterface InterceptorUnitInterface) *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call {
	_c.Call.Return(interceptorUnitInterface)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call) RunAndReturn(run func(name string, mode providers.InterceptorMode, scope providers.InterceptorScope, applyTo []string, properties map[string]interface{}) InterceptorUnitInterface) *FlowFactoryInterfaceMock_CreateInterceptorUnit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNode provides a mock function for the type FlowFactoryInterfaceMock
func (_mock *FlowFactoryInterfaceMock) CreateNode(id string, _type string, properties map[string]interface{}, isStartNode bool, isFinalNode bool) (NodeInterface, error) {
	ret := _mock.Called(id, _type, properties, isStartNode, isFinalNode)

	if len(ret) == 0 {
		panic("no return value specified for CreateNode")
	}

	var r0 NodeInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, map[string]interface{}, bool, bool) (NodeInterface, error)); ok {
		return returnFunc(id, _type, properties, isStartNode, isFinalNode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, map[string]interface{}, bool, bool) NodeInterface); ok {
		r0 = returnFunc(id, _type, properties, isStartNode, isFinalNode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(NodeInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, map[string]interface{}, bool, bool) error); ok {
		r1 = returnFunc(id, _type, properties, isStartNode, isFinalNode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowFactoryInterfaceMock_CreateNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNode'
type FlowFactoryInterfaceMock_CreateNode_Call struct {
	*mock.Call
}

// CreateNode is a helper method to define mock.On call
//   - id string
//   - _type string
//   - properties map[string]interface{}
//   - isStartNode bool
//   - isFinalNode bool
func (_e *FlowFactoryInterfaceMock_Expecter) CreateNode(id interface{}, _type interface{}, properties interface{}, isStartNode interface{}, isFinalNode interface{}) *FlowFactoryInterfaceMock_CreateNode_Call {
	return &FlowFactoryInterfaceMock_CreateNode_Call{Call: _e.mock.On("CreateNode", id, _type, properties, isStartNode, isFinalNode)}
}

func (_c *FlowFactoryInterfaceMock_CreateNode_Call) Run(run func(id string, _type string, properties map[string]interface{}, isStartNode bool, isFinalNode bool)) *FlowFactoryInterfaceMock_CreateNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateNode_Call) Return(nodeInterface NodeInterface, err error) *FlowFactoryInterfaceMock_CreateNode_Call {
	_c.Call.Return(nodeInterface, err)
	return _c
}

func (_c *FlowFactoryInterfaceMock_CreateNode_Call) RunAndReturn(run func(id string, _type string, properties map[string]interface{}, isStartNode bool, isFinalNode bool) (NodeInterface, error)) *FlowFactoryInterfaceMock_CreateNode_Call {
	_c.Call.Return(run)
	return _c
}
