// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgtmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/flow/core"
	"github.com/thunder-id/thunderid/internal/flow/mgt"
	"github.com/thunder-id/thunderid/internal/system/resourcedependency"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// NewFlowMgtServiceInterfaceMock creates a new instance of FlowMgtServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowMgtServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowMgtServiceInterfaceMock {
	mock := &FlowMgtServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FlowMgtServiceInterfaceMock is an autogenerated mock type for the FlowMgtServiceInterface type
type FlowMgtServiceInterfaceMock struct {
	mock.Mock
}

type FlowMgtServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowMgtServiceInterfaceMock) EXPECT() *FlowMgtServiceInterfaceMock_Expecter {
	return &FlowMgtServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateFlow provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) CreateFlow(ctx context.Context, flowDef *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError) {
	ret := _mock.Called(ctx, flowDef)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlow")
	}

	var r0 *providers.CompleteFlowDefinition
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError)); ok {
		return returnFunc(ctx, flowDef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flowmgt.FlowDefinition) *providers.CompleteFlowDefinition); ok {
		r0 = returnFunc(ctx, flowDef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flowmgt.FlowDefinition) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowDef)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_CreateFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlow'
type FlowMgtServiceInterfaceMock_CreateFlow_Call struct {
	*mock.Call
}

// CreateFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - flowDef *flowmgt.FlowDefinition
func (_e *FlowMgtServiceInterfaceMock_Expecter) CreateFlow(ctx interface{}, flowDef interface{}) *FlowMgtServiceInterfaceMock_CreateFlow_Call {
	return &FlowMgtServiceInterfaceMock_CreateFlow_Call{Call: _e.mock.On("CreateFlow", ctx, flowDef)}
}

func (_c *FlowMgtServiceInterfaceMock_CreateFlow_Call) Run(run func(ctx context.Context, flowDef *flowmgt.FlowDefinition)) *FlowMgtServiceInterfaceMock_CreateFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flowmgt.FlowDefinition
		if args[1] != nil {
			arg1 = args[1].(*flowmgt.FlowDefinition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_CreateFlow_Call) Return(completeFlowDefinition *providers.CompleteFlowDefinition, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_CreateFlow_Call {
	_c.Call.Return(completeFlowDefinition, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_CreateFlow_Call) RunAndReturn(run func(ctx context.Context, flowDef *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError)) *FlowMgtServiceInterfaceMock_CreateFlow_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlow provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) DeleteFlow(ctx context.Context, flowID string) *common.ServiceError {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlow")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// FlowMgtServiceInterfaceMock_DeleteFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlow'
type FlowMgtServiceInterfaceMock_DeleteFlow_Call struct {
	*mock.Call
}

// DeleteFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) DeleteFlow(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_DeleteFlow_Call {
	return &FlowMgtServiceInterfaceMock_DeleteFlow_Call{Call: _e.mock.On("DeleteFlow", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_DeleteFlow_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_DeleteFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_DeleteFlow_Call) Return(serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_DeleteFlow_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_DeleteFlow_Call) RunAndReturn(run func(ctx context.Context, flowID string) *common.ServiceError) *FlowMgtServiceInterfaceMock_DeleteFlow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlow provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetFlow(ctx context.Context, flowID string) (*providers.CompleteFlowDefinition, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetFlow")
	}

	var r0 *providers.CompleteFlowDefinition
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.CompleteFlowDefinition, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.CompleteFlowDefinition); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlow'
type FlowMgtServiceInterfaceMock_GetFlow_Call struct {
	*mock.Call
}

// GetFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetFlow(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_GetFlow_Call {
	return &FlowMgtServiceInterfaceMock_GetFlow_Call{Call: _e.mock.On("GetFlow", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_GetFlow_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_GetFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlow_Call) Return(completeFlowDefinition *providers.CompleteFlowDefinition, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetFlow_Call {
	_c.Call.Return(completeFlowDefinition, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlow_Call) RunAndReturn(run func(ctx context.Context, flowID string) (*providers.CompleteFlowDefinition, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetFlow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowByHandle provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetFlowByHandle(ctx context.Context, handle string, flowType providers.FlowType) (*providers.CompleteFlowDefinition, *common.ServiceError) {
	ret := _mock.Called(ctx, handle, flowType)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowByHandle")
	}

	var r0 *providers.CompleteFlowDefinition
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.FlowType) (*providers.CompleteFlowDefinition, *common.ServiceError)); ok {
		return returnFunc(ctx, handle, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.FlowType) *providers.CompleteFlowDefinition); ok {
		r0 = returnFunc(ctx, handle, flowType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, providers.FlowType) *common.ServiceError); ok {
		r1 = returnFunc(ctx, handle, flowType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetFlowByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowByHandle'
type FlowMgtServiceInterfaceMock_GetFlowByHandle_Call struct {
	*mock.Call
}

// GetFlowByHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - handle string
//   - flowType providers.FlowType
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetFlowByHandle(ctx interface{}, handle interface{}, flowType interface{}) *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call {
	return &FlowMgtServiceInterfaceMock_GetFlowByHandle_Call{Call: _e.mock.On("GetFlowByHandle", ctx, handle, flowType)}
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call) Run(run func(ctx context.Context, handle string, flowType providers.FlowType)) *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 providers.FlowType
		if args[2] != nil {
			arg2 = args[2].(providers.FlowType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call) Return(completeFlowDefinition *providers.CompleteFlowDefinition, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Return(completeFlowDefinition, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call) RunAndReturn(run func(ctx context.Context, handle string, flowType providers.FlowType) (*providers.CompleteFlowDefinition, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowUsages provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetFlowUsages(ctx context.Context, flowID string) (*resourcedependency.DependenciesResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowUsages")
	}

	var r0 *resourcedependency.DependenciesResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*resourcedependency.DependenciesResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *resourcedependency.DependenciesResponse); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcedependency.DependenciesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetFlowUsages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowUsages'
type FlowMgtServiceInterfaceMock_GetFlowUsages_Call struct {
	*mock.Call
}

// GetFlowUsages is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetFlowUsages(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_GetFlowUsages_Call {
	return &FlowMgtServiceInterfaceMock_GetFlowUsages_Call{Call: _e.mock.On("GetFlowUsages", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowUsages_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_GetFlowUsages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowUsages_Call) Return(dependenciesResponse *resourcedependency.DependenciesResponse, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetFlowUsages_Call {
	_c.Call.Return(dependenciesResponse, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowUsages_Call) RunAndReturn(run func(ctx context.Context, flowID string) (*resourcedependency.DependenciesResponse, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetFlowUsages_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowVersion provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetFlowVersion(ctx context.Context, flowID string, version int) (*flowmgt.FlowVersion, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowVersion")
	}

	var r0 *flowmgt.FlowVersion
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*flowmgt.FlowVersion, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *flowmgt.FlowVersion); ok {
		r0 = returnFunc(ctx, flowID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.FlowVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID, version)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetFlowVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowVersion'
type FlowMgtServiceInterfaceMock_GetFlowVersion_Call struct {
	*mock.Call
}

// GetFlowVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
//   - version int
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetFlowVersion(ctx interface{}, flowID interface{}, version interface{}) *FlowMgtServiceInterfaceMock_GetFlowVersion_Call {
	return &FlowMgtServiceInterfaceMock_GetFlowVersion_Call{Call: _e.mock.On("GetFlowVersion", ctx, flowID, version)}
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowVersion_Call) Run(run func(ctx context.Context, flowID string, version int)) *FlowMgtServiceInterfaceMock_GetFlowVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowVersion_Call) Return(flowVersion *flowmgt.FlowVersion, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetFlowVersion_Call {
	_c.Call.Return(flowVersion, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetFlowVersion_Call) RunAndReturn(run func(ctx context.Context, flowID string, version int) (*flowmgt.FlowVersion, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetFlowVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetGraph provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetGraph(ctx context.Context, flowID string) (core.GraphInterface, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetGraph")
	}

	var r0 core.GraphInterface
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (core.GraphInterface, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.GraphInterface); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GraphInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraph'
type FlowMgtServiceInterfaceMock_GetGraph_Call struct {
	*mock.Call
}

// GetGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetGraph(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_GetGraph_Call {
	return &FlowMgtServiceInterfaceMock_GetGraph_Call{Call: _e.mock.On("GetGraph", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_GetGraph_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetGraph_Call) Return(graphInterface core.GraphInterface, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Return(graphInterface, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetGraph_Call) RunAndReturn(run func(ctx context.Context, flowID string) (core.GraphInterface, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetGraph_Call {
	_c.Call.Return(run)
	return _c
}

// GetReachableCallTargets provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetReachableCallTargets(ctx context.Context, flowID string) ([]flowmgt.CallTarget, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetReachableCallTargets")
	}

	var r0 []flowmgt.CallTarget
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]flowmgt.CallTarget, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []flowmgt.CallTarget); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flowmgt.CallTarget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReachableCallTargets'
type FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call struct {
	*mock.Call
}

// GetReachableCallTargets is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetReachableCallTargets(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call {
	return &FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call{Call: _e.mock.On("GetReachableCallTargets", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call) Return(callTargets []flowmgt.CallTarget, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call {
	_c.Call.Return(callTargets, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call) RunAndReturn(run func(ctx context.Context, flowID string) ([]flowmgt.CallTarget, *common.ServiceError)) *FlowMgtServiceInterfaceMock_GetReachableCallTargets_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceDependencies provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) GetResourceDependencies(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error) {
	ret := _mock.Called(ctx, resourceType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceDependencies")
	}

	var r0 []resourcedependency.ResourceDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]resourcedependency.ResourceDependency, error)); ok {
		return returnFunc(ctx, resourceType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []resourcedependency.ResourceDependency); ok {
		r0 = returnFunc(ctx, resourceType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourcedependency.ResourceDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceType, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_GetResourceDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceDependencies'
type FlowMgtServiceInterfaceMock_GetResourceDependencies_Call struct {
	*mock.Call
}

// GetResourceDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - id string
func (_e *FlowMgtServiceInterfaceMock_Expecter) GetResourceDependencies(ctx interface{}, resourceType interface{}, id interface{}) *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call {
	return &FlowMgtServiceInterfaceMock_GetResourceDependencies_Call{Call: _e.mock.On("GetResourceDependencies", ctx, resourceType, id)}
}

func (_c *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call) Run(run func(ctx context.Context, resourceType string, id string)) *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call) Return(resourceDependencys []resourcedependency.ResourceDependency, err error) *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(resourceDependencys, err)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call) RunAndReturn(run func(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error)) *FlowMgtServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidFlow provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) IsValidFlow(ctx context.Context, flowID string, flowType providers.FlowType) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID, flowType)

	if len(ret) == 0 {
		panic("no return value specified for IsValidFlow")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.FlowType) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.FlowType) bool); ok {
		r0 = returnFunc(ctx, flowID, flowType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, providers.FlowType) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID, flowType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_IsValidFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidFlow'
type FlowMgtServiceInterfaceMock_IsValidFlow_Call struct {
	*mock.Call
}

// IsValidFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
//   - flowType providers.FlowType
func (_e *FlowMgtServiceInterfaceMock_Expecter) IsValidFlow(ctx interface{}, flowID interface{}, flowType interface{}) *FlowMgtServiceInterfaceMock_IsValidFlow_Call {
	return &FlowMgtServiceInterfaceMock_IsValidFlow_Call{Call: _e.mock.On("IsValidFlow", ctx, flowID, flowType)}
}

func (_c *FlowMgtServiceInterfaceMock_IsValidFlow_Call) Run(run func(ctx context.Context, flowID string, flowType providers.FlowType)) *FlowMgtServiceInterfaceMock_IsValidFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 providers.FlowType
		if args[2] != nil {
			arg2 = args[2].(providers.FlowType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_IsValidFlow_Call) Return(b bool, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_IsValidFlow_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_IsValidFlow_Call) RunAndReturn(run func(ctx context.Context, flowID string, flowType providers.FlowType) (bool, *common.ServiceError)) *FlowMgtServiceInterfaceMock_IsValidFlow_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlowVersions provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) ListFlowVersions(ctx context.Context, flowID string) (*flowmgt.FlowVersionListResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for ListFlowVersions")
	}

	var r0 *flowmgt.FlowVersionListResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*flowmgt.FlowVersionListResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *flowmgt.FlowVersionListResponse); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.FlowVersionListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_ListFlowVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlowVersions'
type FlowMgtServiceInterfaceMock_ListFlowVersions_Call struct {
	*mock.Call
}

// ListFlowVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *FlowMgtServiceInterfaceMock_Expecter) ListFlowVersions(ctx interface{}, flowID interface{}) *FlowMgtServiceInterfaceMock_ListFlowVersions_Call {
	return &FlowMgtServiceInterfaceMock_ListFlowVersions_Call{Call: _e.mock.On("ListFlowVersions", ctx, flowID)}
}

func (_c *FlowMgtServiceInterfaceMock_ListFlowVersions_Call) Run(run func(ctx context.Context, flowID string)) *FlowMgtServiceInterfaceMock_ListFlowVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_ListFlowVersions_Call) Return(flowVersionListResponse *flowmgt.FlowVersionListResponse, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_ListFlowVersions_Call {
	_c.Call.Return(flowVersionListResponse, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_ListFlowVersions_Call) RunAndReturn(run func(ctx context.Context, flowID string) (*flowmgt.FlowVersionListResponse, *common.ServiceError)) *FlowMgtServiceInterfaceMock_ListFlowVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlows provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) ListFlows(ctx context.Context, limit int, offset int, flowType providers.FlowType) (*flowmgt.FlowListResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, limit, offset, flowType)

	if len(ret) == 0 {
		panic("no return value specified for ListFlows")
	}

	var r0 *flowmgt.FlowListResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, providers.FlowType) (*flowmgt.FlowListResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, limit, offset, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, providers.FlowType) *flowmgt.FlowListResponse); ok {
		r0 = returnFunc(ctx, limit, offset, flowType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.FlowListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, providers.FlowType) *common.ServiceError); ok {
		r1 = returnFunc(ctx, limit, offset, flowType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_ListFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlows'
type FlowMgtServiceInterfaceMock_ListFlows_Call struct {
	*mock.Call
}

// ListFlows is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - flowType providers.FlowType
func (_e *FlowMgtServiceInterfaceMock_Expecter) ListFlows(ctx interface{}, limit interface{}, offset interface{}, flowType interface{}) *FlowMgtServiceInterfaceMock_ListFlows_Call {
	return &FlowMgtServiceInterfaceMock_ListFlows_Call{Call: _e.mock.On("ListFlows", ctx, limit, offset, flowType)}
}

func (_c *FlowMgtServiceInterfaceMock_ListFlows_Call) Run(run func(ctx context.Context, limit int, offset int, flowType providers.FlowType)) *FlowMgtServiceInterfaceMock_ListFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 providers.FlowType
		if args[3] != nil {
			arg3 = args[3].(providers.FlowType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_ListFlows_Call) Return(flowListResponse *flowmgt.FlowListResponse, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_ListFlows_Call {
	_c.Call.Return(flowListResponse, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_ListFlows_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, flowType providers.FlowType) (*flowmgt.FlowListResponse, *common.ServiceError)) *FlowMgtServiceInterfaceMock_ListFlows_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreFlowVersion provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) RestoreFlowVersion(ctx context.Context, flowID string, version int) (*providers.CompleteFlowDefinition, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID, version)

	if len(ret) == 0 {
		panic("no return value specified for RestoreFlowVersion")
	}

	var r0 *providers.CompleteFlowDefinition
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*providers.CompleteFlowDefinition, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *providers.CompleteFlowDefinition); ok {
		r0 = returnFunc(ctx, flowID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID, version)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreFlowVersion'
type FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call struct {
	*mock.Call
}

// RestoreFlowVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
//   - version int
func (_e *FlowMgtServiceInterfaceMock_Expecter) RestoreFlowVersion(ctx interface{}, flowID interface{}, version interface{}) *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call {
	return &FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call{Call: _e.mock.On("RestoreFlowVersion", ctx, flowID, version)}
}

func (_c *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call) Run(run func(ctx context.Context, flowID string, version int)) *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call) Return(completeFlowDefinition *providers.CompleteFlowDefinition, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Return(completeFlowDefinition, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call) RunAndReturn(run func(ctx context.Context, flowID string, version int) (*providers.CompleteFlowDefinition, *common.ServiceError)) *FlowMgtServiceInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetDependencyRegistry provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) SetDependencyRegistry(r resourcedependency.Registry) {
	_mock.Called(r)
	return
}

// FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDependencyRegistry'
type FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call struct {
	*mock.Call
}

// SetDependencyRegistry is a helper method to define mock.On call
//   - r resourcedependency.Registry
func (_e *FlowMgtServiceInterfaceMock_Expecter) SetDependencyRegistry(r interface{}) *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call {
	return &FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call{Call: _e.mock.On("SetDependencyRegistry", r)}
}

func (_c *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call) Run(run func(r resourcedependency.Registry)) *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resourcedependency.Registry
		if args[0] != nil {
			arg0 = args[0].(resourcedependency.Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call) Return() *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Return()
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call) RunAndReturn(run func(r resourcedependency.Registry)) *FlowMgtServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Run(run)
	return _c
}

// UpdateFlow provides a mock function for the type FlowMgtServiceInterfaceMock
func (_mock *FlowMgtServiceInterfaceMock) UpdateFlow(ctx context.Context, flowID string, flowDef *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError) {
	ret := _mock.Called(ctx, flowID, flowDef)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlow")
	}

	var r0 *providers.CompleteFlowDefinition
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError)); ok {
		return returnFunc(ctx, flowID, flowDef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *flowmgt.FlowDefinition) *providers.CompleteFlowDefinition); ok {
		r0 = returnFunc(ctx, flowID, flowDef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *flowmgt.FlowDefinition) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowID, flowDef)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// FlowMgtServiceInterfaceMock_UpdateFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlow'
type FlowMgtServiceInterfaceMock_UpdateFlow_Call struct {
	*mock.Call
}

// UpdateFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
//   - flowDef *flowmgt.FlowDefinition
func (_e *FlowMgtServiceInterfaceMock_Expecter) UpdateFlow(ctx interface{}, flowID interface{}, flowDef interface{}) *FlowMgtServiceInterfaceMock_UpdateFlow_Call {
	return &FlowMgtServiceInterfaceMock_UpdateFlow_Call{Call: _e.mock.On("UpdateFlow", ctx, flowID, flowDef)}
}

func (_c *FlowMgtServiceInterfaceMock_UpdateFlow_Call) Run(run func(ctx context.Context, flowID string, flowDef *flowmgt.FlowDefinition)) *FlowMgtServiceInterfaceMock_UpdateFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *flowmgt.FlowDefinition
		if args[2] != nil {
			arg2 = args[2].(*flowmgt.FlowDefinition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_UpdateFlow_Call) Return(completeFlowDefinition *providers.CompleteFlowDefinition, serviceError *common.ServiceError) *FlowMgtServiceInterfaceMock_UpdateFlow_Call {
	_c.Call.Return(completeFlowDefinition, serviceError)
	return _c
}

func (_c *FlowMgtServiceInterfaceMock_UpdateFlow_Call) RunAndReturn(run func(ctx context.Context, flowID string, flowDef *flowmgt.FlowDefinition) (*providers.CompleteFlowDefinition, *common.ServiceError)) *FlowMgtServiceInterfaceMock_UpdateFlow_Call {
	_c.Call.Return(run)
	return _c
}
