// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgtmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/flow/core"
	"github.com/thunder-id/thunderid/internal/flow/mgt"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// newGraphBuilderInterfaceMock creates a new instance of graphBuilderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newGraphBuilderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *graphBuilderInterfaceMock {
	mock := &graphBuilderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// graphBuilderInterfaceMock is an autogenerated mock type for the graphBuilderInterface type
type graphBuilderInterfaceMock struct {
	mock.Mock
}

type graphBuilderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *graphBuilderInterfaceMock) EXPECT() *graphBuilderInterfaceMock_Expecter {
	return &graphBuilderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetGraph provides a mock function for the type graphBuilderInterfaceMock
func (_mock *graphBuilderInterfaceMock) GetGraph(ctx context.Context, flow *flowmgt.CompleteFlowDefinition) (core.GraphInterface, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, flow)

	if len(ret) == 0 {
		panic("no return value specified for GetGraph")
	}

	var r0 core.GraphInterface
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flowmgt.CompleteFlowDefinition) (core.GraphInterface, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, flow)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flowmgt.CompleteFlowDefinition) core.GraphInterface); ok {
		r0 = returnFunc(ctx, flow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GraphInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flowmgt.CompleteFlowDefinition) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, flow)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// graphBuilderInterfaceMock_GetGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraph'
type graphBuilderInterfaceMock_GetGraph_Call struct {
	*mock.Call
}

// GetGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - flow *flowmgt.CompleteFlowDefinition
func (_e *graphBuilderInterfaceMock_Expecter) GetGraph(ctx interface{}, flow interface{}) *graphBuilderInterfaceMock_GetGraph_Call {
	return &graphBuilderInterfaceMock_GetGraph_Call{Call: _e.mock.On("GetGraph", ctx, flow)}
}

func (_c *graphBuilderInterfaceMock_GetGraph_Call) Run(run func(ctx context.Context, flow *flowmgt.CompleteFlowDefinition)) *graphBuilderInterfaceMock_GetGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flowmgt.CompleteFlowDefinition
		if args[1] != nil {
			arg1 = args[1].(*flowmgt.CompleteFlowDefinition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *graphBuilderInterfaceMock_GetGraph_Call) Return(graphInterface core.GraphInterface, serviceError *serviceerror.ServiceError) *graphBuilderInterfaceMock_GetGraph_Call {
	_c.Call.Return(graphInterface, serviceError)
	return _c
}

func (_c *graphBuilderInterfaceMock_GetGraph_Call) RunAndReturn(run func(ctx context.Context, flow *flowmgt.CompleteFlowDefinition) (core.GraphInterface, *serviceerror.ServiceError)) *graphBuilderInterfaceMock_GetGraph_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCache provides a mock function for the type graphBuilderInterfaceMock
func (_mock *graphBuilderInterfaceMock) InvalidateCache(ctx context.Context, flowID string) {
	_mock.Called(ctx, flowID)
	return
}

// graphBuilderInterfaceMock_InvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCache'
type graphBuilderInterfaceMock_InvalidateCache_Call struct {
	*mock.Call
}

// InvalidateCache is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *graphBuilderInterfaceMock_Expecter) InvalidateCache(ctx interface{}, flowID interface{}) *graphBuilderInterfaceMock_InvalidateCache_Call {
	return &graphBuilderInterfaceMock_InvalidateCache_Call{Call: _e.mock.On("InvalidateCache", ctx, flowID)}
}

func (_c *graphBuilderInterfaceMock_InvalidateCache_Call) Run(run func(ctx context.Context, flowID string)) *graphBuilderInterfaceMock_InvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *graphBuilderInterfaceMock_InvalidateCache_Call) Return() *graphBuilderInterfaceMock_InvalidateCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *graphBuilderInterfaceMock_InvalidateCache_Call) RunAndReturn(run func(ctx context.Context, flowID string)) *graphBuilderInterfaceMock_InvalidateCache_Call {
	_c.Run(run)
	return _c
}
