-- Table to store OAuth2 CIBA (Client-Initiated Backchannel Authentication) requests.
CREATE TABLE "CIBA_AUTH_REQUEST" (
    AUTH_REQ_ID        VARCHAR(36)  NOT NULL,
    DEPLOYMENT_ID      VARCHAR(255) NOT NULL,
    CLIENT_ID          VARCHAR(255) NOT NULL,
    USER_ID            VARCHAR(36),
    STANDARD_SCOPES    TEXT         NOT NULL,
    STATE              VARCHAR(50)  NOT NULL,
    AUTHORIZED_SCOPES  TEXT,
    ATTRIBUTE_CACHE_ID VARCHAR(36),
    COMPLETED_ACR      VARCHAR(255),
    AUTH_TIME          TIMESTAMP,
    LAST_POLLED_AT     TIMESTAMP,
    EXPIRY_TIME        TIMESTAMP    NOT NULL,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AUTH_REQ_ID, DEPLOYMENT_ID)
);

-- Index for expiry time on CIBA_AUTH_REQUEST (supports cleanup and expiry checks)
CREATE INDEX idx_ciba_auth_request_expiry_time ON "CIBA_AUTH_REQUEST" (EXPIRY_TIME);

-- Table to store WebAuthn session data
CREATE TABLE "WEBAUTHN_SESSION" (
    SESSION_KEY VARCHAR(255) NOT NULL,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    SESSION_DATA JSONB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (SESSION_KEY, DEPLOYMENT_ID)
);

-- Index for expiry time on WEBAUTHN_SESSION
CREATE INDEX idx_webauthn_session_expiry_time ON "WEBAUTHN_SESSION" (EXPIRY_TIME);

-- Table to store short-lived OpenID4VP verifier request state.
CREATE TABLE "OPENID4VP_REQUEST_STATE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    STATE VARCHAR(64) PRIMARY KEY,
    DEFINITION_ID VARCHAR(255),
    NONCE VARCHAR(128),
    EPHEMERAL_KEY BYTEA,
    CLIENT_ID VARCHAR(255),
    RP_ID VARCHAR(255),
    REQUEST_URI TEXT,
    STATUS VARCHAR(16),
    RESULT JSONB,
    FAILURE_REASON TEXT,
    EXPIRY_TIME TIMESTAMP NOT NULL
);

-- Index for expiry time on OPENID4VP_REQUEST_STATE (supports cleanup and expiry checks)
CREATE INDEX idx_openid4vp_request_state_expiry_time ON "OPENID4VP_REQUEST_STATE" (EXPIRY_TIME);

-- Table to store short-lived OpenID4VCI c_nonces.
CREATE TABLE "OPENID4VCI_NONCE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NONCE VARCHAR(255) PRIMARY KEY,
    EXPIRY_TIME TIMESTAMP NOT NULL
);

-- Index for expiry time on OPENID4VCI_NONCE (supports cleanup and expiry checks)
CREATE INDEX idx_openid4vci_nonce_expiry_time ON "OPENID4VCI_NONCE" (EXPIRY_TIME);

-- Table to store short-lived issuer-initiated credential offers.
CREATE TABLE "OPENID4VCI_CREDENTIAL_OFFER" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID VARCHAR(255) PRIMARY KEY,
    OFFER JSONB NOT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL
);

-- Index for expiry time on OPENID4VCI_CREDENTIAL_OFFER (supports cleanup and expiry checks)
CREATE INDEX idx_openid4vci_offer_expiry_time ON "OPENID4VCI_CREDENTIAL_OFFER" (EXPIRY_TIME);

-- Table to store generic runtime key-value entries, partitioned by NAMESPACE.
CREATE TABLE "RUNTIME_STORE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAMESPACE     VARCHAR(64)  NOT NULL,
    KEY           VARCHAR(512) NOT NULL,
    VALUE         JSONB        NOT NULL,
    EXPIRY_TIME   TIMESTAMP,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEPLOYMENT_ID, NAMESPACE, KEY)
) PARTITION BY LIST (NAMESPACE);

-- One child partition per providers.RuntimeStoreNamespace constant.
-- Adding a new namespace constant REQUIRES adding a matching partition here.
CREATE TABLE "RUNTIME_STORE_ATTRIBUTE_CACHE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('attribute:cache');
CREATE TABLE "RUNTIME_STORE_FLOW_STATE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('flow:state');
CREATE TABLE "RUNTIME_STORE_AUTHZ_CODE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('authz:code');
CREATE TABLE "RUNTIME_STORE_AUTHZ_REQ"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('authz:req');
CREATE TABLE "RUNTIME_STORE_PAR_REQ"    PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('par:req');
CREATE TABLE "RUNTIME_STORE_CIBA_REQ"   PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('ciba:req');
CREATE TABLE "RUNTIME_STORE_JTI_TOKEN"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('jti:token');
CREATE TABLE "RUNTIME_STORE_VCI_NONCE"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vci:nonce');
CREATE TABLE "RUNTIME_STORE_VCI_OFFER"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vci:offer');
CREATE TABLE "RUNTIME_STORE_VP_STATE"   PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vp:state');

-- Index for expiry time on RUNTIME_STORE (propagates to all partitions; supports cleanup and expiry checks)
CREATE INDEX idx_runtime_store_expiry_time ON "RUNTIME_STORE" (EXPIRY_TIME);
