/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package revocation

import "time"

// RevokeOutcome is the protocol-level result of a revocation request, mapped to HTTP by the handler.
type RevokeOutcome int

const (
	// RevokeOutcomeRevoked indicates success — the token was revoked, or it was invalid/expired/unknown
	// and treated as a no-op success per RFC 7009 §2.2. Maps to HTTP 200.
	RevokeOutcomeRevoked RevokeOutcome = iota
	// RevokeOutcomeNotOwned indicates the token was issued to a different client. Maps to 400 invalid_grant.
	RevokeOutcomeNotOwned
)

// RevocationReason enumerates why a single token was revoked.
type RevocationReason string

const (
	// RevocationReasonExplicit denotes a client/admin-initiated revocation (RFC 7009).
	RevocationReasonExplicit RevocationReason = "explicit"
	// RevocationReasonRefreshRotation denotes revocation of a consumed refresh token on rotation.
	RevocationReasonRefreshRotation RevocationReason = "refresh_rotation"
)

// RevokedToken represents a single revoked token entry in the deny list.
type RevokedToken struct {
	// ID is the surrogate UUID v7 primary key. Generated by the store when empty.
	ID string
	// JTI is the jti claim of the revoked token and the deny-list lookup key.
	JTI string
	// RevocationReason records why the token was revoked.
	RevocationReason RevocationReason
	// RevokedAt is the time the revocation was recorded.
	RevokedAt time.Time
	// ExpiryTime is the revoked token's original expiry; the row is removable once this passes.
	ExpiryTime time.Time
}
