// Copyright 2026 The ThunderID Authors
// SPDX-License-Identifier: Apache-2.0

package revocation

import (
	"context"
	"fmt"
	"time"

	"github.com/thunder-id/thunderid/internal/system/database/provider"
	"github.com/thunder-id/thunderid/internal/system/deployment"
	"github.com/thunder-id/thunderid/internal/system/utils"
)

// revokedTokenEntry is a matched row from the single-token deny list. It carries only what the
// enforcement service needs to decide between an ordinary denial and one still inside the refresh
// rotation grace window.
type revokedTokenEntry struct {
	// RevokedAt is when the revocation was recorded. For a rotation this is the instant of
	// rotation, and it anchors the grace window: the insert is idempotent, so it is written once
	// and never moved by a later redemption.
	RevokedAt time.Time
	// Reason records why the token was revoked. Only refresh_rotation is eligible for grace.
	Reason RevocationReason
}

// revocationCriterion is a single criteria-based (many-token) revocation entry.
type revocationCriterion struct {
	// ID is the surrogate UUID v7 primary key. Generated by the store when empty.
	ID string
	// Type is the criterion dimension (e.g. token_family).
	Type CriterionType
	// Value is the revoked value for the dimension (the tfid for token_family).
	Value string
	// Reason records why the criterion was revoked.
	Reason RevocationReason
	// RevokedAt is the time the revocation was recorded.
	RevokedAt time.Time
	// ExpiryTime bounds the entry; the row is removable once every token it could match has expired.
	ExpiryTime time.Time
}

// revocationStoreInterface defines the deny-list persistence for the revocation feature: the
// single-token deny list (InsertRevokedToken / IsTokenRevoked, by jti) written by the RFC 7009
// revocation service, and the criteria (many-token) deny list (insertCriterion / isCriterionRevoked,
// by criterion) written by the family revoker. Both read paths are consulted by the enforcement
// service on the AS hot path. The constructor is unexported so neither write path can be reached from
// outside the package, bypassing the revocation service's and revoker's validation and ownership.
type revocationStoreInterface interface {
	// InsertRevokedToken writes a JTI to the deny list. The write is idempotent.
	InsertRevokedToken(ctx context.Context, token RevokedToken) error
	// IsTokenRevoked returns the non-expired deny-list entry for the given JTI, or nil when the
	// token is not denied. The entry carries the revocation time and reason so callers can derive
	// the refresh rotation grace window without a second lookup.
	IsTokenRevoked(ctx context.Context, jti string) (*revokedTokenEntry, error)
	// insertCriterion records a criteria-based revocation. The write is idempotent per
	// (deployment, type, value).
	insertCriterion(ctx context.Context, criterion revocationCriterion) error
	// areCriteriaRevoked reports whether a non-expired criteria entry exists for any of the supplied
	// (type, value) pairs, in a single round trip. An empty slice is not revoked.
	areCriteriaRevoked(ctx context.Context, criteria []Criterion, establishedAt time.Time) (bool, error)
}

// revocationStore implements revocationStoreInterface against the runtime persistent database.
type revocationStore struct {
	dbProvider provider.DBProviderInterface
}

// scope returns the deployment id this request acts for. The id is put on the context at the
// edge, so a request scopes by what it names; a context that never passed through the edge,
// such as a start-up task or a background job, falls back to the configured identifier.
func (s *revocationStore) scope(ctx context.Context) string {
	return deployment.Resolve(ctx)
}

// newRevocationStore creates a new revocationStore. It is intentionally unexported so the deny-list
// write paths cannot be reached from outside the package, bypassing the revocation service's and
// family revoker's validation and ownership checks.
func newRevocationStore() revocationStoreInterface {
	return &revocationStore{
		dbProvider: provider.GetDBProvider(),
	}
}

// InsertRevokedToken writes a JTI to the deny list. A duplicate (deployment, jti) is a no-op.
// A UUID v7 surrogate primary key is generated when the token has no ID.
func (s *revocationStore) InsertRevokedToken(ctx context.Context, token RevokedToken) error {
	dbClient, err := s.dbProvider.GetRuntimePersistentDBClient()
	if err != nil {
		return fmt.Errorf("failed to get runtime persistent database client: %w", err)
	}

	id := token.ID
	if id == "" {
		id, err = utils.GenerateUUIDv7()
		if err != nil {
			return fmt.Errorf("failed to generate revoked token id: %w", err)
		}
	}

	_, err = dbClient.ExecuteContext(ctx, queryInsertRevokedToken, id, token.JTI,
		string(token.RevocationReason), token.RevokedAt, token.ExpiryTime, s.scope(ctx))
	if err != nil {
		return fmt.Errorf("error inserting revoked token: %w", err)
	}

	return nil
}

// IsTokenRevoked returns the non-expired deny-list entry for the given JTI, or nil when no such
// entry exists. A row whose revocation time or reason cannot be read is still a denial: the entry is
// returned with a zero RevokedAt, which no grace window can contain, so a data fault closes the
// window rather than opening it.
func (s *revocationStore) IsTokenRevoked(ctx context.Context, jti string) (*revokedTokenEntry, error) {
	dbClient, err := s.dbProvider.GetRuntimePersistentDBClient()
	if err != nil {
		return nil, fmt.Errorf("failed to get runtime persistent database client: %w", err)
	}

	results, err := dbClient.QueryContext(ctx, queryIsTokenRevoked, jti, time.Now().UTC(), s.scope(ctx))
	if err != nil {
		return nil, fmt.Errorf("error checking token revocation: %w", err)
	}
	if len(results) == 0 {
		return nil, nil
	}

	return buildRevokedTokenEntry(results[0]), nil
}

// buildRevokedTokenEntry reads the revocation time and reason from a deny-list row. Unreadable
// values yield a zero RevokedAt and an empty reason, which fail every grace condition, so the
// entry denies as an ordinary revocation.
func buildRevokedTokenEntry(row map[string]interface{}) *revokedTokenEntry {
	entry := &revokedTokenEntry{}
	if reason, ok := row["revocation_reason"].(string); ok {
		entry.Reason = RevocationReason(reason)
	}
	if revokedAt, err := utils.ParseDBTimeField(row["revoked_at"], "revoked_at"); err == nil {
		entry.RevokedAt = revokedAt
	}
	return entry
}

// insertCriterion records a criteria-based revocation. A duplicate (deployment, type, value) refreshes
// the reason and time bounds. A UUID v7 surrogate primary key is generated when none is supplied.
func (s *revocationStore) insertCriterion(ctx context.Context, criterion revocationCriterion) error {
	dbClient, err := s.dbProvider.GetRuntimePersistentDBClient()
	if err != nil {
		return fmt.Errorf("failed to get runtime persistent database client: %w", err)
	}

	id := criterion.ID
	if id == "" {
		id, err = utils.GenerateUUIDv7()
		if err != nil {
			return fmt.Errorf("failed to generate revocation criterion id: %w", err)
		}
	}

	_, err = dbClient.ExecuteContext(ctx, queryInsertRevocationCriterion, id, string(criterion.Type),
		criterion.Value, string(criterion.Reason), criterion.RevokedAt, criterion.ExpiryTime, s.scope(ctx))
	if err != nil {
		return fmt.Errorf("error inserting revocation criterion: %w", err)
	}

	return nil
}

// areCriteriaRevoked reports whether a non-expired criteria entry exists for any supplied
// (type, value) pair. All dimensions are checked in one query so token validation costs a single
// round trip regardless of how many criteria the artifact carries.
func (s *revocationStore) areCriteriaRevoked(ctx context.Context, criteria []Criterion,
	establishedAt time.Time) (bool, error) {
	if len(criteria) == 0 {
		return false, nil
	}

	dbClient, err := s.dbProvider.GetRuntimePersistentDBClient()
	if err != nil {
		return false, fmt.Errorf("failed to get runtime persistent database client: %w", err)
	}

	query, args := buildCriteriaRevokedQuery(criteria, establishedAt, time.Now().UTC(), s.scope(ctx))
	results, err := dbClient.QueryContext(ctx, query, args...)
	if err != nil {
		return false, fmt.Errorf("error checking revocation criteria: %w", err)
	}

	return len(results) > 0, nil
}
