// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmeta

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewFlowMetaServiceInterfaceMock creates a new instance of FlowMetaServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowMetaServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowMetaServiceInterfaceMock {
	mock := &FlowMetaServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FlowMetaServiceInterfaceMock is an autogenerated mock type for the FlowMetaServiceInterface type
type FlowMetaServiceInterfaceMock struct {
	mock.Mock
}

type FlowMetaServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowMetaServiceInterfaceMock) EXPECT() *FlowMetaServiceInterfaceMock_Expecter {
	return &FlowMetaServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetFlowMetadata provides a mock function for the type FlowMetaServiceInterfaceMock
func (_mock *FlowMetaServiceInterfaceMock) GetFlowMetadata(ctx context.Context, metaType MetaType, id string, language *string, namespace *string) (*FlowMetadataResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, metaType, id, language, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowMetadata")
	}

	var r0 *FlowMetadataResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, MetaType, string, *string, *string) (*FlowMetadataResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, metaType, id, language, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, MetaType, string, *string, *string) *FlowMetadataResponse); ok {
		r0 = returnFunc(ctx, metaType, id, language, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FlowMetadataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, MetaType, string, *string, *string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, metaType, id, language, namespace)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// FlowMetaServiceInterfaceMock_GetFlowMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowMetadata'
type FlowMetaServiceInterfaceMock_GetFlowMetadata_Call struct {
	*mock.Call
}

// GetFlowMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - metaType MetaType
//   - id string
//   - language *string
//   - namespace *string
func (_e *FlowMetaServiceInterfaceMock_Expecter) GetFlowMetadata(ctx interface{}, metaType interface{}, id interface{}, language interface{}, namespace interface{}) *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call {
	return &FlowMetaServiceInterfaceMock_GetFlowMetadata_Call{Call: _e.mock.On("GetFlowMetadata", ctx, metaType, id, language, namespace)}
}

func (_c *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call) Run(run func(ctx context.Context, metaType MetaType, id string, language *string, namespace *string)) *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 MetaType
		if args[1] != nil {
			arg1 = args[1].(MetaType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call) Return(flowMetadataResponse *FlowMetadataResponse, serviceError *serviceerror.ServiceError) *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call {
	_c.Call.Return(flowMetadataResponse, serviceError)
	return _c
}

func (_c *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call) RunAndReturn(run func(ctx context.Context, metaType MetaType, id string, language *string, namespace *string) (*FlowMetadataResponse, *serviceerror.ServiceError)) *FlowMetaServiceInterfaceMock_GetFlowMetadata_Call {
	_c.Call.Return(run)
	return _c
}
