// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package magiclinkmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/entityprovider"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewMagicLinkAuthnServiceInterfaceMock creates a new instance of MagicLinkAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMagicLinkAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MagicLinkAuthnServiceInterfaceMock {
	mock := &MagicLinkAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MagicLinkAuthnServiceInterfaceMock is an autogenerated mock type for the MagicLinkAuthnServiceInterface type
type MagicLinkAuthnServiceInterfaceMock struct {
	mock.Mock
}

type MagicLinkAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MagicLinkAuthnServiceInterfaceMock) EXPECT() *MagicLinkAuthnServiceInterfaceMock_Expecter {
	return &MagicLinkAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GenerateMagicLink provides a mock function for the type MagicLinkAuthnServiceInterfaceMock
func (_mock *MagicLinkAuthnServiceInterfaceMock) GenerateMagicLink(ctx context.Context, subject string, expirySeconds int64, queryParams map[string]string, additionalClaims map[string]interface{}, magicLinkURL string) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, subject, expirySeconds, queryParams, additionalClaims, magicLinkURL)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMagicLink")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, map[string]string, map[string]interface{}, string) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, subject, expirySeconds, queryParams, additionalClaims, magicLinkURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, map[string]string, map[string]interface{}, string) string); ok {
		r0 = returnFunc(ctx, subject, expirySeconds, queryParams, additionalClaims, magicLinkURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, map[string]string, map[string]interface{}, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, subject, expirySeconds, queryParams, additionalClaims, magicLinkURL)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMagicLink'
type MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call struct {
	*mock.Call
}

// GenerateMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - expirySeconds int64
//   - queryParams map[string]string
//   - additionalClaims map[string]interface{}
//   - magicLinkURL string
func (_e *MagicLinkAuthnServiceInterfaceMock_Expecter) GenerateMagicLink(ctx interface{}, subject interface{}, expirySeconds interface{}, queryParams interface{}, additionalClaims interface{}, magicLinkURL interface{}) *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call {
	return &MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call{Call: _e.mock.On("GenerateMagicLink", ctx, subject, expirySeconds, queryParams, additionalClaims, magicLinkURL)}
}

func (_c *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call) Run(run func(ctx context.Context, subject string, expirySeconds int64, queryParams map[string]string, additionalClaims map[string]interface{}, magicLinkURL string)) *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call) Return(s string, serviceError *serviceerror.ServiceError) *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call) RunAndReturn(run func(ctx context.Context, subject string, expirySeconds int64, queryParams map[string]string, additionalClaims map[string]interface{}, magicLinkURL string) (string, *serviceerror.ServiceError)) *MagicLinkAuthnServiceInterfaceMock_GenerateMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMagicLink provides a mock function for the type MagicLinkAuthnServiceInterfaceMock
func (_mock *MagicLinkAuthnServiceInterfaceMock) VerifyMagicLink(ctx context.Context, token string, subjectAttribute string) (*entityprovider.Entity, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, token, subjectAttribute)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMagicLink")
	}

	var r0 *entityprovider.Entity
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entityprovider.Entity, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, token, subjectAttribute)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entityprovider.Entity); ok {
		r0 = returnFunc(ctx, token, subjectAttribute)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, token, subjectAttribute)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMagicLink'
type MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call struct {
	*mock.Call
}

// VerifyMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - subjectAttribute string
func (_e *MagicLinkAuthnServiceInterfaceMock_Expecter) VerifyMagicLink(ctx interface{}, token interface{}, subjectAttribute interface{}) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	return &MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call{Call: _e.mock.On("VerifyMagicLink", ctx, token, subjectAttribute)}
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) Run(run func(ctx context.Context, token string, subjectAttribute string)) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) Return(entity *entityprovider.Entity, serviceError *serviceerror.ServiceError) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Return(entity, serviceError)
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) RunAndReturn(run func(ctx context.Context, token string, subjectAttribute string) (*entityprovider.Entity, *serviceerror.ServiceError)) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Return(run)
	return _c
}
