name: 📚 Docs Validation

on:
  workflow_call:

permissions:
  contents: read

env:
  NODE_VERSION: "lts/*"

jobs:
  build-docs:
    name: 📚 Build Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ⚙️ Set up Node.js and pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📚 Build docs
        run: make build_docs
