// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authzmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/authz"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewAuthorizationServiceInterfaceMock creates a new instance of AuthorizationServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationServiceInterfaceMock {
	mock := &AuthorizationServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizationServiceInterfaceMock is an autogenerated mock type for the AuthorizationServiceInterface type
type AuthorizationServiceInterfaceMock struct {
	mock.Mock
}

type AuthorizationServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationServiceInterfaceMock) EXPECT() *AuthorizationServiceInterfaceMock_Expecter {
	return &AuthorizationServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// EvaluateAccess provides a mock function for the type AuthorizationServiceInterfaceMock
func (_mock *AuthorizationServiceInterfaceMock) EvaluateAccess(ctx context.Context, request authz.AccessEvaluationRequest) (*authz.AccessEvaluationResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateAccess")
	}

	var r0 *authz.AccessEvaluationResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.AccessEvaluationRequest) (*authz.AccessEvaluationResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.AccessEvaluationRequest) *authz.AccessEvaluationResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authz.AccessEvaluationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, authz.AccessEvaluationRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthorizationServiceInterfaceMock_EvaluateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateAccess'
type AuthorizationServiceInterfaceMock_EvaluateAccess_Call struct {
	*mock.Call
}

// EvaluateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - request authz.AccessEvaluationRequest
func (_e *AuthorizationServiceInterfaceMock_Expecter) EvaluateAccess(ctx interface{}, request interface{}) *AuthorizationServiceInterfaceMock_EvaluateAccess_Call {
	return &AuthorizationServiceInterfaceMock_EvaluateAccess_Call{Call: _e.mock.On("EvaluateAccess", ctx, request)}
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccess_Call) Run(run func(ctx context.Context, request authz.AccessEvaluationRequest)) *AuthorizationServiceInterfaceMock_EvaluateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authz.AccessEvaluationRequest
		if args[1] != nil {
			arg1 = args[1].(authz.AccessEvaluationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccess_Call) Return(accessEvaluationResponse *authz.AccessEvaluationResponse, serviceError *common.ServiceError) *AuthorizationServiceInterfaceMock_EvaluateAccess_Call {
	_c.Call.Return(accessEvaluationResponse, serviceError)
	return _c
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccess_Call) RunAndReturn(run func(ctx context.Context, request authz.AccessEvaluationRequest) (*authz.AccessEvaluationResponse, *common.ServiceError)) *AuthorizationServiceInterfaceMock_EvaluateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateAccessBatch provides a mock function for the type AuthorizationServiceInterfaceMock
func (_mock *AuthorizationServiceInterfaceMock) EvaluateAccessBatch(ctx context.Context, request authz.AccessEvaluationsRequest) (*authz.AccessEvaluationsResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateAccessBatch")
	}

	var r0 *authz.AccessEvaluationsResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.AccessEvaluationsRequest) (*authz.AccessEvaluationsResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.AccessEvaluationsRequest) *authz.AccessEvaluationsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authz.AccessEvaluationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, authz.AccessEvaluationsRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateAccessBatch'
type AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call struct {
	*mock.Call
}

// EvaluateAccessBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - request authz.AccessEvaluationsRequest
func (_e *AuthorizationServiceInterfaceMock_Expecter) EvaluateAccessBatch(ctx interface{}, request interface{}) *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call {
	return &AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call{Call: _e.mock.On("EvaluateAccessBatch", ctx, request)}
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call) Run(run func(ctx context.Context, request authz.AccessEvaluationsRequest)) *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authz.AccessEvaluationsRequest
		if args[1] != nil {
			arg1 = args[1].(authz.AccessEvaluationsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call) Return(accessEvaluationsResponse *authz.AccessEvaluationsResponse, serviceError *common.ServiceError) *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call {
	_c.Call.Return(accessEvaluationsResponse, serviceError)
	return _c
}

func (_c *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call) RunAndReturn(run func(ctx context.Context, request authz.AccessEvaluationsRequest) (*authz.AccessEvaluationsResponse, *common.ServiceError)) *AuthorizationServiceInterfaceMock_EvaluateAccessBatch_Call {
	_c.Call.Return(run)
	return _c
}
